Repository tari-project/tari, pull requests merged in 2019-03, with the labels that each got.

#127 Basic merkle mountain range
  Cargo.lock
  Cargo.toml
  RFC/src/RFC-0010_CodeStructure.md
  infrastructure/merklemountainrange/Cargo.toml
  infrastructure/merklemountainrange/src/error.rs
  infrastructure/merklemountainrange/src/lib.rs
  infrastructure/merklemountainrange/src/merklemountainrange.rs
  infrastructure/merklemountainrange/src/merklenode.rs
  infrastructure/merklemountainrange/tests/mod.rs
  infrastructure/merklemountainrange/tests/support/hashvalues.rs
  infrastructure/merklemountainrange/tests/support/mod.rs
  infrastructure/merklemountainrange/tests/support/testobject.rs
  infrastructure/merklemountainrange/tests/unit/mmr.rs
  infrastructure/merklemountainrange/tests/unit/mod.rs
Labels: review

#147 Fix circle tests
  Cargo.lock
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
Labels: review

#148 2019 Copyright fixes, added edition 2018, build badge in README
  README.md
  base_layer/p2p/src/lib.rs
  infrastructure/comms/Cargo.toml
  infrastructure/comms/src/connection/i2p/address.rs
  infrastructure/comms/src/connection/i2p/connection.rs
  infrastructure/comms/src/connection/i2p/mod.rs
  infrastructure/comms/src/connection/mod.rs
  infrastructure/comms/src/connection/net_address.rs
  infrastructure/comms/src/connection/onion/address.rs
  infrastructure/comms/src/connection/onion/connection.rs
  infrastructure/comms/src/connection/onion/mod.rs
  infrastructure/comms/src/connection/p2p/address.rs
  infrastructure/comms/src/connection/p2p/connection.rs
  infrastructure/comms/src/connection/p2p/mod.rs
  infrastructure/comms/src/peer_manager/ban_list.rs
  infrastructure/comms/src/peer_manager/liveness.rs
  infrastructure/comms/src/peer_manager/manager.rs
  infrastructure/comms/src/peer_manager/message.rs
  infrastructure/comms/src/peer_manager/mod.rs
  infrastructure/comms/src/peer_manager/peer.rs
  infrastructure/comms/src/peer_manager/routing_table.rs
  infrastructure/comms/src/peer_manager/storage.rs
  infrastructure/comms/src/pubsub/mod.rs
  infrastructure/comms/src/router.rs
  infrastructure/comms/src/rpc/deserialize.rs
  infrastructure/comms/src/rpc/mod.rs
  infrastructure/comms/src/rpc/serialize.rs
  infrastructure/comms/src/server/mod.rs
  infrastructure/comms/tests/mod.rs
Labels: review

#153 github pages fix
  .circleci/config.yml
Labels: review

#154 Resolve issue with RFC deploys
  .circleci/config.yml
Labels: review

#155 Try resolve GH-pages deploy issues
  .circleci/config.yml
Labels: review

#157 Replaced gh-pages with script
  .circleci/config.yml
Labels: review

#158 Fix invalid argument for mktemp
  .circleci/config.yml
Labels: review

#159 Fix no book subdir
  .circleci/config.yml
Labels: review

#156 RFC refactor for Validator Nodes and Asset Management sections
  RFC/src/RFC-0300_DAN.md
  RFC/src/RFC-0302_ValidatorNodes.md
  RFC/src/RFC-0303_VNRegistration.md
  RFC/src/RFC-0304_VNCommittees.md
  RFC/src/RFC-0310_AssetManagement.md
  RFC/src/RFC-0310_AssetTemplates.md
  RFC/src/RFC-0311_AssetTemplates.md
  RFC/src/RFC-0312_AssetRegistration.md
  RFC/src/RFC-0313_AssetReadAPI.md
  RFC/src/RFC-0314_AssetDiscovery.md
  RFC/src/RFC-0315_AssetTransfer.md
  RFC/src/RFC-0316_AssetRetirement.md
  RFC/src/RFC-0320_ValidatorNodes.md
  RFC/src/RFC-0322_VNRegistration.md
  RFC/src/RFC-0341_AssetRegistration.md
  RFC/src/SUMMARY.md
Labels: review

#143 Implement a #[derive(...)] macro for Hashable ordering
  RFC/src/RFC-0010_CodeStructure.md
  base_layer/core/Cargo.toml
  base_layer/core/src/transaction.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
  infrastructure/derive/Cargo.toml
  infrastructure/derive/src/lib.rs
Labels: review

#144 Added transaction kernel signature verification
  base_layer/core/src/block.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/transaction.rs
  base_layer/core/src/transaction_builder.rs
  base_layer/core/src/types.rs
  infrastructure/crypto/src/ristretto/pedersen.rs
Labels: review

#140 Expanded unit tests and fixed indexing utility functions on MMR
  RFC/src/RFC-0010_CodeStructure.md
  infrastructure/merklemountainrange/src/lib.rs
  infrastructure/merklemountainrange/src/merklemountainrange.rs
  infrastructure/merklemountainrange/tests/support/hashvalues.rs
  infrastructure/merklemountainrange/tests/unit/mmr.rs
Labels: review

#160 Add GPG key for neonknight64
  meta/gpg_keys/neonknight64.asc
Labels: review

#163 Delete duplicate RFC placeholders
  Cargo.lock
  RFC/src/RFC-0303_VNRegistration.md
  RFC/src/RFC-0312_AssetRegistration.md
  RFC/src/SUMMARY.md
Labels: review

#171 Add LaTex markup rendering to Docs
  Makefile
  infrastructure/crypto/src/commitment.rs
  meta/assets/rustdoc-include-katex-header.html
Labels: review

#162 Implement MuSig on Ristretto
  Cargo.lock
  base_layer/core/src/transaction.rs
  infrastructure/crypto/src/challenge.rs
  infrastructure/crypto/src/keys.rs
  infrastructure/crypto/src/lib.rs
  infrastructure/crypto/src/macros.rs
  infrastructure/crypto/src/musig.rs
  infrastructure/crypto/src/ristretto/mod.rs
  infrastructure/crypto/src/ristretto/musig.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
  infrastructure/crypto/src/ristretto/ristretto_sig.rs
  infrastructure/crypto/src/ristretto/test_common.rs
  infrastructure/crypto/src/signatures.rs
Labels: review

#150 RFC-0301_NamespaceRegistration
  RFC/src/RFC-0301_NamespaceRegistration.md
Labels: RFC, review

#173 Follow the Rust convention for `as_bytes`
  base_layer/core/src/transaction.rs
  infrastructure/crypto/src/common.rs
  infrastructure/crypto/src/musig.rs
  infrastructure/crypto/src/ristretto/musig.rs
  infrastructure/crypto/src/ristretto/pedersen.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
  infrastructure/crypto/src/ristretto/ristretto_sig.rs
Labels: review

#174 Refactor `HomomorphicCommitment`
  base_layer/core/src/transaction.rs
  base_layer/core/src/types.rs
  infrastructure/crypto/src/commitment.rs
  infrastructure/crypto/src/ristretto/pedersen.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
Labels: review

#27 Asset templates
  RFC/src/Glossary.md
  RFC/src/RFC-0001_overview.md
  RFC/src/RFC-0301_NamespaceRegistration.md
  RFC/src/RFC-0311_AssetTemplates.md
Labels: RFC, in progress

#176 Replace double bars in table
  RFC/src/RFC-0311_AssetTemplates.md
Labels: review

#179 Raid validation #178
  RFC/src/RFC-0311_AssetTemplates.md
Labels: review

#170 Key Manager, File Backup with Mnemonic System
  Cargo.toml
  base_layer/keymanager/Cargo.toml
  base_layer/keymanager/src/diacritics.rs
  base_layer/keymanager/src/file_backup.rs
  base_layer/keymanager/src/keymanager.rs
  base_layer/keymanager/src/lib.rs
  base_layer/keymanager/src/mnemonic.rs
  base_layer/keymanager/src/mnemonic_wordlists.rs
  infrastructure/crypto/Cargo.toml
  infrastructure/crypto/src/lib.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
  infrastructure/tari_util/src/bit.rs
  infrastructure/tari_util/src/lib.rs
Labels: review

#202 Added scripts to generate code coverage reports
  .gitignore
  scripts/code_coverage.sh
  scripts/code_coverage_blockchain.sh
  scripts/code_coverage_comms.sh
  scripts/code_coverage_crypto.sh
  scripts/code_coverage_keymanager.sh
  scripts/code_coverage_merklemountainrange.sh
  scripts/code_coverage_storage.sh
  scripts/code_coverage_tari_core.sh
Labels: review

#182 Serialisation RFC
  .circleci/config.yml
  Cargo.lock
  RFC/src/RFC-0171_MessageSerialisation.md
  RFC/src/SUMMARY.md
  base_layer/core/Cargo.toml
  base_layer/core/src/lib.rs
  base_layer/core/src/message.rs
Labels: review

#205 Fix formatting
  base_layer/core/src/message.rs
Labels: review

#207 Release 0.0.1 - First crates.io publication
  Cargo.lock
  base_layer/README.md
  base_layer/core/Cargo.toml
  base_layer/core/README.md
  base_layer/core/src/message.rs
  base_layer/core/src/transaction.rs
  base_layer/core/src/types.rs
  base_layer/keymanager/Cargo.toml
  base_layer/keymanager/src/keymanager.rs
  base_layer/keymanager/src/mnemonic.rs
  infrastructure/comms/Cargo.toml
  infrastructure/comms/README.md
  infrastructure/comms/src/connection/net_address/mod.rs
  infrastructure/comms/src/lib.rs
  infrastructure/comms/tests/mod.rs
  infrastructure/crypto/Cargo.toml
  infrastructure/crypto/README.md
  infrastructure/crypto/benches/signatures.rs
  infrastructure/crypto/src/challenge.rs
  infrastructure/crypto/src/keys.rs
  infrastructure/crypto/src/ristretto/musig.rs
  infrastructure/crypto/src/ristretto/ristretto_keys.rs
  infrastructure/crypto/src/ristretto/ristretto_sig.rs
  infrastructure/derive/Cargo.toml
  infrastructure/derive/README.md
  infrastructure/merklemountainrange/Cargo.toml
  infrastructure/merklemountainrange/README.md
  infrastructure/storage/Cargo.toml
  infrastructure/storage/README.md
  infrastructure/storage/src/lib.rs
  infrastructure/storage/src/lmdb.rs
  infrastructure/tari_util/Cargo.toml
  infrastructure/tari_util/README.md
  scripts/publish_crates.sh
Labels: review
