Repository tari-project/tari, pull requests merged in 2020-10, with the labels that each got.

#2156 Add sha3 as pow option
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/blocks.rs
  applications/tari_app_grpc/src/conversions/block_header.rs
  applications/tari_app_grpc/src/conversions/new_block_template.rs
  applications/tari_app_utilities/Cargo.toml
  applications/tari_app_utilities/src/identity_management.rs
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/test_faucet/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/mining/cpu_miner.rs
  base_layer/core/src/mining/miner.rs
  base_layer/core/src/mining/mod.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proof_of_work/proof_of_work_algorithm.rs
  base_layer/core/src/proof_of_work/sha3_pow.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  infrastructure/storage/Cargo.toml
Labels: Consensus Change

#2338 Small refactor of `fetch_headers`
  base_layer/core/src/base_node/validators/header_iter.rs
  base_layer/core/src/base_node/validators/headers.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/iterators/chunk.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/horizon_state_sync.rs
  base_layer/core/tests/median_timestamp.rs
Labels: Base node

#2393 Update wire mode for Ridcully
  base_layer/core/src/blocks/genesis_block.rs
  comms/src/connection_manager/wire_mode.rs
Labels: Network Breaking
