Repository tari-project/tari, pull requests merged in 2021-11, with the labels that each got.

#3515 test: fix stack overflow for noise::larger_writes test 1.57-nightly
  comms/src/noise/socket.rs
Labels: mq-approved

#3514 chore: update toolchain to nightly-2021-09-18
  .circleci/config.yml
  .github/workflows/audit.yml
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
  .github/workflows/libwallet.yml
  Cargo.lock
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_stratum_transcoder/src/proxy.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/p2p/src/comms_connector/pubsub.rs
  base_layer/p2p/src/dns/client.rs
  base_layer/p2p/src/dns/mock.rs
  base_layer/p2p/src/services/liveness/state.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/resources.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet_ffi/src/lib.rs
  common/examples/base_node_init.rs
  comms/dht/src/network_discovery/discovering.rs
  comms/src/multiplexing/yamux.rs
  rust-toolchain.toml
Labels: mq-approved

#3509 feat: tracing for console wallet
  Cargo.lock
  applications/tari_base_node/src/main.rs
  applications/tari_mining_node/src/stratum/stratum_miner/job_shared_data.rs
  applications/tari_mining_node/src/stratum/stratum_statistics/stats.rs
  base_layer/core/src/mempool/config.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/mmr/src/merkle_proof.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/contacts_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/master_key_manager.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/storage/database.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  base_layer/wallet/src/wallet.rs
Labels: mq-approved, mq-failed

#3520 fix: header sync must allow transition to archival/pruned if tip is behind
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
Labels: mq-approved

#3522 chore: fix clippy warnings
  applications/tari_base_node/src/main.rs
  applications/tari_mining_node/src/stratum/stratum_miner/job_shared_data.rs
  applications/tari_mining_node/src/stratum/stratum_statistics/stats.rs
  base_layer/core/src/mempool/config.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/mmr/src/merkle_proof.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/src/test_utils/factories/net_address.rs
Labels: mq-approved

#3523 chore: upgrade cucumber
  integration_tests/features/support/ffi_steps.js
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3485 docs: rfc-0240 XTR-BTC atomic swap
  RFC/src/RFC-0240_AtomicSwap.md
  RFC/src/SUMMARY.md
Labels: mq-approved

#3512 feat: add a Rejected status to TransactionStatus
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/common_types/src/transaction.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/transaction_service/storage.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
Labels: mq-approved

#3508 fix: edge case fix for integer pair iter
  base_layer/core/src/iterators/chunk.rs
Labels: mq-approved

#3530 chore: fix doc test
  RFC/src/RFC-0240_AtomicSwap.md
Labels: mq-approved

#3505 feat!: implement new CipherSeed and upgrade encryption KDF
  Cargo.lock
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/main.rs
  applications/tari_console_wallet/src/recovery.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/error.rs
  base_layer/key_manager/src/file_backup.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/mnemonic.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/migrations/2021-10-27-103505_update_key_manager_state/down.sql
  base_layer/wallet/migrations/2021-10-27-103505_update_key_manager_state/up.sql
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/master_key_manager.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/storage/database.rs
  base_layer/wallet/src/storage/sqlite_db.rs
  base_layer/wallet/src/storage/sqlite_utilities.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/util/encryption.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service/storage.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3533 test: turn off multiplexing for cargo on cucumber
  .circleci/config.yml
Labels: mq-approved

#3531 test: reset cucumber timeouts to practical limits
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  integration_tests/features/Mempool.feature
  integration_tests/features/Sync.feature
  integration_tests/features/TransactionInfo.feature
  integration_tests/features/WalletCli.feature
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/WalletRoutingMechanism.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/config.js
  integration_tests/helpers/miningNodeProcess.js
Labels: mq-approved

#3542 fix: check for previously cancelled completed txn before accepting a repeat message
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
Labels: mq-approved

#3536 fix: prevent race condition between block propagation and sync
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: mq-approved

#3547 fix: remove dns resolver config from cucumber tests, use default
  integration_tests/helpers/config.js
Labels: mq-approved

#3548 fix(rpc)!: read from substream while streaming to check for interruptions
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/server/error.rs
  comms/src/protocol/rpc/server/mod.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved

#3549 fix: add check for old db encryption and provide warning
  base_layer/wallet/migrations/2021-10-27-103505_update_key_manager_state/down.sql
  base_layer/wallet/migrations/2021-10-27-103505_update_key_manager_state/up.sql
  base_layer/wallet/src/storage/sqlite_db.rs
  base_layer/wallet/src/storage/sqlite_utilities.rs
Labels: mq-approved

#3545 fix: update the seed words used in the Daily tests
  applications/daily_tests/cron_jobs.js
Labels: mq-approved

#3540 ci: switch off cargo multiplexing for build binaries action
  .github/workflows/base_node_binaries.yml
Labels: mq-approved

#3546 fix: add decision step between header sync and pruned/archival
  base_layer/core/src/base_node/chain_metadata_service/handle.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/error.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/state_machine_service/states/mod.rs
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/tests/helpers/chain_metadata.rs
  base_layer/p2p/src/services/liveness/state.rs
Labels: mq-approved

#3538 feat: add ffi get mnemonic wordlist
  Cargo.lock
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/mnemonic.rs
  base_layer/wallet_ffi/src/enums.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/ffi_steps.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/seedWords.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/walletClient.js
  integration_tests/helpers/walletFFIClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#3537 feat: optimize transaction validation for wallet
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/wallet/migrations/2021-10-28-164318_add_transaction_signature/down.sql
  base_layer/wallet/migrations/2021-10-28-164318_add_transaction_signature/up.sql
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service/storage.rs
  comms/dht/src/crypt.rs
Labels: mq-approved

#3528 refactor!: remove outdated wallet_ffi balance methods
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/ffi_steps.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/walletFFIClient.js
Labels: mq-approved

#3519 test: various cucumber fixes
  common/src/configuration/global.rs
  comms/dht/src/actor.rs
  comms/dht/src/connectivity/mod.rs
  integration_tests/features/Reorgs.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/config.js
Labels: mq-approved, mq-priority

#3527 fix: use time crate instead of chrono
  Cargo.lock
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/README.md
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/ui/components/notification_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
Labels: mq-approved

#3554 chore: fix dev broken cucumber
  integration_tests/features/support/steps.js
Labels: mq-approved

#3541 refactor: split sqlitedb file
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
Labels: mq-approved

#3557 feat: add support for MultiAddr in RPC config
  Cargo.lock
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/config.rs
  applications/tari_mining_node/src/errors.rs
  applications/tari_mining_node/src/main.rs
  applications/tari_stratum_transcoder/Cargo.toml
  applications/tari_stratum_transcoder/src/main.rs
  applications/tari_stratum_transcoder/src/proxy.rs
  common/src/configuration/global.rs
Labels: mq-approved

#3560 test: fixed broken cucumber tests due to failed wallet startup
  integration_tests/features/Reorgs.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletProcess.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3558 fix: stop leak of value of recovered output
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
Labels: mq-approved

#3556 ci: add workflow dispatch to libwallet build action
  .github/workflows/libwallet.yml
Labels: mq-approved

#3562 fix: avoid implicit using of the time crate
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/ui/components/notification_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/common/json_rpc.rs
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_stratum_transcoder/Cargo.toml
  applications/tari_stratum_transcoder/src/common/json_rpc.rs
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/utc.rs
  base_layer/wallet_ffi/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
Labels: mq-approved

#3559 chore: add node id/public key to log mdc
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/main.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/state_machine_service/initializer.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/mempool/async_mempool.rs
  base_layer/core/src/mempool/sync_protocol/initializer.rs
  common/logging/log4rs_sample_base_node.yml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/discovery/service.rs
  comms/src/connectivity/manager.rs
Labels: mq-approved

#3564 test: fix cucumber console wallet startup
  applications/tari_console_wallet/src/wallet_modes.rs
  integration_tests/features/WalletCli.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3566 test: reduce cucumber ci to critical only
  .circleci/config.yml
  Cargo.lock
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/main.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
Labels: mq-approved

#3567 feat: trigger time lock balance update when block received
  Cargo.lock
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
Labels: mq-approved

#3552 feat: add atomic swap htlc sending and claiming
  Cargo.lock
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet/tests/transaction_service/service.rs
  clients/wallet_grpc_client/index.js
  docs/book.toml
  docs/src/btc_atomic_swap.md
  integration_tests/features/WalletTransfer.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#3572 test: make monerod stagenet usage resilient
  integration_tests/features/support/steps.js
  integration_tests/helpers/mergeMiningProxyProcess.js
Labels: mq-approved

#3571 feat: get fee for transactions for stratum transcoder
  applications/tari_stratum_transcoder/src/proxy.rs
Labels: mq-approved

#3574 docs: rfc 0250_Covenants
  RFC/src/BaseLayerExtensions.md
  RFC/src/RFC-0250_Covenants.md
  RFC/src/SUMMARY.md
Labels: mq-approved

#3575 feat(wallet): import utxo’s as EncumberedToBeReceived rather than Unspent
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3583 ci: split cucumber job into two
  .circleci/config.yml
  integration_tests/features/WalletTransactions.feature
Labels: mq-approved

#3578 feat: add error codes to LibWallet for CipherSeed errors
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3577 feat: improve wallet connectivity status for console wallet
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/tests/transaction_service/service.rs
Labels: mq-approved

#3573 feat: add atomic swap refund transaction handling
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/unblinded_output.rs
  applications/tari_base_node/src/builder.rs
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/wallet/migrations/2021-11-11-094000_add_script_lock_height/down.sql
  base_layer/wallet/migrations/2021-11-11-094000_add_script_lock_height/up.sql
  base_layer/wallet/src/base_node_service/mock_base_node_service.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service/storage.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service/storage.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  clients/wallet_grpc_client/index.js
  integration_tests/features/WalletTransfer.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletClient.js
Labels: mq-approved

#3586 fix: allow bullet proof value only rewinding in atomic swaps
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: mq-approved

#3584 fix: update daily test start times and seed phrase
  applications/daily_tests/automatic_recovery_test.js
  applications/daily_tests/automatic_sync_test.js
  applications/daily_tests/cron_jobs.js
Labels: mq-approved

#3585 refactor: clean up unwraps in wallet_ffi
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#3593 refactor: update miningcore repository links
  README.md
Labels: mq-approved

#3579 fix: remove delay from last request latency call
  Cargo.lock
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  common/Cargo.toml
  comms/rpc_macros/src/generator.rs
  comms/src/protocol/rpc/client/mod.rs
  comms/src/protocol/rpc/client/tests.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved, mq-failed

#3587 fix: allow bullet proof value only rewinding off one-sided transaction
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: Consensus Change, mq-approved

#3595 chore: upgrade tokio deps #3581
  Cargo.lock
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/service_framework/src/reply_channel.rs
  base_layer/wallet/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  comms/src/protocol/rpc/client/mod.rs
Labels: mq-approved

#3597 feat: track ping failures and disconnect
  base_layer/p2p/src/services/liveness/config.rs
  base_layer/p2p/src/services/liveness/error.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/src/services/liveness/state.rs
Labels: mq-approved

#3576 chore: minor clippy fixes
  applications/tari_app_grpc/src/conversions/aggregate_body.rs
  base_layer/core/src/proto/mod.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/proto/utils.rs
Labels: mq-approved

#3590 feat: language detection for mnemonic seed words
  base_layer/key_manager/src/mnemonic.rs
Labels: mq-approved

#3580 refactor: remove tari_common dependency from tari_comms
  applications/tari_console_wallet/src/recovery.rs
  comms/Cargo.toml
  comms/src/peer_manager/error.rs
Labels: mq-approved

#3603 docs: ignore RFC code blocks
  RFC/src/RFC-0250_Covenants.md
Labels: mq-approved, mq-priority

#3602 feat: use CipherSeed wallet birthday for recovery start point
  base_layer/core/src/base_node/sync/rpc/mod.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/wallet/src/storage/database.rs
  base_layer/wallet/src/storage/sqlite_db.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  base_layer/wallet/tests/wallet/mod.rs
  integration_tests/features/WalletRecovery.feature
Labels: mq-approved

#3599 test: improve cucumber scenario robustness
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3601 feat!: expose reason for transaction cancellation for callback in wallet_ffi
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/p2p/src/services/liveness/state.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service/transaction_protocols.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/wallet.js
Labels: mq-approved

#3605 feat: add ban peers metric
  comms/src/connectivity/manager.rs
  comms/src/connectivity/metrics.rs
Labels: mq-approved

#3607 fix: seed word parsing
  base_layer/key_manager/src/error.rs
  base_layer/key_manager/src/mnemonic.rs
  base_layer/wallet_ffi/src/enums.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3608 fix: improve handling of old base nodes and reorgs in wallet recovery
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
Labels: mq-approved

#3614 docs: update covenants links
  RFC/src/RFC-0250_Covenants.md
Labels: mq-approved

#3611 feat: display network for console wallet
  applications/tari_console_wallet/src/ui/components/menu.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
Labels: mq-approved

#3612 chore: add pub key in the dailes notify
  applications/daily_tests/cron_jobs.js
Labels: mq-approved

#3613 feat: add page for detailed mempool in explorer
  applications/tari_explorer/app.js
  applications/tari_explorer/routes/mempool.js
  applications/tari_explorer/views/index.hbs
  applications/tari_explorer/views/mempool.hbs
Labels: mq-approved

#3596 feat: implement dht pooled db connection
  Cargo.lock
  base_layer/core/tests/base_node_rpc.rs
  base_layer/key_manager/src/mnemonic.rs
  base_layer/wallet/src/contacts_service/error.rs
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/tests/contacts_service/mod.rs
  base_layer/wallet/tests/wallet/mod.rs
  common_sqlite/src/error.rs
  comms/dht/Cargo.toml
  comms/dht/src/actor.rs
  comms/dht/src/dedup/dedup_cache.rs
  comms/dht/src/dht.rs
  comms/dht/src/storage/connection.rs
  comms/dht/src/storage/database.rs
  comms/dht/src/storage/error.rs
  comms/dht/src/store_forward/database/mod.rs
  comms/dht/src/store_forward/service.rs
Labels: mq-approved

#3620 feat: only trigger UTXO scanning when a new block event is received
  applications/daily_tests/cron_jobs.js
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/wallet/src/base_node_service/handle.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/mod.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/console_wallet.toml
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  integration_tests/helpers/config.js
Labels: mq-approved

#3615 feat!: add tcp bypass settings for tor in wallet_ffi
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  comms/dht/src/macros.rs
  comms/src/tor/hidden_service/proxy_opts.rs
  integration_tests/helpers/ffi/ffiInterface.js
Labels: mq-approved

#3610 chore: change status line
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/src/parser.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
Labels: mq-approved

#3621 test: increase timeout in cucumber
  integration_tests/features/support/steps.js
Labels: mq-approved

#3619 fix!: console wallet grpc_console_wallet_addresss config
  README.md
  applications/launchpad/docker_rig/config.toml
  applications/launchpad/docker_rig/docker-compose.yml
  applications/tari_app_utilities/src/initialization.rs
  common/config/presets/base_node.toml
  common/config/presets/console_wallet.toml
  common/config/presets/mining_node.toml
  common/src/configuration/bootstrap.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  integration_tests/features/support/steps.js
  integration_tests/helpers/config.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3618 feat: add bulletproof rewind profiling
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/utxo_scanner_service/handle.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet_ffi/src/tasks.rs
  common/src/configuration/global.rs
  integration_tests/package-lock.json
Labels: mq-approved

#3625 feat: improve wallet responsiveness
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
Labels: mq-approved

#3630 feat: removed transaction validation redundant events
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
Labels: mq-approved

#3631 test: removed stress test log target
  applications/launchpad/docker_rig/log4rs.yml
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/tasks/send_finalized_transaction.rs
  base_layer/wallet/src/transaction_service/tasks/wait_on_dial.rs
  common/logging/log4rs_debug_sample.yml
  common/logging/log4rs_sample_base_node.yml
  integration_tests/log4rs/base_node.yml
Labels: mq-approved
