Repository tari-project/tari, pull requests merged in 2021-09, with the labels that each got.

#3267 fix: make logging less noisy
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connection_manager/requester.rs
  comms/src/connectivity/requester.rs
  comms/src/noise/config.rs
  comms/src/protocol/identity.rs
  comms/src/protocol/messaging/outbound.rs
  comms/src/protocol/rpc/client.rs
  comms/src/socks/client.rs
Labels: mq-approved

#3278 chore: add network to Base Node status line
  applications/tari_base_node/src/command_handler.rs
Labels: mq-approved

#3280 chore: update to v0.9.6
  .github/workflows/base_node_binaries.yml
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_mining_node/Cargo.toml
  applications/test_faucet/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/wallet/Cargo.toml
  changelog.md
  common/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: mq-approved, mq-priority

#3275 fix: update cucumber tests for walletffi.feature
  .circleci/config.yml
  Cargo.lock
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/ffi/byteVector.js
  integration_tests/helpers/ffi/commsConfig.js
  integration_tests/helpers/ffi/completedTransaction.js
  integration_tests/helpers/ffi/completedTransactions.js
  integration_tests/helpers/ffi/contact.js
  integration_tests/helpers/ffi/contacts.js
  integration_tests/helpers/ffi/emojiSet.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/pendingInboundTransaction.js
  integration_tests/helpers/ffi/pendingInboundTransactions.js
  integration_tests/helpers/ffi/pendingOutboundTransaction.js
  integration_tests/helpers/ffi/pendingOutboundTransactions.js
  integration_tests/helpers/ffi/privateKey.js
  integration_tests/helpers/ffi/publicKey.js
  integration_tests/helpers/ffi/seedWords.js
  integration_tests/helpers/ffi/transportType.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/util.js
  integration_tests/helpers/walletFFIClient.js
Labels: mq-approved

#3286 test: remove @broken keyword from working tests
  integration_tests/features/Mempool.feature
  integration_tests/features/Sync.feature
Labels: mq-approved

#3274 feat: add get-db-stats command
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/parser.rs
  applications/tari_base_node/src/table.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/chain_storage/stats.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/test_helpers/blockchain.rs
  common/src/configuration/global.rs
  infrastructure/storage/src/lmdb_store/store.rs
  infrastructure/storage/tests/lmdb.rs
Labels: mq-approved

#3281 feat: add base installer stubs
  .dockerignore
  Cargo.toml
  applications/installer/Cargo.toml
  applications/installer/src/config/base_node.rs
  applications/installer/src/config/combined.rs
  applications/installer/src/config/common.rs
  applications/installer/src/config/mining.rs
  applications/installer/src/config/mod.rs
  applications/installer/src/config/wallet.rs
  applications/installer/src/main.rs
  applications/installer/src/utils/mod.rs
  applications/tari_console_wallet/Cargo.toml
  buildtools/docker/base_node.Dockerfile
  buildtools/docker_rig/README.md
  buildtools/docker_rig/base_node.Dockerfile
  buildtools/docker_rig/console_wallet.Dockerfile
  buildtools/docker_rig/docker-compose.yml
  buildtools/docker_rig/start_base_node.sh
  buildtools/docker_rig/start_wallet.sh
  buildtools/docker_rig/tor.Dockerfile
  buildtools/docker_rig/torrc
  integration_tests/helpers/ffi/walletFFI.js
Labels: mq-approved

#3283 chore: update randomx
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: mq-approved

#3276 feat: add logging of Monero PoW data to debug merge mining
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: mq-approved

#3284 feat: update+notifications for console wallet
  Cargo.lock
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/ui/app.rs
  applications/tari_console_wallet/src/ui/components/component.rs
  applications/tari_console_wallet/src/ui/components/mod.rs
  applications/tari_console_wallet/src/ui/components/notification_tab.rs
  applications/tari_console_wallet/src/ui/components/tabs_container.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  clients/wallet_grpc_client/.prettierrc
  clients/wallet_grpc_client/index.js
  common/config/presets/tari_config_example.toml
  integration_tests/features/BaseNodeAutoUpdate.feature
  integration_tests/features/WalletAutoUpdate.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletClient.js
Labels: mq-approved

#3289 chore: change CI timeout to 20 minutes
  .circleci/config.yml
Labels: mq-approved

#3291 chore: update deps
  Cargo.lock
  base_layer/p2p/Cargo.toml
Labels: mq-approved

#3285 fix: resolved design flaw in wallet_ffi library
  .circleci/config.yml
  Cargo.lock
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/ffi/completedTransaction.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/transactionKernel.js
Labels: mq-approved

#3290 chore: update windows tor version
  buildtools/install_tor_services.bat
Labels: mq-approved

#3297 fix: ban header sync peer if no headers provided
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: mq-approved

#3298 test: rpc edge case test for early stream exit
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved

#3296 refactor: misc minor improvements + add MissTickBehaviour to all timeouts
  applications/tari_base_node/src/main.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/p2p/src/services/liveness/service.rs
  common/Cargo.toml
  common/src/configuration/bootstrap.rs
  comms/dht/src/actor.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/store_forward/service.rs
  comms/src/connection_manager/dial_state.rs
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/manager.rs
  comms/src/connection_manager/requester.rs
  comms/src/connection_manager/tests/listener_dialer.rs
  comms/src/connectivity/manager.rs
  comms/src/protocol/messaging/error.rs
  comms/src/protocol/messaging/outbound.rs
  comms/src/rate_limit.rs
  comms/src/test_utils/mocks/connection_manager.rs
  infrastructure/storage/tests/lmdb.rs
Labels: mq-approved

#3299 chore: upgrade to tokio 1.11
  Cargo.lock
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_mining_node/Cargo.toml
  applications/tari_stratum_transcoder/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: mq-approved

#3300 fix: dedup sql error when deleting many entries
  comms/dht/src/actor.rs
  comms/dht/src/dedup/dedup_cache.rs
Labels: mq-approved

#3306 revert: fix ban header syn peer if no headers provided (#3297)
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: mq-approved, mq-priority

#3295 feat: ping-peer command
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/parser.rs
  base_layer/p2p/src/services/liveness/handle.rs
Labels: mq-approved

#3301 fix: randomx memory usage
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: mq-approved

#3260 fix: prevent immediate run of wallet recovery on cron script
  applications/daily_tests/automatic_recovery_test.js
  applications/daily_tests/cron_jobs.js
Labels: mq-approved

#3261 feat: show status avx2 feature and randomx count and flags
  applications/tari_base_node/src/command_handler.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/ui/components/menu.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_service.rs
Labels: mq-approved

#3303 chore: mark broken tests and add interval print for long grpc call
  integration_tests/features/Propagation.feature
  integration_tests/features/Reorgs.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/support/world.js
Labels: mq-approved

#3308 fix: reduce overly-eager connection reaping for slow connections
  comms/examples/stress/node.rs
  comms/examples/stress/service.rs
  comms/examples/stress_test.rs
  comms/src/builder/comms_node.rs
  comms/src/connection_manager/tests/manager.rs
  comms/src/connectivity/config.rs
  comms/src/connectivity/manager.rs
  comms/src/connectivity/test.rs
  comms/src/multiplexing/yamux.rs
Labels: mq-approved

#3248 fix: disable P2P transaction negotiation while recovery is in progress
  base_layer/wallet/src/test_utils.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
Labels: mq-approved, mq-failed

#3305 ci: run builds and ci on ubuntu 18.04
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
Labels: mq-approved

#3309 chore: fix 3 cucumber tests
  integration_tests/features/Propagation.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
Labels: mq-approved

#3312 fix: disconnected node was never ready
  base_layer/core/src/base_node/chain_metadata_service/service.rs
Labels: mq-approved

#3313 fix: always grow database when asked to resize
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  infrastructure/storage/src/lmdb_store/store.rs
Labels: mq-approved

#3314 chore: update headers requests to use vec::with_capacity
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: mq-approved

#3316 chore: delete unnecessary space character
  applications/tari_base_node/src/command_handler.rs
Labels: mq-approved

#3236 fix: block sync validation
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/validators.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/validation/block_validators.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/mod.rs
  base_layer/core/src/validation/traits.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/block_validation.rs
  integration_tests/helpers/transactionBuilder.js
Labels: mq-approved

#3318 refactor: assimilate the base node grpc client into the M O N O R E P O
  clients/base_node_grpc_client/README.md
  clients/base_node_grpc_client/package-lock.json
  clients/base_node_grpc_client/package.json
  clients/base_node_grpc_client/src/index.js
  clients/base_node_grpc_client/src/index.test.js
Labels: mq-approved

#3321 fix: handle stream read error case by explicitly closing the substream
  applications/tari_base_node/src/command_handler.rs
  base_layer/wallet/src/connectivity_service/test.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  base_layer/wallet/tests/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service/transaction_protocols.rs
  comms/rpc_macros/src/generator.rs
  comms/rpc_macros/src/lib.rs
  comms/rpc_macros/tests/macro.rs
  comms/src/memsocket/mod.rs
  comms/src/multiplexing/yamux.rs
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/handshake.rs
  comms/src/protocol/rpc/mod.rs
  comms/src/protocol/rpc/server/mock.rs
  comms/src/protocol/rpc/server/mod.rs
  comms/src/protocol/rpc/server/router.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved

#3323 test: stratum transcoder tests
  .circleci/config.yml
  applications/tari_stratum_transcoder/src/proxy.rs
  integration_tests/features/StratumTranscoder.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/stratumTranscoderClient.js
  integration_tests/helpers/stratumTranscoderProcess.js
Labels: mq-approved

#3315 fix: wait couple rounds for no pings to send an event
  base_layer/core/src/base_node/chain_metadata_service/handle.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  integration_tests/features/Reorgs.feature
  integration_tests/features/Sync.feature
Labels: mq-approved

#3326 test: shorten cucumber ci run
  integration_tests/features/Recovery.feature
  integration_tests/features/Reorgs.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletCli.feature
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/miningNodeProcess.js
  package-lock.json
Labels: mq-approved

#3327 ci: update nightly image for ci
  .circleci/config.yml
Labels: mq-approved

#3317 refactor: remove mining estimate debug print
  applications/tari_mining_node/src/main.rs
Labels: mq-approved

#3331 docs: renumber staged wallet security RFC and add to summary
  RFC/src/RFC-0153_StagedWalletSecurity.md
  RFC/src/SUMMARY.md
Labels: mq-approved

#3337 test: set wallet recovery base dir + update git repo daily
  applications/daily_tests/cron_jobs.js
  applications/daily_tests/helpers.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3336 feat: rpc response message chunking
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
  base_layer/wallet/src/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/src/proto/rpc.proto
  comms/src/protocol/rpc/body.rs
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/error.rs
  comms/src/protocol/rpc/message.rs
  comms/src/protocol/rpc/mod.rs
  comms/src/protocol/rpc/server/chunking.rs
  comms/src/protocol/rpc/server/mod.rs
  comms/src/protocol/rpc/status.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: Comms, Network Breaking, mq-approved

#3341 fix: remove explicit panic from rpc handshake on io error
  comms/src/protocol/rpc/handshake.rs
Labels: mq-approved

#3345 refactor: remove mutex lock contention by dealing equal work to threads
  base_layer/core/src/validation/block_validators/async_validator.rs
Labels: mq-approved

#3348 fix: update block explorer to use local grpc
  applications/tari_explorer/package-lock.json
  applications/tari_explorer/package.json
  applications/tari_explorer/routes/index.js
Labels: mq-approved

#3349 fix: fix median timestamp index
  base_layer/core/src/validation/header_validator.rs
  base_layer/core/src/validation/helpers.rs
Labels: mq-approved

#3350 fix: invalid forced sync peer now returns configerror
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/main.rs
Labels: mq-approved

#3354 fix: dead_code lint error when base_node_feature is not set
  base_layer/core/src/transactions/aggregated_body.rs
Labels: mq-approved

#3357 fix: stop MTP attack
  applications/tari_mining_node/src/difficulty.rs
  applications/tari_mining_node/src/miner.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/tests/async_db.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/pow_blockchain.rs
  base_layer/core/tests/helpers/test_blockchain.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_service.rs
  base_layer/core/tests/node_state_machine.rs
Labels: mq-approved

#3356 fix: fix regression in cucumber tests for wallet ffi step
  integration_tests/features/support/steps.js
Labels: mq-approved

#3351 ci: add wallet ffi to build
  .github/workflows/ci.yml
Labels: mq-approved

#3362 fix: remove sqlite from windows installer and scripts
  applications/tari_base_node/windows/runtime/source_base_node_env.bat
  applications/tari_base_node/windows/runtime/start_tari_base_node.bat
  applications/tari_console_wallet/windows/runtime/source_console_wallet_env.bat
  applications/tari_console_wallet/windows/runtime/start_tari_console_wallet.bat
  buildtools/install_sqlite.bat
  buildtools/windows_inno_installer.iss
Labels: mq-approved

#3361 test: add flaky tag to transcoder cucumber test
  integration_tests/features/StratumTranscoder.feature
Labels: mq-approved

#3335 ci: rerun flaky tests
  .circleci/config.yml
  integration_tests/.husky/pre-commit
  integration_tests/helpers/baseNodeProcess.js
Labels: mq-approved

#3334 fix: remove unnecessary range proof verify and fix test temp disk usage
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/tests/chain_storage_tests/chain_backend.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/helpers/sample_blockchains.rs
  infrastructure/storage/src/lmdb_store/store.rs
Labels: mq-approved

#3365 fix: relative paths for logs is now relative to data path instead of current execution directory
  common/src/configuration/bootstrap.rs
  common/src/logging.rs
Labels: mq-approved

#3364 fix: pressing b key should not clear existing base node in console wallet
  applications/tari_console_wallet/src/ui/components/network_tab.rs
Labels: mq-approved

#3359 refactor: remove managed peer concept from connectivity manager
  applications/tari_base_node/src/command_handler.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/p2p/src/initialization.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/connectivity/test.rs
  comms/dht/src/network_discovery/discovering.rs
  comms/dht/tests/dht.rs
  comms/src/builder/comms_node.rs
  comms/src/builder/mod.rs
  comms/src/builder/tests.rs
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/manager.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connection_manager/tests/listener_dialer.rs
  comms/src/connection_manager/tests/manager.rs
  comms/src/connectivity/config.rs
  comms/src/connectivity/connection_pool.rs
  comms/src/connectivity/manager.rs
  comms/src/connectivity/requester.rs
  comms/src/connectivity/test.rs
  comms/src/multiplexing/mod.rs
  comms/src/multiplexing/yamux.rs
  comms/src/test_utils/mocks/connectivity_manager.rs
  comms/src/test_utils/mocks/peer_connection.rs
  comms/src/utils/atomic_ref_counter.rs
  comms/src/utils/mod.rs
Labels: mq-approved

#3366 fix: wallet recovery
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
Labels: mq-approved

#3363 ci: create separate mining artifact
  .github/workflows/base_node_binaries.yml
Labels: mq-approved

#3369 fix: additional check for cancelled transactions
  base_layer/wallet/src/transaction_service/service.rs
Labels: mq-approved

#3373 chore: remove dead code file bullet_rangeproofs
  base_layer/core/src/transactions/bullet_rangeproofs.rs
Labels: mq-approved

#3374 refactor: separate wallet_ffi cucumber steps into own file
  integration_tests/features/support/ffi_steps.js
  integration_tests/features/support/steps.js
Labels: mq-approved

#3304 feat: improve console wallet responsiveness
  applications/tari_console_wallet/src/ui/mod.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/debouncer.rs
  applications/tari_console_wallet/src/ui/state/mod.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  applications/tari_console_wallet/src/ui/ui_error.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/service.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
Labels: mq-approved

#3372 feat: merge consensus breaking changes in #3195 #3193 with weatherwax compatibility
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/block_validators/orphan.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/node_service.rs
Labels: mq-approved

#3371 docs: draft RFC-0360: NFT sale via Mimblewimble invoice
  RFC/src/Glossary.md
  RFC/src/RFC-0201_TariScript.md
  RFC/src/RFC-0360_NFTInvoices.md
  RFC/src/SUMMARY.md
Labels: mq-approved

#3287 fix: resolved feature flags for openssl vendoring
  Cargo.lock
  base_layer/wallet_ffi/Cargo.toml
  comms/Cargo.toml
Labels: mq-approved

#3377 feat: implement DHT protocol versioning, includes #3243
  Cargo.lock
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/src/test_utils.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/tests/support/comms_and_services.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/dht/Cargo.toml
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/builder.rs
  comms/dht/src/config.rs
  comms/dht/src/consts.rs
  comms/dht/src/crypt.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/dht.rs
  comms/dht/src/discovery/service.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/inbound/deserialize.rs
  comms/dht/src/inbound/message.rs
  comms/dht/src/lib.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/message.rs
  comms/dht/src/outbound/serialize.rs
  comms/dht/src/store_forward/database/stored_message.rs
  comms/dht/src/store_forward/forward.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/store_forward/store.rs
  comms/dht/src/test_utils/makers.rs
  comms/dht/src/version.rs
  comms/dht/tests/dht.rs
  comms/src/protocol/messaging/outbound.rs
  comms/src/utils/signature.rs
Labels: mq-approved

#3378 chore: sha2 as dev dependency
  Cargo.lock
  base_layer/key_manager/Cargo.toml
Labels: mq-approved

#3376 fix: fix debouncer delay bug
  applications/tari_console_wallet/src/ui/state/debouncer.rs
Labels: mq-approved

#3379 feat: get-peer supports partial node id lookup
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/parser.rs
  comms/src/peer_manager/manager.rs
  comms/src/peer_manager/node_id.rs
  comms/src/peer_manager/peer_storage.rs
  comms/src/peer_manager/wrapper.rs
  infrastructure/storage/src/key_val_store/error.rs
  infrastructure/storage/src/key_val_store/hmap_database.rs
  infrastructure/storage/src/key_val_store/key_val_store.rs
  infrastructure/storage/src/key_val_store/lmdb_database.rs
  infrastructure/storage/src/lmdb_store/store.rs
  infrastructure/storage/tests/lmdb.rs
Labels: mq-approved

#3381 refactor: improve logging when max request size is exceeded
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/error.rs
  comms/src/protocol/rpc/mod.rs
  comms/src/protocol/rpc/server/chunking.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved

#3347 test: reduce max utxo query size
  base_layer/wallet/src/output_manager_service/config.rs
Labels: mq-approved

#3368 docs: add block/transaction weights to RFC
  RFC/src/Glossary.md
  RFC/src/RFC-0110_BaseNodes.md
Labels: mq-approved

#3382 chore: bundle sqlite by default for tests
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/mobile_build.sh
  comms/Cargo.toml
Labels: mq-approved

#3380 fix: fix console wallet tick events endless loop edge case at shutdown
  applications/tari_console_wallet/src/utils/crossterm_events.rs
Labels: mq-approved

#3385 test: fix brokend test and remove @broken
  integration_tests/features/StressTest.feature
Labels: mq-approved

#3387 feat: add substream count to list-connections
  applications/tari_base_node/src/command_handler.rs
Labels: mq-approved

#3395 ci: mark flaky/broken integration tests
  .circleci/config.yml
  .github/wip_integration_tests.yml
  integration_tests/.nvmrc
  integration_tests/features/Mempool.feature
  integration_tests/features/StratumTranscoder.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/ffi_steps.js
  integration_tests/features/support/steps.js
  integration_tests/helpers/util.js
Labels: mq-approved

#3393 feat: display weight, #inputs, #outputs in wallet for txn
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
Labels: mq-approved

#3398 fix: mempool stats reflects unconfirmed pool
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
  base_layer/core/tests/mempool.rs
Labels: mq-approved

#3367 chore: add warning when force sync is enabled
  applications/tari_base_node/src/main.rs
Labels: mq-approved
