Repository tari-project/tari, pull requests merged in 2021-07, with the labels that each got.

#3049 Fix wallet cucumber tests
  integration_tests/features/support/steps.js
  integration_tests/helpers/util.js
Labels: Integration test, tests

#3101 fix: update transaction status from broadcast if already mined
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
Labels: mq-approved

#3086 docs: add RFC-0160 Block Serialization
  RFC/src/Glossary.md
  RFC/src/RFC-0160_BlockSerialization.md
  RFC/src/SUMMARY.md
  base_layer/core/src/blocks/block_header.rs
Labels: mq-approved

#3098 fix: reduce UTXO batch size query limit to account for 4MB frame size
  base_layer/wallet/src/output_manager_service/config.rs
Labels: mq-approved

#3105 feat: add support for `/dns` multiaddrs to dns resolver
  comms/Cargo.toml
  comms/src/socks/client.rs
  comms/src/transports/dns/common.rs
  comms/src/transports/dns/system.rs
  comms/src/transports/dns/tor.rs
Labels: mq-approved

#3099 docs: fix some typos in TariScript RFC
  RFC/src/RFC-0201_TariScript.md
Labels: mq-approved

#3110 fix: don't log tor control port password
  common/src/configuration/global.rs
Labels: mq-approved

#3106 chore: upgrade yamux v0.9.0
  Cargo.lock
  comms/Cargo.toml
  comms/src/multiplexing/yamux.rs
Labels: mq-approved

#3108 test: add cucumber test for wallet password change
  integration_tests/features/WalletPasswordChange.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3070 docs: update RFC-0201/TariScript: Add metadata ComSig to the transaction output
  RFC/src/Glossary.md
  RFC/src/RFC-0201_TariScript.md
Labels: mq-approved

#3082 fix: fix prune mode sync bug introduced in TariScript
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/proto/rpc.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/lmdb_db/mod.rs
  base_layer/core/src/chain_storage/pruned_output.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
Labels: mq-approved

#3109 fix: accumulated block data bitmap now contains current stxo indexes
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/chain_storage/accumulated_data.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/mmr/src/mutable_mmr.rs
Labels: mq-approved

#3126 test: add network with only pruned nodes
  integration_tests/features/Sync.feature
Labels: mq-approved

#3121 fix: console wallet now recognises wallet.network comms settings
  applications/tari_app_utilities/src/initialization.rs
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/bootstrap.rs
  common/src/configuration/global.rs
  common/src/configuration/network.rs
  common/src/configuration/utils.rs
  common/src/lib.rs
Labels: mq-approved

#3127 feat(comms): tcp-only p2p protocol listener
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/transport.rs
  base_layer/wallet/src/testnet_utils.rs
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/global.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/examples/stress/node.rs
  comms/src/builder/comms_node.rs
  comms/src/builder/mod.rs
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/error.rs
  comms/src/connection_manager/listener.rs
  comms/src/connection_manager/manager.rs
  comms/src/connection_manager/mod.rs
  comms/src/connection_manager/requester.rs
  comms/src/connection_manager/tests/listener_dialer.rs
  comms/src/connection_manager/tests/manager.rs
  comms/src/connection_manager/types.rs
  comms/src/runtime.rs
  comms/src/socks/client.rs
  comms/src/test_utils/test_node.rs
  comms/src/tor/hidden_service/builder.rs
  comms/src/tor/hidden_service/controller.rs
  comms/src/tor/hidden_service/mod.rs
  comms/src/transports/dns/tor.rs
  comms/src/transports/helpers.rs
  comms/src/transports/mod.rs
  comms/src/transports/socks.rs
  comms/src/transports/tcp_with_tor.rs
Labels: mq-approved

#3128 feat(wallet): add extra feedback to recovery monitoring callback in Wallet FFI
  applications/tari_console_wallet/src/recovery.rs
  base_layer/wallet/src/utxo_scanner_service/handle.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/src/tasks.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#3131 fix: bug that causes non p2p apps to panic on startup
  common/src/configuration/global.rs
Labels: mq-approved, mq-priority

#3122 test: fix prune mode test
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_app_grpc/src/conversions/chain_metadata.rs
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/proto/chain_metadata.proto
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/wallet/tests/support/rpc.rs
  integration_tests/features/Propagation.feature
  integration_tests/features/Sync.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/baseNodeClient.js
  integration_tests/helpers/config.js
Labels: mq-approved

#3132 test: fix cucumber test wallet environment variables
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  common/src/configuration/bootstrap.rs
  integration_tests/helpers/config.js
  integration_tests/package-lock.json
Labels: mq-approved, mq-failed

#3136 fix: fetch_utxo uses tip deleted bitmap
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: mq-approved

#3137 fix: update transaction and block validator to use full deleted map
  applications/tari_base_node/src/command_handler.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/pruned_output.rs
  base_layer/core/src/validation/block_validators.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/traits.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/helpers/block_builders.rs
Labels: mq-approved, mq-failed

#3138 fix: fix prune mode sync
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/chain_storage/accumulated_data.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/mod.rs
  integration_tests/features/Sync.feature
Labels: mq-approved

#3129 fix: replace usage of RangeProof MR with Witness MR
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/validation/block_validators.rs
  base_layer/core/src/validation/error.rs
Labels: mq-approved

#3140 test: test wallet view all transactions
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
Labels: mq-approved

#3134 chore: rename daemon mode to non-interactive mode
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/README.md
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  common/src/configuration/bootstrap.rs
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3141 fix: improve reliability of get block template protocol in mm proxy
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_merge_mining_proxy/src/block_template_data.rs
  applications/tari_merge_mining_proxy/src/block_template_protocol.rs
  applications/tari_merge_mining_proxy/src/common/merge_mining.rs
  applications/tari_merge_mining_proxy/src/error.rs
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/error.rs
  integration_tests/features/WalletBaseNodeSwitch.feature
  integration_tests/helpers/miningNodeProcess.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3133 test: one-sided support for washing machine script
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/utils/washing_machine.js
  comms/dht/src/connectivity/test.rs
  comms/src/test_utils/mocks/connectivity_manager.rs
  integration_tests/features/support/steps.js
  integration_tests/helpers/types.js
  integration_tests/helpers/util.js
  integration_tests/helpers/walletClient.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3130 feat: add persistent dedup cache for message hashes
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  comms/dht/migrations/2021-07-23-162902_add_dedup_cache/down.sql
  comms/dht/migrations/2021-07-23-162902_add_dedup_cache/up.sql
  comms/dht/src/actor.rs
  comms/dht/src/builder.rs
  comms/dht/src/config.rs
  comms/dht/src/dedup/dedup_cache.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/schema.rs
  comms/dht/src/storage/error.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/test_utils/dht_actor_mock.rs
Labels: mq-approved

#3142 fix: Update LibWallet recovery task event handling
  base_layer/wallet/tests/wallet/mod.rs
  base_layer/wallet_ffi/src/tasks.rs
Labels: mq-approved

#3139 fix: update LibWallet `wallet_import_utxo` method to include valid TariScript
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3147 fix: Fix cucumber transaction builder reliability
  integration_tests/helpers/transactionBuilder.js
Labels: mq-approved

#3145 fix: fix GRPC GetTransactionInfo not found response
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
Labels: mq-approved
