Repository tari-project/tari, pull requests merged in 2021-08, with the labels that each got.

#3003 Miningcore Transcoder
  Cargo.lock
  Cargo.toml
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/config.rs
  applications/tari_mining_node/src/main.rs
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_mining_node/src/stratum/error.rs
  applications/tari_mining_node/src/stratum/mod.rs
  applications/tari_mining_node/src/stratum/stratum_controller/controller.rs
  applications/tari_mining_node/src/stratum/stratum_controller/mod.rs
  applications/tari_mining_node/src/stratum/stratum_miner/control_message.rs
  applications/tari_mining_node/src/stratum/stratum_miner/job_shared_data.rs
  applications/tari_mining_node/src/stratum/stratum_miner/miner.rs
  applications/tari_mining_node/src/stratum/stratum_miner/mod.rs
  applications/tari_mining_node/src/stratum/stratum_miner/solution.rs
  applications/tari_mining_node/src/stratum/stratum_miner/solver_instance.rs
  applications/tari_mining_node/src/stratum/stratum_types/client_message.rs
  applications/tari_mining_node/src/stratum/stratum_types/job.rs
  applications/tari_mining_node/src/stratum/stratum_types/job_params.rs
  applications/tari_mining_node/src/stratum/stratum_types/login_params.rs
  applications/tari_mining_node/src/stratum/stratum_types/login_response.rs
  applications/tari_mining_node/src/stratum/stratum_types/miner_message.rs
  applications/tari_mining_node/src/stratum/stratum_types/mod.rs
  applications/tari_mining_node/src/stratum/stratum_types/rpc_error.rs
  applications/tari_mining_node/src/stratum/stratum_types/rpc_request.rs
  applications/tari_mining_node/src/stratum/stratum_types/rpc_response.rs
  applications/tari_mining_node/src/stratum/stratum_types/submit_params.rs
  applications/tari_mining_node/src/stratum/stratum_types/worker_identifier.rs
  applications/tari_mining_node/src/stratum/stratum_types/worker_status.rs
  applications/tari_mining_node/src/stratum/stream.rs
  applications/tari_stratum_transcoder/Cargo.toml
  applications/tari_stratum_transcoder/src/common/json_rpc.rs
  applications/tari_stratum_transcoder/src/common/mining.rs
  applications/tari_stratum_transcoder/src/common/mod.rs
  applications/tari_stratum_transcoder/src/common/proxy.rs
  applications/tari_stratum_transcoder/src/error.rs
  applications/tari_stratum_transcoder/src/main.rs
  applications/tari_stratum_transcoder/src/proxy.rs
  base_layer/tari_stratum_ffi/Cargo.toml
  base_layer/tari_stratum_ffi/src/error.rs
  base_layer/tari_stratum_ffi/src/lib.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/bootstrap.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  common/src/lib.rs
  common/src/logging.rs
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/config.js
  integration_tests/helpers/mergeMiningProxyProcess.js
  integration_tests/helpers/miningNodeProcess.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved, requires-local-test

#3143 fix: add timeout to protocol notifications + log improvements
  comms/dht/src/store_forward/store.rs
  comms/src/bounded_executor.rs
  comms/src/connection_manager/manager.rs
  comms/src/pipeline/inbound.rs
  comms/src/protocol/messaging/consts.rs
  comms/src/protocol/messaging/extension.rs
  comms/src/protocol/messaging/mod.rs
  comms/src/protocol/rpc/server/router.rs
  integration_tests/features/WalletBaseNodeSwitch.feature
Labels: mq-approved

#3146 fix: introduce cache update cool down to console wallet
  applications/tari_console_wallet/src/ui/state/app_state.rs
Labels: mq-approved

#3153 test: improve Verify all coinbases in hybrid mining are accounted for cucumber test
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/mergeMiningProxyClient.js
  integration_tests/helpers/transactionBuilder.js
  integration_tests/package-lock.json
Labels: mq-approved

#3158 refactor: stratum transcoder config cleanup
  common/config/presets/tari_config_example.toml
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  integration_tests/helpers/config.js
Labels: mq-approved

#3155 docs: added links to mobile wallets' repos
  README.md
Labels: mq-approved, mq-failed

#3148 fix(wallet): block certain keys during popup
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
Labels: mq-approved, mq-failed

#3166 test: fix two cucumber tests to be less flaky
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
Labels: mq-approved

#3160 fix: fix utxo scan edge case when pc awakes from sleep
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
Labels: mq-failed

#3167 chore: update to cucumber test to use sydney seed monero url address
  integration_tests/helpers/mergeMiningProxyProcess.js
Labels: mq-approved

#3169 test: fix flaky cucumber tests involving transactions
  integration_tests/features/support/steps.js
Labels: mq-approved

#3162 fix: ban peer when Merkle roots mismatch
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/config.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: mq-approved

#3144 test: cucumber for all wallet commands
  integration_tests/features/WalletBaseNodeSwitch.feature
  integration_tests/features/WalletCli.feature
  integration_tests/features/WalletPasswordChange.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3152 feat: add a shared p2p rpc client session pool to reduce rpc setup time
  applications/utils/automatic_recovery_test.js
  applications/utils/washing_machine.js
  base_layer/core/src/mempool/sync_protocol/test.rs
  clients/wallet_grpc_client/index.js
  clients/wallet_grpc_client/package-lock.json
  clients/wallet_grpc_client/package.json
  comms/dht/src/actor.rs
  comms/rpc_macros/src/generator.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connectivity/test.rs
  comms/src/protocol/messaging/test.rs
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/client_pool.rs
  comms/src/protocol/rpc/mod.rs
  comms/src/protocol/rpc/server/mock.rs
  comms/src/protocol/rpc/test/client_pool.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/handshake.rs
  comms/src/protocol/rpc/test/mod.rs
  comms/src/protocol/rpc/test/smoke.rs
  comms/src/test_utils/mocks/mod.rs
  comms/src/test_utils/mocks/peer_connection.rs
  integration_tests/features/StressTest.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/baseNodeClient.js
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/mergeMiningProxyProcess.js
  integration_tests/helpers/util.js
  integration_tests/helpers/walletClient.js
  integration_tests/helpers/walletProcess.js
  integration_tests/log4rs/base_node.yml
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3149 fix(wallet): fix resize panic
  applications/tari_console_wallet/src/ui/widgets/list_state.rs
Labels: mq-approved

#3159 feat: wallet connectivity service
  Cargo.lock
  applications/tari_console_wallet/src/ui/components/base_node.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/utils/crossterm_events.rs
  base_layer/wallet/src/base_node_service/config.rs
  base_layer/wallet/src/base_node_service/error.rs
  base_layer/wallet/src/base_node_service/handle.rs
  base_layer/wallet/src/base_node_service/mock_base_node_service.rs
  base_layer/wallet/src/base_node_service/mod.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/base_node_service/service.rs
  base_layer/wallet/src/connectivity_service/error.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/initializer.rs
  base_layer/wallet/src/connectivity_service/mod.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  base_layer/wallet/src/connectivity_service/watch.rs
  base_layer/wallet/src/lib.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service/service.rs
  comms/src/connection_manager/error.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connectivity/manager.rs
  comms/src/connectivity/requester.rs
  comms/src/multiplexing/yamux.rs
  comms/src/protocol/rpc/server/mock.rs
  comms/src/test_utils/mocks/connectivity_manager.rs
  infrastructure/test_utils/Cargo.toml
  infrastructure/test_utils/src/futures/async_assert_eventually.rs
  infrastructure/test_utils/src/runtime.rs
Labels: mq-approved

#3156 test: improve cucumber reliability of Massive multiple reorg test
  integration_tests/features/Reorgs.feature
  integration_tests/features/support/steps.js
Labels: mq-approved

#3163 fix: improve prune mode to remove panics
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/pruned_output.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/tests/async_db.rs
  base_layer/core/tests/node_comms_interface.rs
  integration_tests/features/Sync.feature
Labels: mq-approved

#3183 test: mark cucumber test as flaky
  integration_tests/features/WalletMonitoring.feature
Labels: mq-approved

#3179 test: fix flaky unit test sending_transaction_and_confirmation
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service/service.rs
Labels: mq-approved

#3180 test: fix wallet CLI cucumber tests (child process exited with code 107)
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/utxo_scanner_service/mod.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  integration_tests/features/WalletCli.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/util.js
  integration_tests/helpers/walletClient.js
  integration_tests/package-lock.json
Labels: mq-approved, mq-failed

#3176 ci: use non-zero exit status when wallet recovery fails
  applications/tari_console_wallet/src/recovery.rs
  applications/utils/automatic_recovery_test.js
  applications/utils/automatic_sync_test.js
  base_layer/wallet/src/utxo_scanner_service/handle.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanning.rs
  base_layer/wallet_ffi/src/tasks.rs
Labels: mq-approved, mq-failed

#3150 fix: set robust limits for a busy blockchain
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/mempool/service/service.rs
  base_layer/wallet/src/base_node_service/config.rs
  base_layer/wallet/src/base_node_service/mod.rs
  base_layer/wallet/src/output_manager_service/config.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/transaction_service/config.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_coinbase_monitoring_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  comms/src/protocol/rpc/handshake.rs
  integration_tests/helpers/util.js
Labels: mq-approved, mq-failed

#3168 test: add wallet ffi testing
  base_layer/wallet_ffi/wallet.h
  integration_tests/.eslintrc.json
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletFFI.js
  integration_tests/helpers/walletFFIClient.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3182 Update log4rs for tari_stratum_transcoder
  applications/tari_stratum_transcoder/src/proxy.rs
  common/logging/log4rs_sample_transcoder.yml
  common/src/logging.rs
Labels: mq-approved

#3185 feat(mining_node): mining worker name for tari_mining_node
  applications/tari_mining_node/src/config.rs
  applications/tari_mining_node/src/main.rs
  applications/tari_mining_node/src/stratum/controller.rs
  common/config/presets/tari_config_example.toml
  common/src/configuration/global.rs
Labels: mq-approved

#3178 feat: add network selection to wallet_ffi
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#3181 refactor: cleanup stratum config terminal output in tari_mining_node
  applications/tari_mining_node/src/stratum/controller.rs
Labels: mq-approved

#3187 fix(mining_node): stratum miner speed fix
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_mining_node/src/stratum/stratum_miner/miner.rs
Labels: mq-approved

#3173 fix: enforce unique commitments in utxo set
  applications/test_faucet/src/main.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/lmdb_db/mod.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/helpers.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/block_validators.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/traits.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/core/tests/node_service.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
  base_layer/wallet/src/wallet.rs
  infrastructure/test_utils/src/enums.rs
Labels: mq-approved, mq-failed

#3177 fix: handle receiver cancelling an inbound transaction that is later received
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database.rs
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/output_manager_service/service.rs
  clients/wallet_grpc_client/index.js
  integration_tests/features/Propagation.feature
  integration_tests/features/Reorgs.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletClient.js
Labels: mq-failed

#3186 fix: ensure peers are added to peer list before recovery starts
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_console_wallet/src/recovery.rs
Labels: mq-approved

#3204 chore: fix dev after test merges
  base_layer/core/src/validation/test.rs
Labels: mq-approved

#3206 test: fix or remove ignored tests in pow_data.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
Labels: mq-approved, mq-failed

#3218 chore: better logging for lmdb_delete
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: mq-approved

#3215 fix(wallet_ffi)add null check for `transport_type` in `create_comms_config` FFI function
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3214 fix(wallet_ffi): fix division by zero during recovery
  base_layer/wallet_ffi/src/tasks.rs
Labels: mq-approved

#3213 fix(wallet): add NodeId to console wallet Who Am I tab
  applications/tari_console_wallet/src/ui/components/receive_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
Labels: mq-approved

#3212 test: Add integration test for ListHeaders
  .circleci/config.yml
  integration_tests/features/BaseNodeConnectivity.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/baseNodeClient.js
Labels: mq-approved

#3217 fix: bug in wallet base node peer switching
  applications/daily_tests/helpers.js
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/wallet/src/base_node_service/mock_base_node_service.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/base_node_service/service.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  comms/rpc_macros/src/generator.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/message.rs
  comms/src/protocol/rpc/server/mod.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/tests/rpc_stress.rs
Labels: mq-approved

#3219 test: cucumber check block heights in order test
  integration_tests/features/BaseNodeConnectivity.feature
  integration_tests/features/support/steps.js
  integration_tests/helpers/baseNodeClient.js
Labels: mq-approved

#3220 test: almost complete ffi wallet test
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/ffi/byteVector.js
  integration_tests/helpers/ffi/completedTransaction.js
  integration_tests/helpers/ffi/completedTransactions.js
  integration_tests/helpers/ffi/contact.js
  integration_tests/helpers/ffi/contacts.js
  integration_tests/helpers/ffi/pendingInboundTransaction.js
  integration_tests/helpers/ffi/pendingInboundTransactions.js
  integration_tests/helpers/ffi/pendingOutboundTransaction.js
  integration_tests/helpers/ffi/pendingOutboundTransactions.js
  integration_tests/helpers/ffi/publicKey.js
  integration_tests/helpers/ffi/seedWords.js
  integration_tests/helpers/ffi/walletFFI.js
  integration_tests/helpers/walletFFIClient.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3222 cucumber: Add mempool test for unconfirmed tx to mined tx
  integration_tests/features/Mempool.feature
Labels: mq-approved

#3223 fix: chain error caused by zero-conf transactions and reorgs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  integration_tests/features/Reorgs.feature
Labels: mq-approved

#3221 ci: prebuild mining node on cucumber tests
  .circleci/config.yml
Labels: mq-approved

#3216 Add extra logging detail for wiremode warnings
  comms/src/connection_manager/listener.rs
  comms/src/connection_manager/wire_mode.rs
Labels: mq-approved

#3226 fix: edge-case fixes for wallet peer switching in console wallet
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/initializer.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  base_layer/wallet/src/connectivity_service/watch.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  comms/src/protocol/rpc/server/mod.rs
Labels: mq-approved

#3227 feat: add `ping()` to all comms RPC clients
  base_layer/wallet/src/base_node_service/monitor.rs
  comms/rpc_macros/src/generator.rs
  comms/src/noise/socket.rs
  comms/src/protocol/rpc/client.rs
  comms/src/protocol/rpc/error.rs
  comms/src/protocol/rpc/test/greeting_service.rs
  comms/src/protocol/rpc/test/smoke.rs
Labels: mq-approved

#3225 fix: show warnings on console
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/sync/rpc/mod.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/logging/log4rs_sample_base_node.yml
  common/logging/log4rs_sample_mining_node.yml
  common/logging/log4rs_sample_seed_node.yml
  common/logging/log4rs_sample_transcoder.yml
  common/logging/log4rs_sample_wallet.yml
  common/src/logging.rs
Labels: mq-approved

#3224 test: improve comms limits to combat network timeouts
  base_layer/wallet/tests/output_manager_service/service.rs
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/listener.rs
  comms/src/connection_manager/manager.rs
  comms/src/protocol/rpc/client.rs
  integration_tests/features/Sync.feature
  integration_tests/package-lock.json
Labels: mq-approved

#3234 chore: add extra seed node
  common/config/presets/tari_config_example.toml
Labels: mq-approved

#3232 test: Add rebuild-db integration test
  .circleci/config.yml
  integration_tests/features/Recovery.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/baseNodeProcess.js
Labels: mq-approved

#3235 fix: exit command and free up tokio thread
  Cargo.lock
  applications/tari_base_node/src/main.rs
Labels: mq-approved

#3244 fix: add status output to logs in non-interactive mode
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/src/parser.rs
Labels: mq-approved

#2864 refactor: additional DB audit of methods
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: mq-approved

#3211 feat: allow DHT to be configured to repropagate messages for a number of rounds
  base_layer/core/src/mempool/service/inbound_handlers.rs
  comms/dht/src/actor.rs
  comms/dht/src/builder.rs
  comms/dht/src/config.rs
  comms/dht/src/dedup/dedup_cache.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/dht.rs
  comms/dht/src/domain_message.rs
  comms/dht/src/envelope.rs
  comms/dht/src/filter/future.rs
  comms/dht/src/filter/layer.rs
  comms/dht/src/filter/mod.rs
  comms/dht/src/filter/predicate.rs
  comms/dht/src/inbound/dht_handler/task.rs
  comms/dht/src/inbound/message.rs
  comms/dht/src/lib.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/error.rs
  comms/dht/src/outbound/message_params.rs
  comms/dht/src/storage/error.rs
  comms/dht/src/store_forward/forward.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/store_forward/store.rs
  comms/dht/src/test_utils/dht_actor_mock.rs
  comms/dht/src/tower_filter/predicate.rs
  comms/dht/tests/dht.rs
Labels: mq-approved

#3259 refactor: refactor wallet ffi cucumber tests
  .circleci/config.yml
  applications/ffi_client/index.js
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/ffi/byteVector.js
  integration_tests/helpers/ffi/commsConfig.js
  integration_tests/helpers/ffi/completedTransaction.js
  integration_tests/helpers/ffi/completedTransactions.js
  integration_tests/helpers/ffi/contact.js
  integration_tests/helpers/ffi/contacts.js
  integration_tests/helpers/ffi/emojiSet.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/pendingInboundTransaction.js
  integration_tests/helpers/ffi/pendingInboundTransactions.js
  integration_tests/helpers/ffi/pendingOutboundTransaction.js
  integration_tests/helpers/ffi/pendingOutboundTransactions.js
  integration_tests/helpers/ffi/privateKey.js
  integration_tests/helpers/ffi/publicKey.js
  integration_tests/helpers/ffi/seedWords.js
  integration_tests/helpers/ffi/transportType.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/walletFFIClient.js
Labels: mq-approved, mq-priority

#3239 fix: send transactions to all connected peers
  base_layer/core/src/mempool/service/service.rs
Labels: mq-approved

#3253 test: add random transactions to empty cucumber blocks
  Cargo.lock
  integration_tests/features/Mempool.feature
  integration_tests/features/Reorgs.feature
  integration_tests/features/StressTest.feature
  integration_tests/features/support/steps.js
  integration_tests/features/support/world.js
Labels: mq-approved

#3255 feat: improve basenode switch from listening to lagging mode
  base_layer/core/src/base_node/chain_metadata_service/service.rs
Labels: mq-approved

#3257 fix: small display bug
  applications/tari_base_node/src/recovery.rs
Labels: mq-approved

#3256 feat: add Igor testnet
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/consensus/network.rs
  common/config/presets/tari_igor_config.toml
  common/src/configuration/network.rs
  common/src/configuration/utils.rs
Labels: mq-approved

#3264 fix: off-by-one causing "no further headers to download" bug
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
Labels: mq-approved, mq-priority

#3262 fix: revert mining_node default logging config
  common/logging/log4rs_sample_mining_node.yml
Labels: mq-approved

#3247 feat: allow network to be selected at application start
  applications/tari_app_utilities/src/initialization.rs
  common/src/configuration/bootstrap.rs
Labels: mq-approved

#3265 feat: add ability to bypass rangeproof
  Cargo.toml
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/recovery.rs
  base_layer/core/src/base_node/state_machine_service/initializer.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/sync/validators.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/validation/block_validators.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  common/src/configuration/global.rs
Labels: mq-approved

#3269 test: add trace tag to liveness data
  base_layer/p2p/src/services/liveness/service.rs
Labels: mq-approved

#3270 fix: auto update continuously checks auto_update_check_interval is disabled
  base_layer/p2p/src/auto_update/dns.rs
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/p2p/src/auto_update/service.rs
Labels: mq-approved

#3271 fix: remove cucumber walletffi.js file that got re-included in rebase
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/ffi/walletFFI.js
Labels: mq-approved

#3272 test: early subscription to connectivity events for mempool sync
  base_layer/core/src/mempool/sync_protocol/initializer.rs
Labels: mq-approved
