Repository tari-project/tari, pull requests merged in 2022-09, with the labels that each got.

#4578 fix(outbound): reduce messaging protocol error to debug
  comms/core/src/protocol/messaging/error.rs
Labels: mq-failed

#4689 feat: improve txo validation logic
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  clients/ffi_client/index.js
  clients/ffi_client/recovery.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: CR-insufficient_context, S-Controversial

#4694 feat: improve the TMS validation process
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: S-Controversial

#4713 fix: ffi tests
  integration_tests/helpers/ffi/ffiInterface.js
Labels: CR-insufficient_context

#4706 fix: sync handling and increase reorg speed in mempool
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/hooks.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  integration_tests/features/Mempool.feature
Labels: CR-insufficient_context

#4740 ci: deny dbg macro
  lints.toml
Labels: CR-insufficient_context

#4714 fix(core): use compact inputs for block propagation
  applications/tari_app_grpc/src/conversions/transaction_input.rs
  applications/tari_base_node/src/commands/command/check_db.rs
  applications/tari_base_node/src/commands/command/get_block.rs
  applications/tari_base_node/src/commands/command/period_stats.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_base_node/src/recovery.rs
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/base_node/comms_interface/outbound_interface.rs
  base_layer/core/src/base_node/proto/request.proto
  base_layer/core/src/base_node/proto/request.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/tests/async_db.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/core/tests/node_service.rs
Labels: S-Controversial

#4745 chore: disallow onion v2
  comms/core/src/connection_manager/common.rs
  comms/core/src/connection_manager/error.rs
Labels: CR-insufficient_context

#4743 fix(clients): fix tari nodejs client proto paths
  .circleci/config.yml
  .github/workflows/integration_tests.yml
  clients/nodejs/base_node_grpc_client/src/index.js
  clients/nodejs/wallet_grpc_client/index.js
  clients/nodejs/wallet_grpc_client/package.json
  integration_tests/package-lock.json
Labels: CR-too_long

#4744 fix: fix get_shard_key
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  clients/nodejs/base_node_grpc_client/src/index.js
  clients/nodejs/wallet_grpc_client/index.js
Labels: CR-insufficient_context
