Repository tari-project/tari, pull requests merged in 2022-05, with the labels that each got.

#4065 refactor(comms): reduce length of long functions (clippy)
  comms/core/src/connectivity/manager.rs
  comms/core/src/noise/socket.rs
Labels: mq-approved

#4067 test(cucumber): use separate FFI target dir
  integration_tests/helpers/ffi/ffiInterface.js
Labels: mq-approved

#4064 fix(key-manager): remove floating point math from mnemonic code
  base_layer/key_manager/src/mnemonic.rs
Labels: mq-approved

#4070 feat(p2p): adds tor.forward_address setting
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/transport.rs
  common/config/presets/base_node.toml
Labels: mq-approved, mq-priority

#4071 ci: fix coverage
  .github/workflows/coverage.yml
Labels: mq-approved

#3908 feat(collectibles): add list assets command
  applications/tari_collectibles/src-tauri/src/cli.rs
  applications/tari_collectibles/src-tauri/src/config.rs
  applications/tari_collectibles/src-tauri/src/main.rs
  applications/tari_console_wallet/src/main.rs
  common/src/exit_codes.rs
Labels: mq-approved

#4072 fix: support safe non-interactive mode
  applications/tari_console_wallet/src/init/mod.rs
Labels: mq-approved, mq-priority

#4073 feat: allow network to be set by TARI_NETWORK env var
  applications/tari_app_utilities/Cargo.toml
  applications/tari_app_utilities/src/common_cli_args.rs
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/cli.rs
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_collectibles/src-tauri/src/cli.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/cli.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/cli.rs
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/cli.rs
Labels: mq-approved

#4017 chore: update launchpad backend
  .circleci/config.yml
  .github/workflows/ci.yml
  .github/workflows/rfc_test.yml
  applications/launchpad/backend/assets/config.toml
  applications/launchpad/backend/src/docker/settings.rs
  applications/launchpad/backend/src/docker/workspace.rs
  applications/launchpad/backend/tauri.conf.json
  applications/launchpad/build_images.sh
  applications/launchpad/docker_rig/base_node.Dockerfile
  applications/launchpad/docker_rig/console_wallet.Dockerfile
  applications/launchpad/docker_rig/mm_proxy.Dockerfile
  applications/launchpad/docker_rig/monerod.Dockerfile
  applications/launchpad/docker_rig/sha3_miner.Dockerfile
  applications/launchpad/gui-vue/src/store.js
  applications/launchpad/versions.txt
  common/config/presets/base_node.toml
Labels: mq-approved, mq-failed

#4020 test: unignore working tests
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#3864 docs: rfc side chains
  .github/workflows/rfc_deploy.yml
  .github/workflows/rfc_test.yml
  README.md
  RFC/book.toml
  RFC/mermaid-init.js
  RFC/mermaid.min.js
  RFC/src/BaseLayerExtensions.md
  RFC/src/RFC-0001_overview.md
  RFC/src/RFC-0100_BaseLayer.md
  RFC/src/RFC-0110_BaseNodes.md
  RFC/src/RFC-0111_BaseNodeArchitecture.md
  RFC/src/RFC-0120_Consensus.md
  RFC/src/RFC-0130_Mining.md
  RFC/src/RFC-0131_Mining.md
  RFC/src/RFC-0152_EmojiId.md
  RFC/src/RFC-0170_NetworkCommunicationProtocol.md
  RFC/src/RFC-0171_MessageSerialisation.md
  RFC/src/RFC-0172_PeerToPeerMessagingProtocol.md
  RFC/src/RFC-0190_Mempool.md
  RFC/src/RFC-0201_TariScript.md
  RFC/src/RFC-0250_Covenants.md
  RFC/src/RFC-0301_NamespaceRegistration.md
  RFC/src/RFC-0311_AssetTemplates.md
  RFC/src/RFC-0312_DANHighLevelSpecification.md
  RFC/src/RFC-0322_VNRegistration.md
  RFC/src/RFC-0340_VNConsensusOverview.md
  RFC/src/RFC-0345_AssetLifeCycle.md
  RFC/src/RFC-0360_NFTInvoices.md
  RFC/src/RFC-0500_PaymentChannels.md
  RFC/src/RFC-8001_MultiPartyTransactions.md
  RFC/src/RFC-8002_TransactionProtocol.md
  RFC/src/RFC-8003_TariUseCases.md
  RFC/src/RFCD-0010_CodeStructure.md
  RFC/src/RFCD-0130_Mining.md
  RFC/src/RFCD-0300_DAN.md
  RFC/src/RFCD-0302_ValidatorNodes.md
  RFC/src/RFCD-0304_VNCommittees.md
  RFC/src/RFCD-0341_AssetRegistration.md
  RFC/src/RFCD-0345_AssetLifeCycle.md
  RFC/src/RFCD-0500_PaymentChannels.md
  RFC/src/SUMMARY.md
  RFC/src/assets/Infrastructure overview.drawio
  RFC/src/theme/images/chains.png
Labels: mq-approved

#3999 test: write test for input, output and kernel malleability
  base_layer/core/src/covenants/mod.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/helpers/block_malleability.rs
  base_layer/core/tests/helpers/mod.rs
Labels: mq-approved

#4081 fix(base-node): assign correct base dir to tor identity
  applications/tari_base_node/src/config.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/error.rs
Labels: mq-approved

#4083 fix(wallet): ensure block hash exists
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
Labels: mq-approved

#4085 fix: prevent seed peer address from being overwritten unless newer
  applications/tari_base_node/src/commands/command/get_peer.rs
  applications/tari_base_node/src/commands/command/list_peers.rs
  base_layer/p2p/src/initialization.rs
  comms/core/Cargo.toml
  comms/core/src/peer_manager/peer.rs
  comms/dht/src/peer_validator.rs
  integration_tests/features/Sync.feature
  integration_tests/features/support/steps.js
Labels: mq-approved

#4092 fix(wallet header): remove function argument
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#4090 fix: possible overflow in difficulty calculation (fixes #3923)
  base_layer/core/src/proof_of_work/difficulty.rs
Labels: mq-approved

#4101 fix: single allocation for block header consensus encoding
  base_layer/core/src/blocks/block_header.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: mq-approved

#4095 chore: remove unused add_recovery_byte_to_serialized_data_if_needed function
  base_layer/core/src/transactions/transaction_components/output_features.rs
Labels: mq-approved

#4089 fix(wallet): add default value for wait stage
  applications/tari_console_wallet/src/automation/commands.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/lib.rs
Labels: mq-approved

#4087 fix(core): set reorg metrics on header sync rewind
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
Labels: mq-approved

#4105 feat: add mempool fee per gram stats to transaction service
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/proto/rpc.rs
  base_layer/core/src/base_node/rpc/mod.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/service/handle.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/service/request.rs
  base_layer/core/src/mempool/service/response.rs
  base_layer/core/src/mempool/test_utils/mock.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/tari_amount.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#4096 fix(wallet): use network specified by cli/envvar in console wallet
  applications/tari_console_wallet/src/main.rs
Labels: mq-approved

#4104 feat(dht): add feature to optionally bundle sqlite
  Cargo.lock
  base_layer/wallet/Cargo.toml
  comms/dht/Cargo.toml
Labels: mq-approved

#4106 fix(ci): sort .license.ignore locally before diff
  scripts/file_license_check.sh
Labels: mq-approved

#4107 ci: feature selfhosted runners
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: mq-approved

#4109 feat(wallet_ffi): new ffi method to create output features
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#4115 feat(wallet_ffi): new ffi method to create covenant
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#4114 feat: add FeePerGramStats to ffi library
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/ffi_steps.js
  integration_tests/helpers/ffi/feePerGramStat.js
  integration_tests/helpers/ffi/feePerGramStats.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/walletFFIClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#4113 refactor(core): change ConsensusEncoding trait not to return written bytes
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/bytes.rs
  base_layer/core/src/consensus/consensus_encoding/crypto.rs
  base_layer/core/src/consensus/consensus_encoding/epoch_time.rs
  base_layer/core/src/consensus/consensus_encoding/generic.rs
  base_layer/core/src/consensus/consensus_encoding/integers.rs
  base_layer/core/src/consensus/consensus_encoding/micro_tari.rs
  base_layer/core/src/consensus/consensus_encoding/script.rs
  base_layer/core/src/covenants/arguments.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/covenants/encoder.rs
  base_layer/core/src/covenants/filters/filter.rs
  base_layer/core/src/covenants/token.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/asset_output_features.rs
  base_layer/core/src/transactions/transaction_components/committee_definition_features.rs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/mint_non_fungible_features.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/output_features_version.rs
  base_layer/core/src/transactions/transaction_components/output_flags.rs
  base_layer/core/src/transactions/transaction_components/side_chain_checkpoint_features.rs
  base_layer/core/src/transactions/transaction_components/template_parameter.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_input_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/transaction_output_version.rs
Labels: mq-approved

#4118 feat(wallet_ffi): new ffi method to create output features (fixed flag size for dibbler)
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved, mq-failed

#4119 fix: tx importing status to correctly reflect the origin
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#4126 feat: loosen ffi import utxo requirements
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#4124 fix: hash in cucumber
  integration_tests/helpers/util.js
Labels: mq-approved

#3907 fix(dht)!: fixes MAC related key vuln for propagated cleartext msgs
  Cargo.lock
  comms/core/Cargo.toml
  comms/core/src/peer_manager/node_id.rs
  comms/core/src/utils/mod.rs
  comms/core/src/utils/signature.rs
  comms/dht/Cargo.toml
  comms/dht/src/crypt.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/lib.rs
  comms/dht/src/origin_mac.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/serialize.rs
  comms/dht/src/proto/envelope.proto
  comms/dht/src/store_forward/error.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/test_utils/makers.rs
  comms/dht/src/version.rs
Labels: Network Breaking, mq-approved

#3928 fix(comms)!: commit to public key and nonce in identity sig
  comms/core/src/peer_manager/identity_signature.rs
Labels: Network Breaking, mq-approved

#4121 feat(core): adds constitution UTXO features
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/vec.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/committee_members.rs
  base_layer/core/src/transactions/transaction_components/side_chain/contract_constitution.rs
  base_layer/core/src/transactions/transaction_components/side_chain/mod.rs
Labels: mq-approved

#4100 fix: better message for failed software update check
  base_layer/p2p/src/auto_update/service.rs
Labels: mq-approved

#4091 refactor(core): upgrade randomx-rs to 1.1.11
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: mq-approved

#4086 feat(daily-tests): use environment variable to set custom seed words
  applications/daily_tests/cron_jobs.js
Labels: mq-approved

#4082 chore(wallet): rename connection_manager_pool_size to db_connection_pool_size
  applications/tari_console_wallet/src/init/mod.rs
  base_layer/wallet/src/config.rs
Labels: mq-approved

#4117 chore: remove unused identity files
  config/tor_id.json
  validator_node_tor_id.json
Labels: mq-approved

#4131 fix(dht): optimisation, no decrypt if public key dest doesn't match
  comms/dht/src/inbound/decryption.rs
Labels: mq-approved

#4120 feat(core): impl consensus encoding for bool
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/bool.rs
Labels: mq-approved

#4132 fix(integration_test): fix wallet-cli integration tests
  integration_tests/features/WalletCli.feature
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#4134 feat(core)!: add side-chain features and constitution to UTXOs
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/mod.rs
  applications/tari_app_grpc/src/conversions/output_features.rs
  applications/tari_app_grpc/src/conversions/sidechain_features.rs
  base_layer/common_types/src/types/fixed_hash.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_encoding/vec.rs
  base_layer/core/src/covenants/arguments.rs
  base_layer/core/src/covenants/byte_codes.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/covenants/decoder.rs
  base_layer/core/src/covenants/encoder.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/filters/and.rs
  base_layer/core/src/covenants/filters/field_eq.rs
  base_layer/core/src/covenants/filters/fields_hashed_eq.rs
  base_layer/core/src/covenants/filters/fields_preserved.rs
  base_layer/core/src/covenants/filters/not.rs
  base_layer/core/src/covenants/filters/or.rs
  base_layer/core/src/covenants/filters/output_hash_eq.rs
  base_layer/core/src/covenants/filters/xor.rs
  base_layer/core/src/covenants/macros.rs
  base_layer/core/src/covenants/token.rs
  base_layer/core/src/proto/transaction.proto
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/committee_members.rs
  base_layer/core/src/transactions/transaction_components/side_chain/contract_constitution.rs
  base_layer/core/src/transactions/transaction_components/side_chain/mod.rs
  base_layer/core/src/transactions/transaction_components/side_chain/sidechain_features.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/block_validators/test.rs
  base_layer/core/tests/mempool.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/base_node.toml
  integration_tests/helpers/transactionBuilder.js
  integration_tests/helpers/util.js
Labels: mq-approved

#4130 test: coverage mocks for files common configuration files (PR #4116)
  common/src/configuration/bootstrap.rs
  common/src/configuration/common_config.rs
  common/src/configuration/error.rs
  common/src/configuration/loader.rs
  common/src/configuration/mod.rs
  common/src/configuration/name_server.rs
  common/src/configuration/network.rs
  common/src/configuration/string_list.rs
Labels: mq-approved, mq-failed

#4116 test: coverage for rolling average time struct
  base_layer/core/src/common/byte_counter.rs
  base_layer/core/src/common/limited_reader.rs
  base_layer/core/src/common/rolling_avg.rs
Labels: mq-approved, mq-failed

#4133 feat(wallet): new command to publish a contract definition transaction
  Cargo.lock
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/sidechain_features.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/proto/transaction.proto
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/output_features_version.rs
  base_layer/core/src/transactions/transaction_components/side_chain/contract_definition.rs
  base_layer/core/src/transactions/transaction_components/side_chain/mod.rs
  base_layer/core/src/transactions/transaction_components/side_chain/sidechain_features.rs
  base_layer/wallet/src/assets/asset_manager.rs
  base_layer/wallet/src/assets/asset_manager_handle.rs
  base_layer/wallet/src/assets/contract_definition_file_format.rs
  base_layer/wallet/src/assets/infrastructure/asset_manager_service.rs
  base_layer/wallet/src/assets/infrastructure/mod.rs
  base_layer/wallet/src/assets/mod.rs
  integration_tests/features/WalletCli.feature
  integration_tests/features/support/wallet_cli_steps.js
  integration_tests/fixtures/contract_definition.json
Labels: mq-approved

#4144 feat: scan base node for constitutions
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_app_grpc/proto/validator_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/grpc/validator_node_grpc_server.rs
  applications/tari_validator_node/src/main.rs
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  dan_layer/core/src/services/base_node_client.rs
  dan_layer/core/src/services/mocks/mod.rs
Labels: mq-approved, mq-failed

#4135 ci: docker image build for x86-64 & arm64 from x86-64
  applications/launchpad/tarilabs.Dockerfile
Labels: mq-approved

#4142 feat: add encrypted value in the transaction output
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/unblinded_output.rs
  applications/test_faucet/src/main.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/encrypted_value.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/wallet/migrations/2022-05-25-154612_add_encrypted_value/down.sql
  base_layer/wallet/migrations/2022-05-25-154612_add_encrypted_value/up.sql
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  common/src/configuration/network.rs
Labels: mq-approved, mq-failed
