Repository tari-project/tari, pull requests merged in 2022-10, with the labels that each got.

#4753 fix(dht/encryption): greatly reduce heap allocations for encrypted messaging
  Cargo.lock
  comms/core/src/lib.rs
  comms/core/src/message/mod.rs
  comms/core/src/protocol/rpc/body.rs
  comms/dht/Cargo.toml
  comms/dht/src/crypt.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/dht.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/inbound/deserialize.rs
  comms/dht/src/inbound/dht_handler/task.rs
  comms/dht/src/inbound/forward.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/message.rs
  comms/dht/src/outbound/mock.rs
  comms/dht/src/outbound/requester.rs
  comms/dht/src/outbound/serialize.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/store_forward/store.rs
  comms/dht/src/test_utils/makers.rs
  comms/dht/src/test_utils/mod.rs
  comms/dht/tests/dht.rs
Labels: S-Controversial

#4771 Revert "ci: run coverage on prs"
  .github/workflows/coverage.yml
Labels: mq-failed

#4752 fix: batch rewind operations
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: clippy failed, CR-insufficient_context

#4778 feat: move nonce to first in sha hash
  applications/tari_miner/src/difficulty.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/sha3_pow.rs
  base_layer/core/tests/block_validation.rs
Labels: S-Controversial, S-Requires-Hard-Fork

#4805 fix(core): periodically commit large transaction in prune_to_height
  Cargo.lock
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: P-merge

#4817 fix(comms/rpc): measures client-side latency to first message received
  comms/core/src/protocol/rpc/client/mod.rs
Labels: P-merge

#4800 fix(core): increase sync timeouts
  base_layer/core/src/base_node/sync/config.rs
Labels: P-merge

#4742 feat: add multisig script that returns aggregate of signed public keys
  infrastructure/tari_script/src/op_codes.rs
  infrastructure/tari_script/src/script.rs
Labels: S-Controversial, S-Needs-RFC, P-acks_required

#4818 refactor: split tari_base_node and tari_console_wallet into a lib component
  applications/tari_app_utilities/src/common_cli_args.rs
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/cli.rs
  applications/tari_base_node/src/lib.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/src/recovery.rs
  applications/tari_console_wallet/src/cli.rs
  applications/tari_console_wallet/src/config.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/lib.rs
  applications/tari_console_wallet/src/main.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/utils/crossterm_events.rs
  applications/tari_console_wallet/src/wallet_modes.rs
Labels: P-acks_required

#4825 chore: remove autoupdate script
  buildtools/dns/.env.sample
  buildtools/dns/.nvmrc
  buildtools/dns/README.md
  buildtools/dns/package-lock.json
  buildtools/dns/package.json
  buildtools/dns/update.js
Labels: CR-insufficient_context, P-acks_required

#4826 chore: update log4rs
  Cargo.lock
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  infrastructure/libtor/Cargo.toml
Labels: P-acks_required

#4824 chore: update crossterm
  Cargo.lock
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/ui/mod.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_miner/Cargo.toml
  applications/tari_miner/src/main.rs
Labels: P-acks_required

#4835 docs: add a docstring to the check_sig method
  infrastructure/tari_script/src/script.rs
Labels: P-merge

#4832 fix(dht): fix over allocation for encrypted messages
  comms/dht/src/crypt.rs
Labels: P-merge

#4834 feat: make build_script_challenge public
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
Labels: P-merge

#4837 docs: improve m-of-n opcode docs
  infrastructure/tari_script/src/op_codes.rs
Labels: P-merge

#4814 fix: remove unnecessary validator config settings
  common/config/presets/e_validator_node.toml
Labels: P-merge

#4841 fix: list-connections
  applications/tari_base_node/src/commands/command/list_connections.rs
Labels: P-merge

#4840 feat: add more detailed error mapping for the ffi
  base_layer/wallet_ffi/src/error.rs
Labels: P-merge

#4827 feat: better FFI feedback from transaction validation
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-merge

#4843 fix(dht): zeroize AEAD keys on drop
  comms/dht/src/crypt.rs
Labels: P-acks_required

#4845 feat: add missing fields to grpc consensus constants interface
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/transactions/weight.rs
Labels: CR-too_long, P-merge

#4838 fix(base-node): use Network::from_str to parse network in cli
  applications/tari_base_node/src/cli.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/cli.rs
  applications/tari_merge_mining_proxy/src/cli.rs
Labels: P-acks_required

#4848 fix: remove clear_on_drop dependency
  Cargo.lock
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/wallet/Cargo.toml
  comms/core/Cargo.toml
  comms/core/src/tor/control_client/types.rs
Labels: P-acks_required

#4849 fix: remove unused config for validator node
  common/config/presets/e_validator_node.toml
Labels: P-acks_required

#4836 feat: add opcode versions
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/validation/block_validators/orphan.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/helpers/block_malleability.rs
  infrastructure/tari_script/src/lib.rs
  infrastructure/tari_script/src/op_codes.rs
Labels: P-acks_required

#4851 feat: add static lifetime to emission amounts calculation
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-acks_required

#4856 feat: add block height to input request to get network consensus constants
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_app_grpc/proto/types.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
Labels: CR-insufficient_context, CR-too_long, P-reviews_required, P-acks_required

#4852 fix(core): adds txo version checks to async validator
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/transaction_validators.rs
Labels: P-acks_required

#4857 fix(ci): update GHA set-output plus dependabot schedule for GHA
  .github/dependabot.yml
  .github/workflows/auto_labels.yml
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/build_libwallets.yml
  .github/workflows/ci.yml
  .github/workflows/pr_title.yml
Labels: P-acks_required

#4863 chore: fix potentially buggy split of string into lines
  applications/tari_console_wallet/src/ui/components/log_tab.rs
  comms/core/src/tor/control_client/parsers.rs
Labels: P-merge

#4864 chore: replace manual implementation of char methods
  base_layer/core/src/consensus/emission.rs
Labels: P-merge
