Repository tari-project/tari, pull requests merged in 2022-08, with the labels that each got.

#4364 feat!: add burned outputs
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/transaction_kernel.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/test_faucet/src/main.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/proto/transaction.proto
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/kernel_builder.rs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/output_type.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/validation/block_validators/orphan.rs
  base_layer/core/src/validation/chain_balance.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/src/validation/traits.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  clients/wallet_grpc_client/index.js
  integration_tests/README.md
  integration_tests/features/Sync.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/wallet_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#4374 fix: burned output check
  base_layer/core/src/validation/helpers.rs
Labels: mq-approved

#4296 fix: low entropy mac passphrase in cipher seed (see issue #4182)
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-failed

#4369 fix: wallet's `remove_encryption()` was removing cipher before decryption (see issue #4304)
  applications/tari_console_wallet/src/grpc/mod.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/notifier/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/wallet.rs
Labels: mq-approved

#4370 fix: wallet seed_words command is broken (see issue #4363)
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/wallet/src/wallet.rs
Labels: mq-approved

#4275 fix: add more recent zero point for wallet birthday (see issue #4176)
  base_layer/key_manager/src/cipher_seed.rs
Labels: mq-approved, mq-failed

#4367 feat: remove hashing domain and update key manager
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/test_faucet/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/types/default_hash_domain.rs
  base_layer/common_types/src/types/mac_hash_domain.rs
  base_layer/common_types/src/types/mod.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/mod.rs
  base_layer/core/src/consensus/mod.rs
  base_layer/core/src/covenants/mod.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/transactions/mod.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/error.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
  base_layer/mmr/Cargo.toml
  base_layer/mmr/src/lib.rs
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/lib.rs
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  common/Cargo.toml
  common/src/hashing.rs
  common/src/hashing_domain.rs
  common/src/lib.rs
  comms/core/Cargo.toml
  comms/core/src/lib.rs
  comms/dht/Cargo.toml
  comms/dht/src/lib.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/core/Cargo.toml
  dan_layer/core/src/lib.rs
  dan_layer/engine/Cargo.toml
  dan_layer/engine/src/crypto.rs
  dan_layer/engine/src/lib.rs
  dan_layer/storage_sqlite/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/tari_script/src/lib.rs
Labels: mq-approved, mq-failed

#4316 fix!: improve wallet key derivation by use of proper domain separation (see issue #4170)
  Cargo.lock
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
Labels: mq-approved, mq-failed

#4362 fix(dht)!: add message padding for message decryption, to reduce message length leaks (fixes #4140)
  comms/dht/src/crypt.rs
Labels: mq-approved

#4340 fix: wallet database encryption does not bind to field keys #4137
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/types.rs
  base_layer/wallet/src/util/encryption.rs
Labels: mq-approved

#4385 test(comms/core): fix broken DNS resolution test
  comms/core/src/utils/multiaddr.rs
Labels: mq-approved

#4381 feat(base_layer/core): add domain hashing wrapper for consensus encoding
  base_layer/core/src/base_node/sync/rpc/tests.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/hashing.rs
  base_layer/core/src/consensus/mod.rs
  base_layer/core/src/transactions/mod.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/side_chain/checkpoint_challenge.rs
  base_layer/core/src/transactions/transaction_components/side_chain/contract_definition.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/dan_validators/checkpoint_validator.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/domainHasher.js
  integration_tests/helpers/transactionBuilder.js
  integration_tests/helpers/util.js
Labels: mq-approved

#4387 fix: force peer identity signature
  comms/core/src/connection_manager/common.rs
  comms/core/src/connection_manager/error.rs
Labels: mq-approved

#4382 feat: bump tari_crypto version -> v0.15.4
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/test_faucet/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  infrastructure/tari_script/Cargo.toml
Labels: mq-approved

#4359 fix(wallet): implement `check_for_updates` in wallet grpc
  applications/tari_base_node/src/commands/cli_loop.rs
  applications/tari_base_node/src/commands/command/version.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/p2p/src/auto_update/service.rs
  meta/hashes.txt
  meta/hashes.txt.sig
Labels: mq-approved

#4377 feat!: fix kernel mutability
  applications/test_faucet/src/main.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/kernel_builder.rs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/transactions/transaction_protocol/proto/recipient_signed_message.proto
  base_layer/core/src/transactions/transaction_protocol/proto/recipient_signed_message.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_metadata.proto
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_metadata.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/mempool.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/helpers/domainHasher.js
  integration_tests/helpers/transactionBuilder.js
Labels: mq-approved, mq-failed

#4163 docs: new contribution guidelines
  .github/workflows/pr_title.yml
  Contributing.md
  RFC/src/theme/images/status-active.svg
  RFC/src/theme/images/status-wip.svg
  meta/img/status-deprecated.svg
  meta/img/status-draft.svg
  meta/img/status-outofdate.svg
  meta/img/status-raw.svg
  meta/img/status-retired.svg
  meta/img/status-stable.svg
Labels: documentation, mq-approved

#4398 fix: default to esme
  applications/tari_base_node/src/config.rs
  common/config/presets/c_base_node.toml
Labels: mq-approved

#4406 test: add a utility script for running many coinsplits
  scripts/generate-coinsplits.ps1
Labels: mq-approved

#4302 fix: use HashError for value encryption parts
  base_layer/core/src/transactions/transaction_components/encrypted_value.rs
Labels: mq-approved

#4384 chore: remove wallet key manager state migration
  base_layer/wallet/migrations/2022-02-28-141501_key_manager_unique_index/up.sql
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/key_manager_state_old.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/mod.rs
Labels: mq-approved

#4401 feat: accept 'esme' as network name on cli
  common/src/configuration/network.rs
Labels: mq-approved

#4397 fix: recover all known scripts
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
Labels: mq-approved

#4386 fix: better coinbase handling (see issue #4353)
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/types.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/features/WalletTransactions.feature
Labels: mq-approved

#4425 fix(base-node): allow unused_mut for not(feature = "libtor")
  applications/tari_console_wallet/src/main.rs
Labels: mq-approved

#4433 chore: remove mention of old weatherwax in readme and example
  README.md
  common/src/configuration/mod.rs
Labels: mq-approved

#4434 fix: add missing assets for contribution guide
  Contributing.md
  meta/img/status-active.svg
  meta/img/status-testing.svg
  meta/img/status-wip.svg
Labels: mq-approved

#4428 feat(comms): auto detects configured tor control port auth
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/tor_authentication.rs
  base_layer/p2p/src/transport.rs
  common/config/presets/c_base_node.toml
  common/config/presets/d_console_wallet.toml
  common/src/exit_codes.rs
  comms/core/src/tor/control_client/client.rs
  comms/core/src/tor/control_client/commands/mod.rs
  comms/core/src/tor/control_client/commands/protocol_info.rs
  comms/core/src/tor/control_client/error.rs
  comms/core/src/tor/control_client/parsers.rs
  comms/core/src/tor/control_client/test_server.rs
  comms/core/src/tor/hidden_service/controller.rs
Labels: mq-approved

#4442 fix: cap unlimited rpc connection
  comms/core/src/protocol/rpc/server/mod.rs
Labels: mq-approved

#4446 fix(comms/tor): re-establish tor control port connection for any failure
  comms/core/src/tor/control_client/monitor.rs
  comms/core/src/tor/hidden_service/controller.rs
Labels: mq-approved

#4465 chore: removed unused requests
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/proto/request.proto
  base_layer/core/tests/node_comms_interface.rs
Labels: mq-approved

#4474 feat: remove total_txs and rename total_weight in mempool
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/proto/stats_response.proto
  base_layer/core/src/mempool/proto/stats_response.rs
  base_layer/core/src/mempool/rpc/test.rs
  base_layer/core/src/mempool/service/local_service.rs
  base_layer/core/src/mempool/test_utils/mock.rs
  base_layer/core/tests/mempool.rs
Labels: mq-approved

#4464 fix: wallet always scan interactive payments (see #4452)
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: mq-approved

#4471 chore: remove broken tag from working tests
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/WalletTransfer.feature
Labels: mq-approved

#4483 fix: fix transaction output hashing
  integration_tests/features/support/steps.js
  integration_tests/helpers/hashing.js
  integration_tests/helpers/transactionBuilder.js
  integration_tests/helpers/transactionOutputHashing.js
  integration_tests/helpers/util.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#4445 feat!: apply hashing api to the mmr
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/lib.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/mmr/benches/bench.rs
  base_layer/mmr/src/common.rs
  base_layer/mmr/src/functions.rs
  base_layer/mmr/src/merkle_checkpoint.rs
  base_layer/mmr/src/merkle_mountain_range.rs
  base_layer/mmr/src/merkle_proof.rs
  base_layer/mmr/src/mmr_cache.rs
  base_layer/mmr/src/mutable_mmr.rs
  base_layer/mmr/src/pruned_hashset.rs
  base_layer/mmr/tests/merkle_mountain_range.rs
  base_layer/mmr/tests/merkle_proof.rs
  base_layer/mmr/tests/mmr_cache.rs
  base_layer/mmr/tests/mutable_mmr.rs
  base_layer/mmr/tests/pruned_mmr.rs
  base_layer/mmr/tests/support/mod.rs
  base_layer/mmr/tests/with_blake512_hash.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet_ffi/Cargo.toml
Labels: mq-approved

#4462 chore: lower some log level messages
  comms/core/src/protocol/messaging/error.rs
  comms/core/src/protocol/messaging/outbound.rs
Labels: mq-approved, conflicts

#4460 feat(tariscript)!: use varints in tari script (de)serialization
  Cargo.lock
  infrastructure/tari_script/Cargo.toml
  infrastructure/tari_script/src/op_codes.rs
Labels: mq-approved

#4487 test: fix features-to_consensus_bytes in cucumber
  base_layer/mmr/benches/bench.rs
  integration_tests/helpers/transactionOutputHashing.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#4490 feat: remove more dan layer code
  applications/tari_console_wallet/src/cli.rs
  integration_tests/features/NFT.feature
  integration_tests/features/WalletCli.feature
  integration_tests/features/support/wallet_cli_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#4485 fix: remove use of hardcoded value (see issue #4451)
  comms/dht/src/network_discovery/on_connect.rs
  integration_tests/features/WalletCli.feature
Labels: mq-approved

#4495 fix(base_node_config): check_interval is 0 made base node is panicked
  base_layer/p2p/src/auto_update/service.rs
Labels: mq-approved

#4441 fix: miner config grpc addresses names
  applications/tari_miner/src/config.rs
  applications/tari_miner/src/main.rs
  integration_tests/helpers/config.js
Labels: mq-approved
