Repository tari-project/tari, pull requests merged in 2022-02, with the labels that each got.

#3776 chore: check genesis block during startup
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: mq-approved

#3782 chore: remove debug info from get-mempool-state
  base_layer/core/src/mempool/mod.rs
Labels: mq-approved

#3759 feat: ability to compile on stable rust
  .github/workflows/ci.yml
  applications/tari_collectibles/src-tauri/src/app_state.rs
  applications/tari_collectibles/src-tauri/src/main.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/Makefile
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
  comms/dht/src/lib.rs
  comms/dht/src/store_forward/local_state.rs
Labels: mq-approved

#3764 feat: re-use scanned range proofs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction/test.rs
  base_layer/core/src/transactions/transaction/unblinded_output.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/transaction_service/service.rs
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved

#3787 chore: script to keep .gitkeep file
  applications/tari_collectibles/web-app/package.json
Labels: mq-approved

#3784 feat(base-node): add number of active sync peers metric
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
Labels: mq-approved

#3789 fix: coinbase output recovery bug
  base_layer/core/src/transactions/transaction/output_features.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/master_key_manager.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  integration_tests/features/WalletRecovery.feature
  integration_tests/features/support/mining_node_steps.js
  integration_tests/features/support/node_steps.js
  integration_tests/features/support/wallet_steps.js
  integration_tests/features/support/world.js
  integration_tests/package-lock.json
Labels: mq-approved

#3793 feat: add specific LibWallet error code for “Fee is greater than amount”
  base_layer/wallet_ffi/src/error.rs
Labels: mq-approved

#3798 fix(core): reduce one block behind waiting period
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: mq-approved

#3788 fix(core)!: fix potential panic for sidechain merkle root with incorrect length
  Cargo.lock
  applications/tari_app_grpc/src/conversions/output_features.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/array.rs
  base_layer/common_types/src/lib.rs
  base_layer/common_types/src/types/mod.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/transaction/output_features.rs
  base_layer/core/src/transactions/transaction/side_chain_checkpoint_features.rs
  base_layer/wallet/src/assets/asset_manager.rs
  base_layer/wallet/src/assets/asset_manager_handle.rs
  base_layer/wallet/src/assets/infrastructure/mod.rs
Labels: mq-approved

#3785 fix(comms): minor edge-case fix to handle inbound connection while dialing
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/manager.rs
Labels: mq-approved

#3786 feat(collectibles): add delete committee member button
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/Manage.js
Labels: mq-approved

#3792 refactor: outbound message pipeline, threads and mempool improvements
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/command_handler.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_validator_node/src/comms.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/mempool.rs
  base_layer/p2p/src/initialization.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/src/bounded_executor.rs
  comms/src/multiplexing/yamux.rs
  comms/src/pipeline/builder.rs
  comms/src/pipeline/inbound.rs
  comms/src/pipeline/outbound.rs
  comms/src/protocol/messaging/extension.rs
  comms/src/protocol/rpc/client/mod.rs
Labels: mq-approved

#3795 fix: minor fixes on collectibles
  applications/tari_base_node/Cargo.toml
  applications/tari_collectibles/src-tauri/src/main.rs
  applications/tari_collectibles/web-app/src/Dashboard.js
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  common/Cargo.toml
  common/src/configuration/collectibles_config.rs
  comms/Cargo.toml
  comms/dht/Cargo.toml
  dan_layer/core/Cargo.toml
  infrastructure/metrics/Cargo.toml
Labels: mq-approved

#3796 feat(wallet_ffi)!: add base node connectivity callback to wallet ffi
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/wallet.js
Labels: mq-approved

#3800 docs: readme fixes
  README.md
Labels: mq-approved

#3799 fix: bump flood ban messages config
  applications/launchpad/backend/assets/config.toml
  applications/launchpad/docker_rig/config.toml
  common/config/presets/base_node.toml
  common/src/configuration/utils.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
Labels: mq-approved

#3802 feat: read asset definitions from base layer
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_collectibles/src-tauri/src/clients/wallet_client.rs
  applications/tari_collectibles/src-tauri/src/commands/asset_wallets/mod.rs
  applications/tari_collectibles/src-tauri/src/main.rs
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/binding.js
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  common/config/presets/validator_node.toml
  common/src/configuration/validator_node_config.rs
  dan_layer/core/src/services/base_node_client.rs
  dan_layer/core/src/services/mocks/mod.rs
Labels: mq-approved

#3797 ci: move Apple IDs into envs
  .github/workflows/base_node_binaries.yml
Labels: mq-approved

#3804 refactor: reduce log level of some messages
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  comms/src/connection_manager/common.rs
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/listener.rs
  comms/src/protocol/identity.rs
  comms/src/protocol/rpc/client/mod.rs
  comms/src/protocol/rpc/handshake.rs
Labels: mq-approved

#3753 refactor: minor changes while investigating faucet
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/service_framework/src/stack.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/wallet.rs
Labels: mq-approved

#3808 fix: improved image handling in collectibles
  applications/tari_collectibles/web-app/src/Create.js
Labels: mq-approved

#3810 refactor: split `ErrorCodes` into the `ExitError` and `ExitCode` pair
  applications/launchpad/backend/src/docker/error.rs
  applications/tari_app_utilities/src/identity_management.rs
  applications/tari_app_utilities/src/initialization.rs
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/src/recovery.rs
  applications/tari_console_wallet/src/automation/error.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/main.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/ui/mod.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  applications/tari_mining_node/src/main.rs
  applications/tari_validator_node/src/comms.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/main.rs
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/output_manager_service/error.rs
  common/src/exit_codes.rs
  infrastructure/libtor/src/tor.rs
Labels: mq-approved

#3816 fix: fix rustls and trust-dns-client after version bump
  Cargo.lock
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/auto_update/dns.rs
  base_layer/p2p/src/dns/client.rs
  base_layer/p2p/src/dns/error.rs
  base_layer/p2p/src/peer_seeds.rs
Labels: mq-approved

#3794 feat!: add scanned transaction handling for one-sided payments with callbacks
  applications/ffi_client/index.js
  applications/ffi_client/lib/index.js
  applications/ffi_client/recovery.js
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/common_types/src/transaction.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/src/transaction_service/tasks/check_imported_transaction_status.rs
  base_layer/wallet/src/transaction_service/tasks/mod.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/output_manager_service_mock.rs
  base_layer/wallet/tests/support/transaction_service_mock.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletFFI.feature
  integration_tests/features/support/ffi_steps.js
  integration_tests/features/support/wallet_steps.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/helpers/walletFFIClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#3818 chore(p2p): remove unused config from liveness service
  applications/tari_base_node/src/bootstrap.rs
  base_layer/p2p/src/services/liveness/config.rs
Labels: mq-approved

#3828 feat(wallet): add grpc method for setting base node
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
Labels: mq-approved

#3837 feat: update console wallet tui
  applications/tari_console_wallet/src/ui/app.rs
  applications/tari_console_wallet/src/ui/components/base_node.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/mod.rs
  applications/tari_console_wallet/src/ui/components/network_tab.rs
  applications/tari_console_wallet/src/ui/components/receive_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/common_types/src/transaction.rs
Labels: mq-approved

#3838 feat(cli): resize terminal height
  applications/tari_base_node/src/cli.rs
Labels: mq-approved

#3836 fix(dan): include state_root in node hash
  dan_layer/core/src/models/hot_stuff_tree_node.rs
Labels: mq-approved

#3817 chore: change NodeIdentity debug
  comms/src/peer_manager/node_identity.rs
Labels: mq-approved

#3839 fix: update RFC links and README (#3675)
  RFC/README.md
  RFC/src/SUMMARY.md
  RFC/src/about.md
Labels: mq-approved

#3842 feat: add persistence of transaction cancellation reason to wallet db
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  base_layer/wallet/migrations/2022-02-14-104456_cancellation_column_update/down.sql
  base_layer/wallet/migrations/2022-02-14-104456_cancellation_column_update/up.sql
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/features/WalletCli.feature
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletMonitoring.feature
  integration_tests/features/support/wallet_steps.js
  integration_tests/helpers/ffi/completedTransaction.js
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/util.js
  integration_tests/helpers/walletClient.js
  integration_tests/helpers/walletFFIClient.js
Labels: mq-approved

#3843 ci: cargo test speedups
  .github/workflows/ci.yml
Labels: mq-approved

#3824 ci: improvements to macos pkg
  .github/workflows/base_node_binaries.yml
Labels: mq-approved, mq-failed

#3807 fix(wallet): fix aggressive disconnects in wallet connectivity
  base_layer/wallet/src/connectivity_service/service.rs
  comms/src/connectivity/manager.rs
  comms/src/peer_manager/manager.rs
  comms/src/peer_manager/peer_storage.rs
Labels: mq-approved

#3741 feat(sync): blockchain sync switches peers when max latency is exceeded
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/chain_metadata_service/handle.rs
  base_layer/core/src/base_node/mod.rs
  base_layer/core/src/base_node/state_machine_service/initializer.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/helpers.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/state_machine_service/states/mod.rs
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/config.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/hooks.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/events.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/mod.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/mod.rs
  base_layer/core/src/base_node/sync/sync_peer.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/common/rolling_vec.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/p2p/src/services/liveness/handle.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/src/services/liveness/state.rs
Labels: mq-approved

#3841 feat: adds get-mempool-tx command
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/args.rs
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/macros.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/src/parser.rs
  base_layer/common_types/src/emoji.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/proof_of_work/proof_of_work_algorithm.rs
Labels: mq-approved

#3844 feat(validator-node): committee proposes genesis block w/ instructions
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/grpc/validator_node_grpc_server.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/inbound_connection_service.rs
  applications/tari_validator_node/src/p2p/services/outbound_connection_service.rs
  common/src/configuration/validator_node_config.rs
  dan_layer/core/src/digital_assets_error.rs
  dan_layer/core/src/fixed_hash.rs
  dan_layer/core/src/models/hot_stuff_tree_node.rs
  dan_layer/core/src/models/instruction_set.rs
  dan_layer/core/src/models/view_id.rs
  dan_layer/core/src/services/asset_processor.rs
  dan_layer/core/src/services/infrastructure_services/inbound_connection_service.rs
  dan_layer/core/src/services/infrastructure_services/mocks/mod.rs
  dan_layer/core/src/services/infrastructure_services/outbound_service.rs
  dan_layer/core/src/services/mocks/mod.rs
  dan_layer/core/src/services/payload_processor.rs
  dan_layer/core/src/services/payload_provider.rs
  dan_layer/core/src/services/service_specification.rs
  dan_layer/core/src/storage/chain/chain_db_unit_of_work.rs
  dan_layer/core/src/storage/mocks/mod.rs
  dan_layer/core/src/storage/state/state_db.rs
  dan_layer/core/src/storage/state/state_db_unit_of_work.rs
  dan_layer/core/src/templates/tip002_template.rs
  dan_layer/core/src/templates/tip004_template.rs
  dan_layer/core/src/templates/tip721_template.rs
  dan_layer/core/src/workers/consensus_worker.rs
  dan_layer/core/src/workers/states/commit_state.rs
  dan_layer/core/src/workers/states/decide_state.rs
  dan_layer/core/src/workers/states/next_view.rs
  dan_layer/core/src/workers/states/pre_commit_state.rs
  dan_layer/core/src/workers/states/prepare.rs
  dan_layer/core/src/workers/states/starting.rs
  dan_layer/storage_sqlite/src/sqlite_chain_backend_adapter.rs
  dan_layer/storage_sqlite/src/sqlite_db_factory.rs
Labels: mq-approved

#3846 fix: improve sha3 pool mining
  applications/tari_mining_node/src/difficulty.rs
  applications/tari_mining_node/src/main.rs
  applications/tari_mining_node/src/miner.rs
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_mining_node/src/stratum/error.rs
  applications/tari_mining_node/src/stratum/mod.rs
  applications/tari_mining_node/src/stratum/stratum_controller/controller.rs
  applications/tari_mining_node/src/stratum/stratum_miner/control_message.rs
  applications/tari_mining_node/src/stratum/stratum_miner/job_shared_data.rs
  applications/tari_mining_node/src/stratum/stratum_miner/miner.rs
  applications/tari_mining_node/src/stratum/stratum_miner/mod.rs
  applications/tari_mining_node/src/stratum/stratum_miner/solution.rs
  applications/tari_mining_node/src/stratum/stratum_miner/solver_instance.rs
  applications/tari_mining_node/src/stratum/stratum_statistics/mod.rs
  applications/tari_mining_node/src/stratum/stratum_statistics/stats.rs
  common/logging/log4rs_sample_mining_node.yml
Labels: mq-approved

#3845 ci: test with all features enabled
  .github/scripts/libwallet/build_jnilib.sh
  .github/scripts/libwallet/entrypoint.sh
  .github/scripts/libwallet/hash_libs.sh
  .github/scripts/libwallet/setup.sh
  .github/scripts/libwallet/sqlite-autoconf-3360000.tar.gz
  .github/workflows/ci.yml
  base_layer/key_manager/src/cipher_seed.rs
Labels: mq-approved

#3858 refactor: improve the commands parser
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/command_handler.rs
  applications/tari_base_node/src/commands/args.rs
  applications/tari_base_node/src/commands/cli.rs
  applications/tari_base_node/src/commands/command_handler.rs
  applications/tari_base_node/src/commands/mod.rs
  applications/tari_base_node/src/commands/parser.rs
  applications/tari_base_node/src/commands/performer.rs
  applications/tari_base_node/src/commands/reader.rs
  applications/tari_base_node/src/commands/status_line.rs
  applications/tari_base_node/src/macros.rs
  applications/tari_base_node/src/main.rs
Labels: mq-approved

#3862 chore: update README's "Conversation channels" part
  README.md
Labels: mq-approved, mq-priority

#3856 chore: consolidate fee_per_gram
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  common/src/configuration/global.rs
  common/src/configuration/wallet_config.rs
Labels: mq-approved

#3865 fix: remove critical tag from flaky cucumber test
  integration_tests/features/WalletRecovery.feature
Labels: mq-approved

#3853 fix(wallet): minor wording fix on transactions tab
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/wallet/src/connectivity_service/service.rs
Labels: mq-approved

#3863 feat: add logging of cancelled outputs when transaction is rejected
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
Labels: mq-approved, mq-priority

#3857 feat: add contacts liveness service to base layer wallet
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  base_layer/p2p/src/proto/liveness.proto
  base_layer/p2p/src/services/liveness/handle.rs
  base_layer/p2p/src/services/liveness/mock.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/migrations/2022-02-16-110518_add_last_seen_to_contacts/down.sql
  base_layer/wallet/migrations/2022-02-16-110518_add_last_seen_to_contacts/up.sql
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/contacts_service/error.rs
  base_layer/wallet/src/contacts_service/handle.rs
  base_layer/wallet/src/contacts_service/mod.rs
  base_layer/wallet/src/contacts_service/service.rs
  base_layer/wallet/src/contacts_service/storage/database.rs
  base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/contacts_service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  integration_tests/helpers/config.js
Labels: mq-approved

#3866 fix: fix flakey `test_coinbase_abandoned` integration test
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#3852 feat(base-node): allow status line interval to be configured
  applications/tari_app_utilities/src/initialization.rs
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/commands/command_handler.rs
  applications/tari_base_node/src/commands/performer.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_validator_node/src/comms.rs
  applications/tari_validator_node/src/main.rs
  common/config/presets/base_node.toml
  common/src/configuration/collectibles_config.rs
  common/src/configuration/global.rs
  common/src/configuration/validator_node_config.rs
Labels: mq-approved

#3859 ci: build improvements - rust caching + bash updates/sync
  .github/workflows/base_node_binaries.yml
  applications/tari_base_node/osx-pkg/ReadMe.md
  buildtools/create_osx_install_zip.sh
  buildtools/create_ubuntu_install_zip.sh
Labels: mq-approved

#3840 feat(dht): convenience function for DHT to discover then connect
  applications/tari_base_node/src/commands/command_handler.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node/src/p2p/services/rpc_client.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/actor.rs
  comms/dht/src/dht.rs
  comms/dht/src/discovery/mod.rs
  comms/dht/src/discovery/requester.rs
  comms/dht/src/discovery/service.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/test_utils/dht_actor_mock.rs
  comms/dht/src/test_utils/dht_discovery_mock.rs
  comms/dht/tests/dht.rs
  comms/src/connection_manager/common.rs
  comms/src/connection_manager/error.rs
  dan_layer/core/src/services/validator_node_rpc_client.rs
Labels: mq-approved

#3830 feat: add support for make-it-rain command
  applications/tari_collectibles/src-tauri/src/commands/asset_wallets/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/assets/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/keys/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/tip004/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/tip721/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/wallets/mod.rs
  applications/tari_collectibles/src-tauri/src/main.rs
  applications/tari_collectibles/src-tauri/src/status.rs
  applications/tari_collectibles/src-tauri/src/storage/models/wallet_row.rs
Labels: mq-approved

#3855 fix(validator-node): fix consensus stall after genesis
  applications/tari_validator_node/src/default_service_specification.rs
  dan_layer/core/src/models/view.rs
  dan_layer/core/src/services/asset_proxy.rs
  dan_layer/core/src/services/service_specification.rs
  dan_layer/core/src/workers/consensus_worker.rs
  dan_layer/core/src/workers/states/commit_state.rs
  dan_layer/core/src/workers/states/decide_state.rs
  dan_layer/core/src/workers/states/next_view.rs
  dan_layer/core/src/workers/states/pre_commit_state.rs
  dan_layer/core/src/workers/states/prepare.rs
  dan_layer/core/src/workers/states/starting.rs
  dan_layer/core/src/workers/states/synchronizing.rs
Labels: mq-approved

#3869 chore: fix cargo udeps warnings in tari_metrics
  Cargo.lock
  base_layer/p2p/Cargo.toml
  common/Cargo.toml
  comms/Cargo.toml
  infrastructure/metrics/Cargo.toml
Labels: mq-approved

#3868 feat: add contacts status to tui
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  applications/tari_console_wallet/src/ui/ui_contact.rs
  applications/tari_console_wallet/src/utils/formatting.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/contacts_service/handle.rs
  base_layer/wallet/src/contacts_service/mod.rs
  base_layer/wallet/src/contacts_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/contacts_service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
Labels: mq-approved

#3870 ci: macOS PKG Notarisation + Stapler and upload updates
  .github/workflows/base_node_binaries.yml
Labels: mq-approved

#3872 feat: update committee selection from collectibles
  Cargo.lock
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_collectibles/package-lock.json
  applications/tari_collectibles/package.json
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_collectibles/src-tauri/src/clients/base_node_client.rs
  applications/tari_collectibles/src-tauri/src/clients/wallet_client.rs
  applications/tari_collectibles/src-tauri/src/commands/assets/mod.rs
  applications/tari_collectibles/src-tauri/src/error.rs
  applications/tari_collectibles/src-tauri/src/main.rs
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/src/AccountDashboard.js
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_collectibles/web-app/src/AssetCommitteeManager.js
  applications/tari_collectibles/web-app/src/AssetManager.js
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/Manage.js
  applications/tari_collectibles/web-app/src/binding.js
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  base_layer/common_types/src/types/mod.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/wallet/src/assets/asset_manager.rs
  base_layer/wallet/src/assets/asset_manager_handle.rs
  base_layer/wallet/src/assets/infrastructure/asset_manager_service.rs
  base_layer/wallet/src/assets/infrastructure/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  dan_layer/core/src/models/asset_definition.rs
  dan_layer/core/src/models/base_layer_output.rs
  dan_layer/core/src/models/error.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/services/asset_proxy.rs
  dan_layer/core/src/workers/state_sync/mod.rs
  dan_layer/core/src/workers/states/mod.rs
  dan_layer/core/src/workers/states/starting.rs
  dan_layer/core/src/workers/states/synchronizing.rs
  integration_tests/features/WalletCli.feature
  integration_tests/features/support/wallet_cli_steps.js
Labels: mq-approved

#3871 feat!: add support for specifying custom messages for scanned outputs in libwallet
  base_layer/wallet/src/connectivity_service/initializer.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/utxo_scanner_service/handle.rs
  base_layer/wallet/src/utxo_scanner_service/initializer.rs
  base_layer/wallet/src/utxo_scanner_service/mod.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/support/output_manager_service_mock.rs
  base_layer/wallet/tests/support/transaction_service_mock.rs
  base_layer/wallet/tests/utxo_scanner.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved, mq-priority
