Repository tari-project/tari, pull requests merged in 2022-03, with the labels that each got.

#3814 fix: fix merge mining proxy pool mining
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  common/config/presets/merge_mining_proxy.toml
  common/src/configuration/global.rs
  common/src/configuration/merge_mining_config.rs
  common/src/configuration/utils.rs
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/config.js
  integration_tests/helpers/mergeMiningProxyProcess.js
  integration_tests/helpers/miningNodeProcess.js
  integration_tests/helpers/stratumTranscoderProcess.js
  integration_tests/helpers/validatorNodeProcess.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3915 ci: add tari_wallet_ffi check to ci
  .github/workflows/ci.yml
  base_layer/core/src/common/mod.rs
Labels: mq-approved

#3899 fix: aligned tables left
  RFC/src/theme/css/general.css
Labels: mq-approved

#3867 refactor: use clap as a commands parser
  Cargo.lock
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/commands/args.rs
  applications/tari_base_node/src/commands/command/ban_peer.rs
  applications/tari_base_node/src/commands/command/block_timing.rs
  applications/tari_base_node/src/commands/command/check_db.rs
  applications/tari_base_node/src/commands/command/check_for_updates.rs
  applications/tari_base_node/src/commands/command/dial_peer.rs
  applications/tari_base_node/src/commands/command/discover_peer.rs
  applications/tari_base_node/src/commands/command/get_block.rs
  applications/tari_base_node/src/commands/command/get_chain_metadata.rs
  applications/tari_base_node/src/commands/command/get_db_stats.rs
  applications/tari_base_node/src/commands/command/get_mempool_state.rs
  applications/tari_base_node/src/commands/command/get_mempool_stats.rs
  applications/tari_base_node/src/commands/command/get_network_stats.rs
  applications/tari_base_node/src/commands/command/get_peer.rs
  applications/tari_base_node/src/commands/command/get_state_info.rs
  applications/tari_base_node/src/commands/command/header_stats.rs
  applications/tari_base_node/src/commands/command/list_banned_peers.rs
  applications/tari_base_node/src/commands/command/list_connections.rs
  applications/tari_base_node/src/commands/command/list_headers.rs
  applications/tari_base_node/src/commands/command/list_peers.rs
  applications/tari_base_node/src/commands/command/list_reorgs.rs
  applications/tari_base_node/src/commands/command/mod.rs
  applications/tari_base_node/src/commands/command/period_stats.rs
  applications/tari_base_node/src/commands/command/ping_peer.rs
  applications/tari_base_node/src/commands/command/quit.rs
  applications/tari_base_node/src/commands/command/reset_offline_peers.rs
  applications/tari_base_node/src/commands/command/rewind_blockchain.rs
  applications/tari_base_node/src/commands/command/search_kernel.rs
  applications/tari_base_node/src/commands/command/search_utxo.rs
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_base_node/src/commands/command/unban_all_peers.rs
  applications/tari_base_node/src/commands/command/version.rs
  applications/tari_base_node/src/commands/command/watch_command.rs
  applications/tari_base_node/src/commands/command/whoami.rs
  applications/tari_base_node/src/commands/command_handler.rs
  applications/tari_base_node/src/commands/mod.rs
  applications/tari_base_node/src/commands/nom_parser.rs
  applications/tari_base_node/src/commands/parser.rs
  applications/tari_base_node/src/commands/performer.rs
  applications/tari_base_node/src/commands/status_line.rs
  applications/tari_base_node/src/main.rs
  common/src/configuration/bootstrap.rs
  integration_tests/helpers/baseNodeProcess.js
Labels: mq-approved

#3910 ci: fix missing npm deps and add javascript ci
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
  applications/launchpad/gui-vue/package-lock.json
  applications/launchpad/gui-vue/package.json
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/package.json
  applications/tari_explorer/package-lock.json
  applications/tari_explorer/package.json
  applications/tari_explorer/routes/index.js
  applications/tari_explorer/views/404.hbs
  applications/tari_explorer/views/assets.hbs
  applications/tari_explorer/views/index.hbs
  applications/tari_explorer/views/mempool.hbs
  applications/tari_explorer/views/search.hbs
  applications/tari_explorer/views/validator.hbs
Labels: mq-approved

#3916 fix(consensus): check blockchain version within valid range
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/header_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
Labels: mq-approved

#3906 chore: clean up providing seed words from LibWallet
  applications/tari_console_wallet/src/init/mod.rs
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/key_manager_service/handle.rs
  base_layer/wallet/src/key_manager_service/interface.rs
  base_layer/wallet/src/key_manager_service/mock.rs
  base_layer/wallet/src/key_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved, mq-failed

#3820 chore!: change hash to use consensus encoding
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
Labels: Consensus Change, do not merge

#3917 fix: clap commands improvements
  applications/tari_base_node/src/commands/args.rs
  applications/tari_base_node/src/commands/command/ban_peer.rs
  applications/tari_base_node/src/commands/command/block_timing.rs
  applications/tari_base_node/src/commands/command/check_db.rs
  applications/tari_base_node/src/commands/command/check_for_updates.rs
  applications/tari_base_node/src/commands/command/dial_peer.rs
  applications/tari_base_node/src/commands/command/discover_peer.rs
  applications/tari_base_node/src/commands/command/get_block.rs
  applications/tari_base_node/src/commands/command/get_chain_metadata.rs
  applications/tari_base_node/src/commands/command/get_db_stats.rs
  applications/tari_base_node/src/commands/command/get_mempool_state.rs
  applications/tari_base_node/src/commands/command/get_mempool_stats.rs
  applications/tari_base_node/src/commands/command/get_network_stats.rs
  applications/tari_base_node/src/commands/command/get_peer.rs
  applications/tari_base_node/src/commands/command/get_state_info.rs
  applications/tari_base_node/src/commands/command/header_stats.rs
  applications/tari_base_node/src/commands/command/list_banned_peers.rs
  applications/tari_base_node/src/commands/command/list_connections.rs
  applications/tari_base_node/src/commands/command/list_headers.rs
  applications/tari_base_node/src/commands/command/list_peers.rs
  applications/tari_base_node/src/commands/command/list_reorgs.rs
  applications/tari_base_node/src/commands/command/mod.rs
  applications/tari_base_node/src/commands/command/period_stats.rs
  applications/tari_base_node/src/commands/command/ping_peer.rs
  applications/tari_base_node/src/commands/command/quit.rs
  applications/tari_base_node/src/commands/command/reset_offline_peers.rs
  applications/tari_base_node/src/commands/command/rewind_blockchain.rs
  applications/tari_base_node/src/commands/command/search_kernel.rs
  applications/tari_base_node/src/commands/command/search_utxo.rs
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_base_node/src/commands/command/unban_all_peers.rs
  applications/tari_base_node/src/commands/command/version.rs
  applications/tari_base_node/src/commands/command/watch_command.rs
  applications/tari_base_node/src/commands/command/whoami.rs
  applications/tari_base_node/src/commands/mod.rs
  applications/tari_base_node/src/commands/nom_parser.rs
  applications/tari_base_node/src/commands/reader.rs
  applications/tari_base_node/src/main.rs
Labels: mq-approved

#3924 fix: launch the watch command on start
  applications/tari_base_node/src/main.rs
Labels: mq-approved

#3930 feat: add mmr check to reconstructed block and mempool validation for unique excess signature
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/mempool.rs
Labels: mq-approved

#3905 chore: hide private values in debug and serialize
  Cargo.lock
  applications/launchpad/backend/Cargo.toml
  applications/launchpad/backend/src/commands/launch_docker.rs
  applications/launchpad/backend/src/commands/service.rs
  applications/launchpad/backend/src/docker/settings.rs
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_collectibles/src-tauri/src/models/wallet.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/proxy.rs
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/stratum/stratum_types/login_params.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/transactions/transaction_components/unblinded_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  common/Cargo.toml
  common/src/configuration/global.rs
  common/src/configuration/merge_mining_config.rs
  comms/Cargo.toml
  comms/src/tor/control_client/commands/add_onion.rs
  comms/src/tor/hidden_service/mod.rs
  infrastructure/libtor/Cargo.toml
  infrastructure/libtor/src/tor.rs
Labels: mq-approved

#3934 fix: correct main path for wallet rpc client
  applications/daily_tests/washing_machine.js
  applications/tari_collectibles/web-app/package-lock.json
  clients/wallet_grpc_client/package.json
Labels: mq-approved, mq-priority

#3932 feat(metrics): add UTXO set size to base node metrics
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proof_of_work/proof_of_work_algorithm.rs
  comms/src/peer_manager/manager.rs
  comms/src/peer_manager/metrics.rs
  comms/src/peer_manager/mod.rs
Labels: mq-approved

#3922 ci: add auto labeler for clippy
  .github/workflows/auto_labels.yml
  .github/workflows/ci.yml
Labels: mq-approved

#3946 fix(wallet): tor identity private key needs to be serialized
  comms/src/tor/hidden_service/mod.rs
Labels: mq-approved

#3948 chore(core): make HashWriter API more ergonomic and similar to Digest
  base_layer/core/src/common/hash_writer.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: mq-approved

#3951 fix(wallet): ensure that identity sig is stored on startup
  base_layer/wallet/src/wallet.rs
Labels: mq-approved

#3949 refactor: improve ergonomics of error to RPC status
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/base_node/rpc/sync_utxos_by_block_task.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  comms/src/protocol/rpc/mod.rs
  comms/src/protocol/rpc/status.rs
Labels: mq-approved

#3926 fix: bug in block timing grpc method
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/commands/command/mod.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/validation/test.rs
Labels: mq-approved

#3950 fix: fix Tor ID deserialization issue
  applications/tari_console_wallet/src/init/mod.rs
Labels: mq-approved

#3938 feat: script to produce coverage report for wallet
  .gitignore
  scripts/code_coverage_wallet.sh
Labels: mq-approved

#3955 fix(sync): ban peer if sending invalid prev_header
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
Labels: mq-approved

#3953 feat(dht): monitor and display warning for min ratio for TCPv4 nodes
  applications/tari_base_node/src/bootstrap.rs
  common/config/presets/common.toml
  common/src/configuration/global.rs
  common/src/configuration/utils.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/lib.rs
Labels: mq-approved

#3947 docs: add docstring to merge mining proxy
  applications/tari_merge_mining_proxy/src/block_template_data.rs
  applications/tari_merge_mining_proxy/src/block_template_protocol.rs
  applications/tari_merge_mining_proxy/src/common/json_rpc.rs
  applications/tari_merge_mining_proxy/src/common/merge_mining.rs
  applications/tari_merge_mining_proxy/src/common/mod.rs
  applications/tari_merge_mining_proxy/src/common/monero_rpc.rs
  applications/tari_merge_mining_proxy/src/common/proxy.rs
  applications/tari_merge_mining_proxy/src/error.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/covenants/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/mmr/src/lib.rs
  infrastructure/storage/src/lmdb_store/store.rs
Labels: mq-approved

#3959 fix: fix handling of creating faux transaction for recovered outputs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/output_manager_service_mock.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#3962 docs(tari-script): fix doctests
  infrastructure/tari_script/src/script_commitment.rs
Labels: mq-approved

#3954 chore(dht): take out "TODO: remove" for message tag
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/message.rs
  comms/dht/src/proto/envelope.proto
  comms/dht/src/store_forward/forward.rs
Labels: mq-approved

#3935 test(core): reinstate inputs_not_mallaeble test
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
Labels: mq-approved

#3964 feat(core): add tip height metric
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/chain_storage/block_add_result.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: mq-approved

#3969 fix: add output option to the status command
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_base_node/src/commands/status_line.rs
Labels: mq-approved

#3971 fix: revert changes to key manager branch seed strings
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/resources.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
Labels: mq-approved, mq-priority

#3970 chore: resolve zeroize version conflict (using fork)
  Cargo.lock
  Cargo.toml
Labels: mq-approved

#3972 ci: fix the recovery daily test
  applications/daily_tests/automatic_recovery_test.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3968 test(mempool): add criterion bench for large transaction inserts
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/core/benches/mempool.rs
  base_layer/core/src/mempool/consts.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
Labels: mq-approved

#3811 chore: change error propagation in validator node
  Cargo.lock
  applications/tari_validator_node/src/comms.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/grpc/services/wallet_client.rs
  applications/tari_validator_node/src/p2p/services/inbound_connection_service.rs
  applications/tari_validator_node/src/p2p/services/outbound_connection_service.rs
  common/src/exit_codes.rs
  dan_layer/core/Cargo.toml
  dan_layer/core/src/digital_assets_error.rs
Labels: mq-approved, mq-failed

#3963 refactor: reduce unwrap calls in the tari_mining_node
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_mining_node/src/stratum/error.rs
  applications/tari_mining_node/src/stratum/stratum_controller/controller.rs
  applications/tari_mining_node/src/stratum/stream.rs
Labels: mq-approved

#3965 ci: add npm audit
  .github/workflows/ci.yml
  applications/launchpad/gui-vue/package-lock.json
  applications/launchpad/gui-vue/package.json
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/package.json
  applications/tari_explorer/package-lock.json
  applications/tari_web_extension/package-lock.json
  applications/tari_web_extension/package.json
  applications/tari_web_extension_example/package-lock.json
Labels: mq-approved, mq-failed

#3977 feat: implement qr code for base node
  .gitignore
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/commands/command/whoami.rs
Labels: mq-approved

#3981 chore(core): update merge mining hash to use ergonomic HashWriter api
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/epoch_time.rs
Labels: mq-approved

#3985 fix: package.json in launchpad/gui-vue
  applications/launchpad/gui-vue/package-lock.json
  applications/launchpad/gui-vue/package.json
Labels: mq-approved

#3978 fix: another fix for the recovery daily test
  applications/daily_tests/automatic_recovery_test.js
  applications/daily_tests/cron_jobs.js
Labels: mq-approved, mq-priority

#3989 refactor: decompose consensus worker
  applications/tari_validator_node/src/default_service_specification.rs
  dan_layer/core/src/services/service_specification.rs
  dan_layer/core/src/workers/consensus_worker.rs
  dan_layer/core/src/workers/states/next_view.rs
  dan_layer/core/src/workers/states/starting.rs
  dan_layer/core/src/workers/states/synchronizing.rs
Labels: mq-approved

#3920 feat: add config setting to resize terminal
  Cargo.lock
  applications/tari_base_node/src/commands/cli.rs
  applications/tari_base_node/src/commands/cli_loop.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/ui/mod.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/main.rs
  common/config/presets/base_node.toml
  common/src/configuration/global.rs
Labels: mq-approved

#3991 chore: use tari-project/rpgp repo for override
  Cargo.lock
  Cargo.toml
Labels: mq-approved

#3992 fix: recovery daily test reporting of uT was rounding incorrectly
  applications/daily_tests/automatic_recovery_test.js
Labels: mq-approved
