Repository tari-project/tari, pull requests merged in 2022-11, with the labels that each got.

#4871 fix(ci): selectively revert resolver for arm64 builds
  .github/workflows/base_node_binaries.yml
Labels: C-bug, P-controversial, A-ci

#4862 feat!: impl final tari pow algorithm
  applications/tari_miner/src/difficulty.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proof_of_work/sha3_pow.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: C-consensus_breaking, P-acks_required

#4877 fix(comms/peer_manager): fix possible panic in offline calc
  comms/core/src/peer_manager/peer.rs
Labels: P-merge

#4876 fix(ci): correct ARM64 builds
  .github/workflows/base_node_binaries.yml
  Cross.toml
Labels: P-acks_required

#4883 fix(ci): resolve windows binary builds
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libwallets_workflow.yml
  .github/workflows/ci.yml
Labels: P-acks_required

#4885 chore: better help for seed-words command
  applications/tari_console_wallet/src/cli.rs
Labels: CR-insufficient_context, P-merge

#4891 chore: delete some unneed, unsafe functions
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  infrastructure/tari_script/src/lib.rs
  infrastructure/tari_script/src/script_commitment.rs
Labels: P-merge, P-reviews_required, P-acks_required

#4899 docs: add warning labels
  Contributing.md
Labels: C-documentation, P-merge

#4844 fix(dht): use new DHKE shared secret type
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/wallet.h
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/core/src/noise/crypto_resolver.rs
  comms/core/src/types.rs
  comms/dht/Cargo.toml
  comms/dht/src/crypt.rs
  comms/dht/src/dht.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/test_utils/makers.rs
  infrastructure/tari_script/Cargo.toml
Labels: P-merge

#4854 fix: added UtxoSelectionMode to enable unrestricted output listing [issue #4811]
  base_layer/wallet/src/output_manager_service/input_selection.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
Labels: P-acks_required

#4860 fix!: refactor `CipherSeed`, zeroize, and fix key derivation
  Cargo.lock
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: A-wallet, W-transaction-breaking

#4874 fix: remove tari script serialization fix migration
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: P-acks_required

#4880 fix(core)!: remove unused get_committees call from base node
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/key_prefix_cursor.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
Labels: P-acks_required

#4892 fix!: update `argon2` and improve key handling
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_grpc/src/authentication/salted_password.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
Labels: P-acks_required

#4900 docs: add transaction breaking warning label
  Contributing.md
Labels: CR-insufficient_context, P-acks_required

#4902 fix(core/metrics): set target difficulty as single value
  Cargo.lock
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
Labels: P-acks_required

#4847 fix(wallet)!: use KDFs on ECDH shared secrets
  base_layer/wallet/src/lib.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: A-wallet, P-merge, P-reviews_required, P-acks_required, W-transaction-breaking

#4897 feat: mempool sync wait for node initial sync
  base_layer/core/src/mempool/sync_protocol/initializer.rs
Labels: P-merge

#4905 fix: force wallet sqlite to do checkpoint after db decryption
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
Labels: P-acks_required

#4910 test(mempool): add test to confirm FeePriority works
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
Labels: P-merge

#4907 docs: change active to stable
  Contributing.md
Labels: CR-insufficient_context

#4914 chore: reset version for reset
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/sha3_pow.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  infrastructure/tari_script/src/op_codes.rs
Labels: A-base_node, mq-failed

#4918 test: failed consensus encoding test
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-merge

#4881 feat!: add tari address for wallet to use
  .license.ignore
  Cargo.lock
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/cli.rs
  applications/tari_console_wallet/src/grpc/mod.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/notifier/mod.rs
  applications/tari_console_wallet/src/ui/app.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/receive_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/tasks.rs
  applications/tari_console_wallet/src/ui/ui_contact.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/emoji.rs
  base_layer/common_types/src/lib.rs
  base_layer/common_types/src/tari_address.rs
  base_layer/wallet/migrations/2022-08-08-134037_initial/up.sql
  base_layer/wallet/src/contacts_service/handle.rs
  base_layer/wallet/src/contacts_service/service.rs
  base_layer/wallet/src/contacts_service/storage/database.rs
  base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/send_transaction_reply.rs
  base_layer/wallet/src/util/mod.rs
  base_layer/wallet/src/util/wallet_identity.rs
  base_layer/wallet/src/utxo_scanner_service/initializer.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/contacts_service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  common/src/configuration/network.rs
Labels: CR-too_long, P-merge, P-reviews_required

#4887 feat: timestamp validation
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/block_validators/body_only.rs
  base_layer/core/src/validation/header_validator.rs
  base_layer/core/tests/block_validation.rs
Labels: P-do_not_merge, P-clippy_failed, P-high-risk, P-controversial, P-reviews_required, P-acks_required, mq-failed

#4925 fix: add hidden types and seed words to key manager
  Cargo.lock
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/lib.rs
  applications/tari_console_wallet/src/recovery.rs
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/diacritics.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/mnemonic.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: A-security, A-wallet

#4960 feat: only coinbase output features may have metadata set, and is of limited size; ref #4908
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/validation/block_validators/orphan.rs
  base_layer/core/src/validation/helpers.rs
Labels: mq-failed

#4955 feat: reset broken sync
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
Labels: P-controversial
