Repository tari-project/tari, pull requests merged in 2022-12, with the labels that each got.

#4984 fix: remove optionals from wallet set up
  Cargo.lock
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/lib.rs
  base_layer/wallet/src/key_manager_service/handle.rs
  base_layer/wallet/src/key_manager_service/interface.rs
  base_layer/wallet/src/key_manager_service/mock.rs
  base_layer/wallet/src/key_manager_service/service.rs
  base_layer/wallet/src/key_manager_service/storage/database/backend.rs
  base_layer/wallet/src/key_manager_service/storage/database/mod.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/macros.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/storage/database.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/storage/sqlite_utilities/mod.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/key_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: A-mobile_wallet, A-security, A-wallet, P-controversial, A-wallet-ffi

#4969 chore: remove all unnecessary unwrap
  Cargo.lock
  applications/tari_app_grpc/src/conversions/aggregate_body.rs
  applications/tari_app_grpc/src/conversions/new_block_template.rs
  applications/tari_app_grpc/src/conversions/transaction_input.rs
  applications/tari_app_grpc/src/conversions/transaction_output.rs
  applications/tari_app_grpc/src/conversions/unblinded_output.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/base_node/proto/rpc.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/base_node/rpc/sync_utxos_by_block_task.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/common/borsh.rs
  base_layer/core/src/covenants/serde.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/src/proto/block.rs
  base_layer/core/src/proto/block_header.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/proto/recipient_signed_message.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/tasks/send_transaction_reply.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-failed

#5004 chore: remove unused message field from OMS
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: mq-failed

#4983 fix!: input and output signatures
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/tests/mempool.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/tests/utxo_scanner.rs
Labels: W-consensus_breaking

#5020 feat: revalidate invalid utxo
  base_layer/wallet/migrations/2022-12-07-110000/down.sql
  base_layer/wallet/migrations/2022-12-07-110000/up.sql
  base_layer/wallet/src/output_manager_service/config.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/schema.rs
  common/config/presets/d_console_wallet.toml
Labels: mq-failed

#5038 feat: add burn-tari to make-it-rain
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/cli.rs
Labels: P-acks_required

#5039 fix(core): fixes stale chain metadata being sent to listening state
  base_layer/core/src/base_node/chain_metadata_service/handle.rs
  base_layer/core/src/base_node/chain_metadata_service/initializer.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: P-acks_required

#5028 docs: multi-party range proof documentation
  docs/src/SUMMARY.md
  docs/src/multi_party_range.md
Labels: P-acks_required

#5047 fix(ci): pin ci to ubuntu 20.04
  .github/workflows/integration_tests.yml
Labels: P-acks_required

#5049 fix: support arbitrary range proof batching
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-merge

#5035 chore: remove metadata references
  applications/tari_app_grpc/proto/transaction.proto
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_app_grpc/src/conversions/output_features.rs
  applications/tari_base_node/src/commands/command/get_mempool_state.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/covenants/byte_codes.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/covenants/decoder.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/fee.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/transactions/weight.rs
  base_layer/core/tests/mempool.rs
  base_layer/wallet/migrations/2022-12-09-114100_rename_metadata_to_coinbase_extra/down.sql
  base_layer/wallet/migrations/2022-12-09-114100_rename_metadata_to_coinbase_extra/up.sql
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
Labels: P-merge

#5058 feat: add cucumber utils for mining blocks and arrive at height
  integration_tests/tests/cucumber.rs
Labels: P-acks_required

#5061 fix: fixing broken base node in the feature-cucumber-rs branch
  applications/tari_base_node/src/lib.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/utils/base_node_process.rs
Labels: mq-failed

#5063 fix: cucumber base node lock issue
  integration_tests/tests/cucumber.rs
  integration_tests/tests/utils/base_node_process.rs
  integration_tests/tests/utils/wallet_process.rs
Labels: mq-failed

#5059 fix: add further cucumber utils
  Cargo.lock
  integration_tests/Cargo.toml
  integration_tests/tests/cucumber.rs
  integration_tests/tests/utils/base_node_process.rs
  integration_tests/tests/utils/miner.rs
Labels: CR-insufficient_context, CR-too_long, P-reviews_required, P-acks_required, mq-failed

#5066 feat: add further cucumber rs steps
  Cargo.lock
  integration_tests/Cargo.toml
  integration_tests/tests/cucumber.rs
  integration_tests/tests/utils/base_node_process.rs
Labels: mq-failed

#5069 feat: add transaction builder for cucumber rs tests
  Cargo.lock
  integration_tests/Cargo.toml
  integration_tests/features/WalletQuery.feature
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/WalletQuery.feature
  integration_tests/tests/utils/miner.rs
  integration_tests/tests/utils/mod.rs
  integration_tests/tests/utils/transaction.rs
  integration_tests/tests/utils/wallet_process.rs
Labels: mq-failed

#5073 feat: add steps in base node connectivity feature
  integration_tests/features/BaseNodeConnectivity.feature
  integration_tests/features/WalletTransfer.feature
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/BaseNodeConnectivity.feature
  integration_tests/tests/features/WalletTransfer.feature
Labels: mq-failed
