Repository tari-project/tari, pull requests merged in 2022-04, with the labels that each got.

#3904 feat!: add less aggressive txn cancelling
  applications/ffi_client/index.js
  applications/ffi_client/lib/index.js
  applications/ffi_client/recovery.js
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/notifier/mod.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/tasks.rs
  applications/tari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/common_types/src/transaction.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/README.md
  integration_tests/features/WalletTransactions.feature
  integration_tests/helpers/ffi/ffiInterface.js
  integration_tests/helpers/ffi/livenessData.js
  integration_tests/helpers/ffi/transactionSendStatus.js
  integration_tests/helpers/ffi/wallet.js
  integration_tests/package-lock.json
  integration_tests/package.json
Labels: mq-approved, mq-priority

#3918 chore: rewrite to_bytes_with_language
  base_layer/key_manager/src/mnemonic.rs
Labels: mq-approved

#3994 test: add non-critical and long-running to CI
  .github/workflows/long_running.yml
  .github/workflows/non_critical_integration_tests.yml
  integration_tests/cucumber.js
Labels: mq-approved

#3996 fix: estimated hashrate calculation is incorrect
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_base_node/src/grpc/hash_rate.rs
  applications/tari_base_node/src/grpc/mod.rs
  applications/tari_explorer/routes/index.js
  applications/tari_explorer/views/index.hbs
  clients/base_node_grpc_client/src/index.js
  integration_tests/features/support/steps.js
Labels: mq-approved

#3945 chore: deprecate stratum transcoder
  .circleci/config.yml
  .github/wip_integration_tests.yml
  .github/workflows/base_node_binaries.yml
  Cargo.lock
  Cargo.toml
  README.md
  applications/launchpad/backend/assets/config.toml
  applications/launchpad/docker_rig/config.toml
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_mining_node/Cargo.toml
  applications/tari_mining_node/src/stratum/controller.rs
  applications/tari_mining_node/src/stratum/stratum_controller/controller.rs
  applications/tari_mining_node/src/stratum/stratum_types/miner_message.rs
  applications/tari_stratum_transcoder/README.md
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/src/error.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/tari_stratum_ffi/src/lib.rs
  integration_tests/Makefile
  integration_tests/features/StratumTranscoder.feature
  integration_tests/features/support/stratum_transcoder_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/config.js
  integration_tests/helpers/stratumTranscoderClient.js
  integration_tests/helpers/stratumTranscoderProcess.js
  scripts/update_crate_metadata.sh
Labels: mq-approved, mq-priority

#3958 feat: check file perms on identity files
  Cargo.lock
  applications/tari_app_utilities/src/identity_management.rs
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/commands/cli_loop.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/main.rs
  base_layer/p2p/src/initialization.rs
  common/Cargo.toml
  common/src/configuration/utils.rs
  common/src/exit_codes.rs
Labels: mq-approved

#3998 refactor: add lock error to the StorageError
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/grpc/services/wallet_client.rs
  dan_layer/core/src/services/asset_proxy.rs
  dan_layer/core/src/services/base_node_client.rs
  dan_layer/core/src/services/service_specification.rs
  dan_layer/core/src/services/validator_node_rpc_client.rs
  dan_layer/core/src/storage/chain/chain_db_unit_of_work.rs
  dan_layer/core/src/storage/error.rs
  dan_layer/core/src/storage/mocks/chain_db.rs
  dan_layer/core/src/storage/state/state_db_unit_of_work.rs
Labels: mq-approved

#4000 fix: clippy error when not on unix
  applications/tari_app_utilities/src/identity_management.rs
Labels: mq-approved, mq-priority

#4002 fix: fix NodeIdentityHasNoAddress when creating new node identity
  applications/launchpad/backend/src/docker/workspace.rs
  applications/tari_app_utilities/src/identity_management.rs
  applications/tari_base_node/src/main.rs
  applications/tari_validator_node/src/main.rs
Labels: mq-approved, mq-failed

#4001 fix: ci build script typo
  .github/workflows/base_node_binaries.yml
Labels: mq-approved

#3997 refactor: using expect instead of assert in integration tests
  integration_tests/features/support/merge_mining_proxy_steps.js
  integration_tests/features/support/steps.js
  integration_tests/features/support/wallet_steps.js
Labels: mq-approved

#4010 fix: ignore test that timeout in github action
  comms/core/src/connectivity/test.rs
  comms/core/src/protocol/rpc/client/tests.rs
  comms/core/src/protocol/rpc/test/smoke.rs
Labels: mq-approved, mq-priority

#4003 fix(dht): saf storage uses constructs correct msg hash
  comms/dht/src/actor.rs
  comms/dht/src/dedup/dedup_cache.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/inbound/message.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/store_forward/database/stored_message.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/test_utils/store_and_forward_mock.rs
Labels: mq-approved, mq-failed

#4018 fix: add Environment cfg source and remove --create-id
  README.md
  applications/launchpad/docker_rig/quick_start.sh
  applications/tari_app_utilities/src/identity_management.rs
  applications/tari_base_node/linux/supervisord.md
  applications/tari_base_node/osx/install.sh
  applications/tari_base_node/osx/post_install.sh
  applications/tari_base_node/setup.sh
  applications/tari_base_node/src/cli.rs
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/windows/runtime/source_base_node_env.bat
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/main.rs
  buildtools/docker/start.sh
  common/src/configuration/utils.rs
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/validatorNodeProcess.js
Labels: mq-approved, mq-priority

#4019 feat(merge mining proxy): check achieved Monero difficulty before submitting to Tari basenode
  applications/tari_merge_mining_proxy/src/config.rs
  applications/tari_merge_mining_proxy/src/main.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
  base_layer/core/src/validation/header_validator.rs
  common/config/presets/merge_mining_proxy.toml
Labels: mq-approved

#4016 refactor: use match for input, output, kernel versions
  applications/test_faucet/src/main.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/src/consensus/consensus_encoding.rs
  base_layer/core/src/consensus/consensus_encoding/hash_writer.rs
  base_layer/core/src/consensus/mod.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_input_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/transaction_output_version.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: mq-approved

#4015 chore: remove #[ignored] tag from working tests
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/p2p/src/peer_seeds.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: mq-approved

#4013 docs(rfc0121): adds TransactionKernel spec
  RFC/src/RFC-0121_ConsensusEncoding.md
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
Labels: mq-approved

#4011 test: increase test coverage for transactions
  base_layer/core/src/transactions/fee.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/full_rewind_result.rs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/rewind_result.rs
  base_layer/core/src/transactions/transaction_components/transaction_input_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_output_version.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
Labels: mq-approved

#4024 test: fixes test_store_and_forward_send_tx
  base_layer/p2p/src/initialization.rs
  base_layer/wallet/tests/wallet.rs
Labels: mq-approved

#4028 fix(launchpad): fix config presets
  applications/launchpad/backend/assets/config.toml
  applications/launchpad/docker_rig/config.toml
  common/config/presets/base_node.toml
Labels: mq-approved

#4027 test(block-validators): add 0-conf double spend tests
  base_layer/core/src/test_helpers/block_spec.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/block_validators/test.rs
Labels: mq-approved

#4029 fix(dns-seeds): use correct cloudflare resolver default
  base_layer/p2p/src/config.rs
  base_layer/p2p/src/depr_transport.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/peer_seeds.rs
Labels: mq-approved

#4030 fix(dht): sets file default for DHT db
  base_layer/p2p/src/config.rs
  comms/dht/src/storage/connection.rs
Labels: mq-approved

#4025 fix: test_output_manager_sqlite_db(_encrypted)
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
Labels: mq-approved

#4026 test: unignore tx_validation_protocol_tx_becomes_mined_unconfirmed_then_confirmed
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
Labels: mq-approved

#4054 feat(tari_explorer): add total hashrate chart
  applications/tari_explorer/routes/index.js
  applications/tari_explorer/views/index.hbs
Labels: mq-approved

#4051 chore: remove unused else
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: mq-approved

#4048 refactor(base-node): use existing peer feature methods to check if is a base or client node
  applications/tari_base_node/src/commands/command/list_connections.rs
  applications/tari_base_node/src/commands/command/list_peers.rs
Labels: mq-approved

#4045 fix: makes header consensus encoding infallible
  base_layer/common_types/src/array.rs
  base_layer/core/src/blocks/block_header.rs
Labels: mq-approved

#4040 fix(wallet): do not prompt for password if given in config
  applications/tari_console_wallet/src/main.rs
Labels: mq-approved

#3135 test: cucumber saf test
  integration_tests/features/WalletRoutingMechanism.feature
Labels: mq-approved

#3995 chore: obscure grpc error response
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/config.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
Labels: mq-approved

#4052 test(covenant): improve test coverage
  base_layer/core/src/covenants/arguments.rs
  base_layer/core/src/covenants/byte_codes.rs
  base_layer/core/src/covenants/decoder.rs
  base_layer/core/src/covenants/encoder.rs
  base_layer/core/src/covenants/error.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/filters/field_eq.rs
  base_layer/core/src/covenants/filters/fields_hashed_eq.rs
  base_layer/core/src/covenants/filters/filter.rs
  base_layer/core/src/covenants/filters/identity.rs
  base_layer/core/src/covenants/macros.rs
  base_layer/core/src/covenants/token.rs
  base_layer/core/src/validation/block_validators/test.rs
Labels: mq-approved

#4037 fix: weird behaviour of dates in base node banned peers
  comms/core/src/peer_manager/peer.rs
  comms/core/src/utils/datetime.rs
Labels: mq-approved

#4050 docs: add key manager docs
  base_layer/wallet/src/key_manager_service/error.rs
  base_layer/wallet/src/key_manager_service/handle.rs
  base_layer/wallet/src/key_manager_service/initializer.rs
  base_layer/wallet/src/key_manager_service/interface.rs
  base_layer/wallet/src/key_manager_service/mock.rs
  base_layer/wallet/src/key_manager_service/storage/database/backend.rs
  base_layer/wallet/src/key_manager_service/storage/database/mod.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/key_manager_state_old.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/mod.rs
Labels: mq-approved

#4039 fix: only count base nodes in peers count in base node status
  applications/tari_base_node/src/commands/command/status.rs
Labels: mq-approved

#4063 refactor(rpc-macros): split into smaller functions (clippy)
  comms/rpc_macros/src/expand.rs
Labels: mq-approved

#4049 fix: update daily test configuration
  applications/daily_tests/automatic_recovery_test.js
  applications/daily_tests/automatic_sync_test.js
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/features/support/wallet_cli_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved
