Repository tari-project/tari, pull requests merged in 2022-01, with the labels that each got.

#3664 fix: end stale outbound queue immediately on disconnect, auto retry outbound messages
  comms/src/connection_manager/peer_connection.rs
  comms/src/protocol/messaging/outbound.rs
  comms/src/protocol/messaging/protocol.rs
Labels: mq-approved

#3673 test: fix `wait for` step
  integration_tests/features/ValidatorNode.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/support/steps.js
Labels: mq-approved, mq-failed

#3678 ci: add build step
  .github/workflows/ci.yml
Labels: mq-approved

#3460 feat!: provide a compact form of TransactionInput
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/aggregate_body.rs
  applications/tari_app_grpc/src/conversions/block.rs
  applications/tari_app_grpc/src/conversions/historical_block.rs
  applications/tari_app_grpc/src/conversions/new_block_template.rs
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_app_grpc/src/conversions/transaction_input.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_merge_mining_proxy/src/common/merge_mining.rs
  applications/tari_merge_mining_proxy/src/error.rs
  applications/tari_stratum_transcoder/src/error.rs
  applications/tari_stratum_transcoder/src/proxy.rs
  base_layer/core/src/base_node/proto/response.rs
  base_layer/core/src/base_node/proto/rpc.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/mempool/proto/mempool_request.rs
  base_layer/core/src/mempool/proto/mempool_response.rs
  base_layer/core/src/mempool/proto/state_response.rs
  base_layer/core/src/mempool/rpc/service.rs
  base_layer/core/src/mempool/rpc/test.rs
  base_layer/core/src/mempool/service/error.rs
  base_layer/core/src/mempool/service/service.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  base_layer/core/src/proto/block.rs
  base_layer/core/src/proto/mod.rs
  base_layer/core/src/proto/transaction.proto
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction/error.rs
  base_layer/core/src/transactions/transaction/mod.rs
  base_layer/core/src/transactions/transaction/transaction.rs
  base_layer/core/src/transactions/transaction/transaction_input.rs
  base_layer/core/src/transactions/transaction/transaction_output.rs
  base_layer/core/src/transactions/transaction/unblinded_output.rs
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/core/tests/block_validation.rs
  base_layer/core/tests/mempool.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/src/transaction_service/tasks/send_finalized_transaction.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service/service.rs
Labels: Consensus Change, mq-approved

#3674 chore: remove moving lock.mdb
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: mq-approved, mq-failed

#3690 ci: fix clippy warning on generated proto module
  base_layer/core/src/proto/mod.rs
Labels: mq-approved

#3685 chore: remove testnet reset todo in wallet
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
Labels: mq-approved

#3689 ci: add tor script to binaries bundle
  .github/workflows/base_node_binaries.yml
  README.md
  applications/tari_base_node/linux/runtime/linux-diag-repo.sh
  applications/tari_base_node/linux/runtime/setup_tor_service.sh
  applications/tari_base_node/linux/runtime/start_all.sh
  applications/tari_base_node/linux/runtime/start_tari_base_node.sh
  applications/tari_base_node/linux/runtime/start_tor.sh
  applications/tari_base_node/linux/setup_tor_service
  applications/tari_base_node/linux/start_all
  applications/tari_base_node/linux/start_tari_base_node
  applications/tari_base_node/linux/start_tor
  applications/tari_base_node/linux/supervisord.md
  applications/tari_base_node/osx/runtime/start_tor.sh
  applications/tari_base_node/src/main.rs
  applications/tari_base_node/ubuntu/setup_tor_service
  applications/tari_base_node/ubuntu/start_all
  applications/tari_base_node/ubuntu/start_tari_base_node
  applications/tari_base_node/ubuntu/start_tor
  applications/tari_base_node/windows/runtime/start_tor.bat
  applications/tari_console_wallet/linux/runtime/start_tari_console_wallet.sh
  applications/tari_console_wallet/linux/start_tari_console_wallet
  applications/tari_console_wallet/ubuntu/start_tari_console_wallet
  base_layer/p2p/src/initialization.rs
  buildtools/create_ubuntu_install_zip.sh
  common/src/exit_codes.rs
Labels: mq-approved

#3683 feat: add owner of method
  applications/tari_collectibles/src-tauri/migrations/2021-12-03-121212_add_721_tokens/up.sql
  applications/tari_collectibles/src-tauri/src/commands/tip721/mod.rs
  applications/tari_collectibles/src-tauri/src/schema.rs
  applications/tari_collectibles/src-tauri/src/storage/models/tip721_token_row.rs
  applications/tari_collectibles/src-tauri/src/storage/sqlite/models/tip721_token.rs
  applications/tari_collectibles/src-tauri/src/storage/sqlite/sqlite_tip721_tokens_table_gateway.rs
  applications/tari_validator_node/src/main.rs
  dan_layer/common_types/build.rs
  dan_layer/common_types/proto/tips/tip004.proto
  dan_layer/common_types/proto/tips/tip721.proto
  dan_layer/core/src/services/asset_processor.rs
  dan_layer/core/src/services/checkpoint_manager.rs
  dan_layer/core/src/templates/tip004_template.rs
  dan_layer/core/src/templates/tip721_template.rs
Labels: mq-approved

#3686 docs: add ToRistrettoPoint opcode to TariScript
  RFC/src/RFC-0202_TariScriptOpcodes.md
Labels: mq-approved

#3696 test: fix cucumber getTransactionOutputHash
  integration_tests/helpers/util.js
Labels: mq-approved

#3691 refactor(mempool)!: optimisations,excess sig index,fix weight calc
  applications/tari_app_grpc/src/conversions/aggregate_body.rs
  applications/tari_app_grpc/src/conversions/transaction.rs
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/base_node/comms_interface/mod.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/new_block_template.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/mempool/async_mempool.rs
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/priority/error.rs
  base_layer/core/src/mempool/priority/mod.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
  base_layer/core/src/mempool/service/error.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/service/initializer.rs
  base_layer/core/src/mempool/service/local_service.rs
  base_layer/core/src/mempool/service/outbound_interface.rs
  base_layer/core/src/mempool/service/service.rs
  base_layer/core/src/mempool/sync_protocol/error.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/error.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/fee.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction/transaction_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/transactions/weight.rs
  base_layer/core/src/validation/block_validators/orphan.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/core/tests/node_service.rs
  base_layer/core/tests/node_state_machine.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  comms/src/lib.rs
Labels: mq-approved

#3697 fix(comms): improve simultaneous connection handling
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/connectivity/mod.rs
  comms/src/builder/tests.rs
  comms/src/connection_manager/manager.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connectivity/connection_pool.rs
  comms/src/connectivity/manager.rs
  comms/src/connectivity/requester.rs
  comms/src/connectivity/test.rs
  comms/src/protocol/messaging/config.rs
  comms/src/protocol/messaging/error.rs
  comms/src/protocol/messaging/extension.rs
  comms/src/protocol/messaging/inbound.rs
  comms/src/protocol/messaging/mod.rs
  comms/src/protocol/messaging/outbound.rs
  comms/src/protocol/messaging/protocol.rs
  comms/src/protocol/messaging/test.rs
Labels: mq-approved

#3699 chore: change UTXO priority to Higher number = higher priority
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
Labels: mq-approved

#3694 docs: add rfc-0203 stealth addresses to the RFCs
  RFC/src/RFC-0203_StealthAddresses.md
  RFC/src/SUMMARY.md
Labels: mq-approved

#3698 ci: improve cargo test step
  .github/workflows/ci.yml
  Cargo.lock
  applications/tari_app_utilities/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_mining_node/Cargo.toml
  applications/tari_stratum_transcoder/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_stratum_ffi/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: mq-approved

#3692 test: reduce number of critical cucumber tests
  .circleci/config.yml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/mempool/service/service.rs
  common/src/configuration/global.rs
  common/src/configuration/loader.rs
  common/src/configuration/network.rs
  integration_tests/cucumber.js
  integration_tests/features/BaseNodeConnectivity.feature
  integration_tests/features/Mempool.feature
  integration_tests/features/Propagation.feature
  integration_tests/features/Reorgs.feature
  integration_tests/features/StratumTranscoder.feature
  integration_tests/features/Sync.feature
  integration_tests/features/WalletBaseNodeSwitch.feature
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletPasswordChange.feature
  integration_tests/features/WalletQuery.feature
  integration_tests/features/WalletTransactions.feature
  integration_tests/features/WalletTransfer.feature
  integration_tests/features/support/merge_mining_proxy_steps.js
  integration_tests/features/support/mining_node_steps.js
  integration_tests/features/support/node_steps.js
  integration_tests/features/support/steps.js
  integration_tests/features/support/stratum_transcoder_steps.js
  integration_tests/features/support/validator_node_steps.js
  integration_tests/features/support/wallet_cli_steps.js
  integration_tests/features/support/wallet_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/baseNodeProcess.js
  integration_tests/helpers/constants.js
  integration_tests/helpers/walletClient.js
  integration_tests/package-lock.json
Labels: mq-approved

#3701 chore: fix typo
  RFC/src/RFC-0203_StealthAddresses.md
Labels: mq-approved

#3702 v0.23.0
  Cargo.lock
  applications/launchpad/backend/Cargo.toml
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_mining_node/Cargo.toml
  applications/tari_stratum_transcoder/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/test_faucet/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_stratum_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog.md
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: mq-approved

#3700 test: fix some ignored tests
  applications/launchpad/backend/dist/.gitkeep
  base_layer/core/src/base_node/sync/rpc/tests.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/network.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/transaction/mod.rs
  base_layer/core/src/validation/transaction_validators.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  comms/src/noise/socket.rs
Labels: mq-approved

#3684 feat: update faux transaction status when imported output is validated
  applications/launchpad/package-lock.json
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/check_imported_transaction_status.rs
  base_layer/wallet/src/transaction_service/tasks/mod.rs
  base_layer/wallet/src/transaction_service/tasks/send_finalized_transaction.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3704 feat!: compact block propagation
  Cargo.lock
  applications/tari_base_node/src/bootstrap.rs
  applications/tari_base_node/src/command_handler.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/base_node/comms_interface/mod.rs
  base_layer/core/src/base_node/comms_interface/outbound_interface.rs
  base_layer/core/src/base_node/proto/request.proto
  base_layer/core/src/base_node/proto/request.rs
  base_layer/core/src/base_node/proto/response.proto
  base_layer/core/src/base_node/proto/response.rs
  base_layer/core/src/base_node/service/initializer.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/service/service_response.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/mempool/config.rs
  base_layer/core/src/mempool/consts.rs
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/proto/mempool_request.rs
  base_layer/core/src/mempool/proto/mempool_response.rs
  base_layer/core/src/mempool/proto/mod.rs
  base_layer/core/src/mempool/proto/service_request.proto
  base_layer/core/src/mempool/proto/service_response.proto
  base_layer/core/src/mempool/proto/state_response.proto
  base_layer/core/src/mempool/proto/state_response.rs
  base_layer/core/src/mempool/reorg_pool/error.rs
  base_layer/core/src/mempool/reorg_pool/mod.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/service/initializer.rs
  base_layer/core/src/mempool/service/outbound_interface.rs
  base_layer/core/src/mempool/service/response.rs
  base_layer/core/src/mempool/service/service.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
  base_layer/core/src/transactions/transaction/transaction.rs
  base_layer/core/src/transactions/transaction/transaction_output.rs
  base_layer/core/src/transactions/transaction/unblinded_output.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/mempool.rs
  base_layer/core/tests/node_comms_interface.rs
  base_layer/core/tests/node_service.rs
  comms/dht/src/connectivity/mod.rs
Labels: mq-approved

#3695 fix!: fix tx and txo validation callback bug in wallet FFI
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#3623 docs: rfc-0241 tari-monero atomic swap
  RFC/src/Glossary.md
  RFC/src/RFC-0240_AtomicSwap.md
  RFC/src/RFC-0241_AtomicSwapXMR.md
  RFC/src/SUMMARY.md
  RFC/src/assets/TXR_XMR_flow.png
  RFC/src/assets/XTR_XMR_happy.png
Labels: mq-approved

#3703 feat: enable optional libtor for macos/linux
  .circleci/config.yml
  .github/wip_integration_tests.yml
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
  .github/workflows/libwallet.yml
  Cargo.lock
  Cargo.toml
  applications/launchpad/docker_rig/base_node.Dockerfile
  applications/tari_app_utilities/src/utilities.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/main.rs
  base_layer/p2p/Cargo.toml
  buildtools/docker/base_node.Dockerfile
  common/Cargo.toml
  common/config/presets/base_node.toml
  common/config/presets/console_wallet.toml
  common/config/presets/merge_mining_proxy.toml
  common/config/presets/validator_node.toml
  common/src/configuration/global.rs
  common/src/exit_codes.rs
  common/src/lib.rs
  common/src/tor.rs
Labels: mq-approved

#3711 fix: update Weatherwax cucumber FFI tests to pass
  .circleci/config.yml
  integration_tests/cucumber.js
  integration_tests/features/WalletFFI.feature
Labels: mq-approved

#3716 test: fix critical recovery test
  comms/src/connection_manager/dialer.rs
  comms/src/connection_manager/peer_connection.rs
  comms/src/connectivity/manager.rs
  integration_tests/features/WalletRecovery.feature
  integration_tests/features/support/wallet_steps.js
  integration_tests/features/support/world.js
  integration_tests/helpers/walletProcess.js
Labels: mq-approved

#3715 chore: log r2d2 to other.log
  common/logging/log4rs_sample_base_node.yml
  common/logging/log4rs_sample_wallet.yml
  integration_tests/log4rs/base_node.yml
  integration_tests/log4rs/wallet.yml
Labels: mq-approved

#3717 fix: put libtor behind optional feature flag
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/main.rs
  common/Cargo.toml
  common/config/presets/base_node.toml
  common/config/presets/console_wallet.toml
  common/src/lib.rs
Labels: mq-approved

#3720 chore!: reinstate 2 min blocks for dibbler
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
Labels: mq-approved

#3721 docs(collectibles): fix readme
  applications/tari_collectibles/README.md
Labels: mq-approved

#3725 fix(comms): ensure signature challenge is constructed consistently
  comms/dht/src/network_discovery/error.rs
  comms/dht/src/peer_validator.rs
  comms/dht/src/proto/mod.rs
  comms/src/net_address/mutliaddresses_with_stats.rs
  comms/src/peer_manager/identity_signature.rs
  comms/src/peer_manager/migrations.rs
  comms/src/peer_manager/migrations/v6.rs
  comms/src/peer_manager/node_identity.rs
  comms/src/stream_id.rs
Labels: mq-approved

#3726 fix(collectibles): various ui fixes
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_collectibles/src-tauri/Cargo.toml
  applications/tari_collectibles/src-tauri/src/commands/asset_wallets/mod.rs
  applications/tari_collectibles/src-tauri/src/commands/assets/mod.rs
  applications/tari_collectibles/src-tauri/src/models/registered_asset_info.rs
  applications/tari_collectibles/src-tauri/src/status.rs
  applications/tari_collectibles/web-app/.gitignore
  applications/tari_collectibles/web-app/build/.gitkeep
  applications/tari_collectibles/web-app/build/asset-manifest.json
  applications/tari_collectibles/web-app/build/favicon.ico
  applications/tari_collectibles/web-app/build/index.html
  applications/tari_collectibles/web-app/build/logo192.png
  applications/tari_collectibles/web-app/build/logo512.png
  applications/tari_collectibles/web-app/build/manifest.json
  applications/tari_collectibles/web-app/build/proto/tip002.proto
  applications/tari_collectibles/web-app/build/robots.txt
  applications/tari_collectibles/web-app/build/static/css/main.41a946fd.chunk.css
  applications/tari_collectibles/web-app/build/static/css/main.41a946fd.chunk.css.map
  applications/tari_collectibles/web-app/build/static/js/2.9d96de0a.chunk.js
  applications/tari_collectibles/web-app/build/static/js/2.9d96de0a.chunk.js.LICENSE.txt
  applications/tari_collectibles/web-app/build/static/js/2.9d96de0a.chunk.js.map
  applications/tari_collectibles/web-app/build/static/js/3.4b92f274.chunk.js
  applications/tari_collectibles/web-app/build/static/js/3.4b92f274.chunk.js.map
  applications/tari_collectibles/web-app/build/static/js/main.f4daf2d0.chunk.js
  applications/tari_collectibles/web-app/build/static/js/main.f4daf2d0.chunk.js.map
  applications/tari_collectibles/web-app/build/static/js/runtime-main.20461b30.js
  applications/tari_collectibles/web-app/build/static/js/runtime-main.20461b30.js.map
  applications/tari_collectibles/web-app/public/asset-no-img.png
  applications/tari_collectibles/web-app/src/AccountDashboard.js
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_collectibles/web-app/src/Dashboard.js
Labels: mq-approved

#3723 ci: fix ios libwallet build on github actions
  .github/scripts/libwallet/build_jnilib.sh
  .github/scripts/libwallet/entrypoint.sh
  .github/scripts/libwallet/hash_libs.sh
  .github/scripts/libwallet/setup.sh
  .github/scripts/libwallet/sqlite-autoconf-3360000.tar.gz
  .github/workflows/base_node_binaries.yml
  .github/workflows/libwallet.yml
  Cargo.lock
  Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/main.rs
  base_layer/wallet_ffi/mobile_build.sh
  common/Cargo.toml
  common/src/lib.rs
  infrastructure/libtor/Cargo.toml
  infrastructure/libtor/src/lib.rs
  infrastructure/libtor/src/tor.rs
Labels: mq-approved

#3729 chore: revert libwallet WIP merge
  .github/workflows/libwallet.yml
Labels: mq-approved, mq-failed

#3724 fix(collectibles): fix setup and unlock
  applications/tari_collectibles/web-app/build/static/js/2.bde91668.chunk.js
  applications/tari_collectibles/web-app/build/static/js/2.bde91668.chunk.js.map
  applications/tari_collectibles/web-app/build/static/js/main.765d8e32.chunk.js
  applications/tari_collectibles/web-app/build/static/js/main.765d8e32.chunk.js.map
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_collectibles/web-app/src/Dashboard.js
  applications/tari_collectibles/web-app/src/Setup.js
Labels: mq-approved

#3734 feat: validator node shows its public key on startup
  applications/tari_collectibles/web-app/.gitignore
  applications/tari_collectibles/web-app/build/.gitkeep
  applications/tari_validator_node/src/main.rs
  comms/src/peer_manager/node_identity.rs
Labels: mq-approved

#3731 feat(validator): add grpc identity rpc
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/proto/validator_node.proto
  applications/tari_app_grpc/proto/wallet.proto
  applications/tari_validator_node/src/grpc/validator_node_grpc_server.rs
  applications/tari_validator_node/src/main.rs
Labels: mq-approved

#3735 fix: prevent key leaking through derive debug impl
  base_layer/core/src/transactions/transaction/unblinded_output.rs
Labels: mq-approved

#3737 ci: improve caching by splitting clippy, build and test jobs
  .github/workflows/ci.yml
Labels: mq-approved, mq-priority

#3719 chore: add latency to status line when syncing
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/hooks.rs
Labels: mq-approved

#3722 feat: add sync progress grpc
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
Labels: mq-approved

#3555 feat: add icon to mining node
  applications/tari_mining_node/build.rs
  applications/tari_mining_node/icon.ico
  applications/tari_mining_node/icon.rc
  applications/tari_mining_node/icon.res
Labels: mq-approved

#3739 chore: fix ubuntu broken built
  applications/tari_mining_node/build.rs
Labels: mq-approved

#3736 chore: add fee per gram option to coin-split command
  applications/tari_console_wallet/README.md
  applications/tari_console_wallet/src/automation/command_parser.rs
  applications/tari_console_wallet/src/automation/commands.rs
Labels: mq-approved

#3743 chore: remove old seeds and enable reorg tracking by default
  common/config/presets/base_node.toml
  common/config/presets/common.toml
Labels: mq-approved

#3746 feat: show error if IPFS upload fails
  applications/tari_collectibles/web-app/.prettierrc
  applications/tari_collectibles/web-app/src/Create.js
Labels: mq-approved

#3748 feat(console-wallet): shift+tab to go to prev tab
  applications/tari_console_wallet/src/ui/app.rs
  applications/tari_console_wallet/src/ui/mod.rs
Labels: mq-approved

#3750 feat(collectibles): add form validation error when committee not set
  applications/tari_collectibles/web-app/.eslintrc.js
  applications/tari_collectibles/web-app/.prettierrc
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/package.json
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/components/AssetCard.js
  applications/tari_collectibles/web-app/src/components/Spinner.js
Labels: mq-approved

#3754 fix: properly decrypt imported faux tx when reading from db
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
Labels: mq-approved

#3758 fix: fix attempting to validate faux transaction
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
Labels: mq-approved

#3755 chore: change daily tests to dibbler
  applications/daily_tests/automatic_recovery_test.js
  applications/daily_tests/automatic_sync_test.js
  applications/daily_tests/washing_machine.js
Labels: mq-approved

#3756 style: format with prettier (same settings as in integration tests)
  applications/tari_collectibles/web-app/.eslintrc.js
  applications/tari_collectibles/web-app/.eslintrc.json
  applications/tari_collectibles/web-app/.prettierignore
  applications/tari_collectibles/web-app/.prettierrc
  applications/tari_collectibles/web-app/src/AccountDashboard.js
  applications/tari_collectibles/web-app/src/App.js
  applications/tari_collectibles/web-app/src/AssetManager.js
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/Dashboard.js
  applications/tari_collectibles/web-app/src/Setup.js
  applications/tari_collectibles/web-app/src/binding.js
  applications/tari_collectibles/web-app/src/components/AssetCard.js
  applications/tari_collectibles/web-app/src/components/Spinner.js
  applications/tari_collectibles/web-app/src/helpers.js
  applications/tari_collectibles/web-app/src/index.js
  applications/tari_collectibles/web-app/src/reportWebVitals.js
  applications/tari_collectibles/web-app/src/setupTests.js
Labels: mq-approved

#3757 fix: fix cucumber test for standard recovery
  integration_tests/features/WalletFFI.feature
  integration_tests/features/WalletRecovery.feature
Labels: mq-approved

#3752 chore: reclassify very long log message
  base_layer/core/src/base_node/sync/rpc/service.rs
Labels: mq-approved

#3760 feat: update the available balance in console wallet
  applications/tari_console_wallet/src/ui/components/balance.rs
Labels: mq-approved

#3763 feat(explorer): better view on mempool
  applications/tari_base_node/windows/README.md
  applications/tari_explorer/routes/index.js
  applications/tari_explorer/routes/mempool.js
  applications/tari_explorer/views/index.hbs
  applications/tari_explorer/views/mempool.hbs
Labels: mq-approved

#3767 feat(ffi)!: add features, metadata_signature and sender_offset_public_key to import_utxo
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/helpers/ffi/ffiInterface.js
Labels: mq-approved

#3768 feat(ffi)!: add commitment_signature_create and destroy
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: mq-approved

#3761 fix(validators): check input metadata matches spending output
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/proto/mmr_tree.proto
  base_layer/core/src/base_node/proto/mmr_tree.rs
  base_layer/core/src/base_node/proto/mod.rs
  base_layer/core/src/base_node/proto/request.proto
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/mmr_tree.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/common/hash_writer.rs
  base_layer/core/src/consensus/consensus_encoding/bytes.rs
  base_layer/core/src/consensus/consensus_encoding/crypto.rs
  base_layer/core/src/consensus/consensus_encoding/generic.rs
  base_layer/core/src/consensus/consensus_encoding/integers.rs
  base_layer/core/src/consensus/consensus_encoding/micro_tari.rs
  base_layer/core/src/consensus/consensus_encoding/script.rs
  base_layer/core/src/consensus/consensus_encoding/vec.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/proto/tx_storage_response.proto
  base_layer/core/src/transactions/transaction/transaction_input.rs
  base_layer/core/src/validation/block_validators/async_validator.rs
  base_layer/core/src/validation/block_validators/body_only.rs
  base_layer/core/src/validation/block_validators/test.rs
  base_layer/core/src/validation/header_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/block_validation.rs
Labels: mq-approved

#3769 chore: update launchpad for dibbler
  applications/launchpad/backend/assets/config.toml
  applications/launchpad/backend/assets/log4rs.yml
  applications/launchpad/backend/assets/torrc
  applications/launchpad/backend/package.json
  applications/launchpad/backend/src/docker/models.rs
  applications/launchpad/backend/src/docker/settings.rs
  applications/launchpad/backend/src/docker/workspace.rs
  applications/launchpad/backend/tauri.conf.json
  applications/launchpad/docker_rig/README.md
  applications/launchpad/docker_rig/base_node.Dockerfile
  applications/launchpad/docker_rig/config.toml
  applications/launchpad/docker_rig/console_wallet.Dockerfile
  applications/launchpad/docker_rig/docker-compose.yml
  applications/launchpad/docker_rig/mm_proxy.Dockerfile
  applications/launchpad/docker_rig/quick_start.sh
  applications/launchpad/docker_rig/sha3_miner.Dockerfile
  applications/launchpad/gui-vue/dist/.gitkeep
  applications/launchpad/gui-vue/package-lock.json
  applications/launchpad/gui-vue/src/components/LaunchDocker.vue
  applications/launchpad/gui-vue/src/components/Settings.vue
  applications/launchpad/gui-vue/src/components/oldLauncher.vue
  applications/launchpad/gui-vue/src/store.js
  applications/launchpad/versions.txt
  applications/tari_base_node/src/bootstrap.rs
Labels: mq-approved

#3775 fix(ffi): mut pointers should be const
  base_layer/wallet_ffi/src/lib.rs
Labels: mq-approved

#3773 feat(base-node): add base node prometheus metrics
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  applications/tari_base_node/src/metrics.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/base_node/mod.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/metrics.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  infrastructure/metrics/Cargo.toml
  infrastructure/metrics/src/lib.rs
  infrastructure/metrics/src/server.rs
  infrastructure/metrics/src/server/builder.rs
  infrastructure/metrics/src/server/pull.rs
  infrastructure/metrics/src/server/push.rs
Labels: mq-approved

#3765 feat: prevent ambiguous output features in transaction protocols
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
Labels: mq-approved

#3779 fix: text explorer show sha-3 correctly + minor fixes
  applications/launchpad/gui-vue/.gitignore
  applications/launchpad/gui-vue/dist/.gitkeep
  applications/tari_explorer/.prettierrc
  applications/tari_explorer/app.js
  applications/tari_explorer/baseNodeClient.js
  applications/tari_explorer/bin/www
  applications/tari_explorer/routes/assets.js
  applications/tari_explorer/routes/blocks.js
  applications/tari_explorer/routes/index.js
  applications/tari_explorer/routes/mempool.js
  applications/tari_explorer/routes/search.js
  applications/tari_explorer/routes/validator.js
  applications/tari_explorer/validatorNodeClient.js
  applications/tari_explorer/views/assets.hbs
  applications/tari_explorer/views/blocks.hbs
  applications/tari_explorer/views/index.hbs
  applications/tari_explorer/views/layout.hbs
Labels: mq-approved

#3771 refactor(test_faucet): include create_utxo to avoid unintentionally breaking faucet utxos
  applications/test_faucet/src/main.rs
Labels: mq-approved

#3749 fix(core): fetch_header_containing_*_mmr functions now take a 0-based mmr position
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync/horizon_state_synchronization.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
Labels: mq-approved

#3780 chore: fix lint again
  applications/tari_collectibles/web-app/.eslintrc.js
  applications/tari_collectibles/web-app/package-lock.json
  applications/tari_collectibles/web-app/package.json
  applications/tari_collectibles/web-app/src/AccountDashboard.js
  applications/tari_collectibles/web-app/src/Create.js
  applications/tari_collectibles/web-app/src/NewAccount.js
Labels: mq-approved
