Repository tari-project/tari, pull requests merged in 2023-01, with the labels that each got.

#5077 feat: add remaining steps for wallet transfer
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/WalletTransfer.feature
Labels: mq-failed

#5090 feat: graceful wallet grpc shutdown
  applications/tari_console_wallet/src/wallet_modes.rs
Labels: P-acks_required

#5074 test: mempool features
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/Mempool.feature
  integration_tests/tests/utils/miner.rs
  integration_tests/tests/utils/transaction.rs
Labels: P-reviews_required, P-acks_required

#5045 fix: wallet errors
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-acks_required, mq-failed

#5086 fix: header sync start info
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: P-acks_required

#5084 fix: add const to FixedHash::zero
  base_layer/common_types/src/types/fixed_hash.rs
Labels: P-acks_required

#5043 fix: functional wallet encryption (issue #5007)
  applications/tari_console_wallet/src/recovery.rs
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/wallet/src/key_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/util/encryption.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#5096 feat: add graceful shutdown of base node
  applications/tari_base_node/src/commands/cli_loop.rs
Labels: P-acks_required

#5093 test: propagation features
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/Propagation.feature
  integration_tests/tests/utils/base_node_process.rs
  integration_tests/tests/utils/miner.rs
Labels: CR-insufficient_context, CR-too_long, P-reviews_required, P-acks_required

#5097 test: sync feature updates
  .github/workflows/ci.yml
  base_layer/core/src/consensus/consensus_constants.rs
  integration_tests/log4rs/cucumber.yml
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/Sync.feature
  integration_tests/tests/utils/base_node_process.rs
  integration_tests/tests/utils/mod.rs
  integration_tests/tests/utils/wallet_process.rs
Labels: P-acks_required

#5103 chore: set Igor vn validity period to 3 epochs for upcoming test
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-reviews_required, P-acks_required

#5104 feat: add transaction info feature cucumber steps
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/Recovery.feature
  integration_tests/tests/features/TransactionInfo.feature
Labels: CR-insufficient_context, CR-too_long, P-reviews_required, P-acks_required, mq-failed

#5110 test: update the cucumber schedule
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/build_libwallets.yml
  .github/workflows/build_libwallets_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
  rust-toolchain.toml
Labels: P-reviews_required, P-acks_required

#5119 chore: remove unused db function
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#5118 feat: increase wallet FFI error codes
  base_layer/wallet_ffi/src/error.rs
Labels: P-acks_required

#5123 fix(dht): check for empty body contents in initial msg validation
  comms/dht/src/inbound/decryption.rs
Labels: P-acks_required

#5111 feat: provide password feedback
  Cargo.lock
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/init/mod.rs
Labels: P-merge, P-acks_required

#5140 feat!: update `Argon2` parameters
  applications/tari_app_grpc/src/authentication/salted_password.rs
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
Labels: A-security, W-breaking

#5150 fix: panic on overflow in release mode
  Cargo.toml
Labels: P-controversial
