Repository tari-project/tari, pull requests merged in 2023-09, with the labels that each got.

#5710 fix: handle target difficulty conversion failure
  base_layer/core/src/consensus/consensus_manager.rs
Labels: P-acks_required

#5712 docs: chain metadata service
  docs/src/diagrams/chain_metadata_service.md
Labels: CR-insufficient_context, P-acks_required

#5646 refactor: remove rate limiter from incoming messages
  applications/minotari_node/src/bootstrap.rs
  applications/minotari_node/src/config.rs
  base_layer/contacts/examples/chat_client/src/networking.rs
  base_layer/contacts/tests/contacts_service.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/p2p/src/comms_connector/peer_message.rs
  base_layer/p2p/src/comms_connector/pubsub.rs
  base_layer/p2p/src/proto/message_type.proto
  base_layer/p2p/tests/services/liveness.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  common/config/presets/c_base_node.toml
  common/config/presets/d_console_wallet.toml
  comms/core/src/lib.rs
  comms/core/src/protocol/messaging/inbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/rate_limit.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5713 fix(sync): unify ban logic in all sync processes
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/sync/ban.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/mod.rs
  base_layer/core/src/common/mod.rs
  comms/dht/src/inbound/dht_handler/task.rs
Labels: P-reviews_required, P-acks_required

#5711 fix(dht): add SAF bans
  comms/dht/src/discovery/error.rs
  comms/dht/src/discovery/service.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/inbound/forward.rs
  comms/dht/src/inbound/message.rs
  comms/dht/src/message_signature.rs
  comms/dht/src/proto/store_forward.proto
  comms/dht/src/store_forward/error.rs
  comms/dht/src/store_forward/message.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/store_forward/service.rs
  comms/dht/src/store_forward/store.rs
  comms/dht/tests/attacks.rs
Labels: P-acks_required

#5717 fix: save dial result on error
  comms/core/src/connection_manager/dialer.rs
Labels: CR-insufficient_context, P-acks_required

#5718 chore: add original ban message to error
  comms/core/src/connection_manager/common.rs
Labels: CR-insufficient_context, P-acks_required

#5716 fix: only allow a monero header if it serializes back to the same data
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
Labels: P-acks_required

#5714 fix(dht): limit peer sync and ban on server-caused errors
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/error.rs
  comms/dht/src/config.rs
  comms/dht/src/network_discovery/config.rs
  comms/dht/src/network_discovery/discovering.rs
  comms/dht/src/network_discovery/error.rs
  comms/dht/src/network_discovery/ready.rs
  comms/dht/src/network_discovery/state_machine.rs
  comms/dht/src/network_discovery/test.rs
Labels: P-acks_required

#5721 fix(sync): remove mem::take in all syncs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: CR-insufficient_context, P-acks_required

#5730 test(dht): fix test_dht_discover_propagation flakiness
  comms/dht/tests/dht.rs
Labels: P-acks_required

#5727 fix: add-peer also dials the peer
  applications/minotari_node/src/commands/command/add_peer.rs
Labels: P-acks_required

#5729 feat: add consistent ban reason for sync
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  comms/dht/src/store_forward/saf_handler/task.rs
Labels: P-acks_required

#5728 fix(comms): greatly reduce timeouts for first byte and noise handshake
  comms/core/src/builder/comms_node.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/error.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/tests/manager.rs
  comms/core/src/noise/config.rs
  comms/core/src/noise/socket.rs
  comms/core/src/test_utils/test_node.rs
Labels: P-acks_required

#5724 fix: horizon sync
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/mmr/Cargo.toml
  base_layer/mmr/benches/smt_vs_mmr.rs
  base_layer/mmr/src/mutable_mmr.rs
  base_layer/mmr/tests/tests/mutable_mmr.rs
  comms/core/src/protocol/identity.rs
Labels: P-acks_required

#5731 fix(comms): only permit a single inbound messaging substream per peer
  base_layer/core/tests/tests/node_service.rs
  base_layer/p2p/src/initialization.rs
  comms/core/src/builder/tests.rs
  comms/core/src/protocol/messaging/extension.rs
  comms/core/src/protocol/messaging/inbound.rs
  comms/core/src/protocol/messaging/mod.rs
  comms/core/src/protocol/messaging/outbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/protocol/messaging/test.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/peer_validator.rs
  comms/dht/tests/dht.rs
  comms/dht/tests/harness.rs
Labels: P-acks_required

#5667 fix!: remove timestamp from header in proto files
  Cargo.lock
  applications/minotari_app_grpc/proto/block.proto
  applications/minotari_app_grpc/src/conversions/block_header.rs
  applications/minotari_app_grpc/src/conversions/mod.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_miner/src/miner.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block_header.rs
  base_layer/core/src/proto/mod.rs
  base_layer/core/src/proto/utils.rs
Labels: P-reviews_required, P-acks_required

#5722 fix!: remove tari prefix and only allow one mergemining tag
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-reviews_required, P-acks_required

#5733 fix: syncing from prune node
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: P-acks_required

#5734 fix: prevent access violation when running multiple vms at the same time
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: P-acks_required

#5737 chore(release): 0.52.0-pre.1
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5738 fix(p2p): enable auto join when online
  base_layer/p2p/src/config.rs
Labels: P-acks_required

#5739 fix: stuck on sync
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-reviews_required, P-acks_required

#5741 fix(comms+dht): mark peers as online inbound connection,join
  comms/core/src/connection_manager/common.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/net_address/mutliaddresses_with_stats.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/peer_validator.rs
Labels: P-acks_required

#5742 docs: fix documentation for Noise pattern update
  comms/core/src/noise/socket.rs
Labels: P-acks_required

#5740 ci(fix): add weekly dual arch docker builds with tags plus network
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#5745 docs: update diagram for listening
  docs/src/diagrams/README.md
  docs/src/diagrams/listening_state.md
  docs/src/diagrams/listing_state.md
  docs/src/diagrams/state_machine.md
Labels: CR-insufficient_context, P-acks_required

#5746 chore: remove code changes from feat_diagram branch
  base_layer/chat_ffi/build.rs
  base_layer/chat_ffi/chat.h
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
Labels: CR-insufficient_context, P-acks_required

#5651 docs: new diagrams (#5640)
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  docs/src/SUMMARY.md
  docs/src/diagrams/README.md
  docs/src/diagrams/block_sync.md
  docs/src/diagrams/chain_metadata_service.md
  docs/src/diagrams/comms/inbound_messaging.md
  docs/src/diagrams/comms/index.md
  docs/src/diagrams/comms/protocol_negotiation.md
  docs/src/diagrams/decide_next_sync.md
  docs/src/diagrams/header_sync.md
  docs/src/diagrams/horizon_sync.md
  docs/src/diagrams/incoming_blocks.md
  docs/src/diagrams/listening_state.md
  docs/src/diagrams/reconcile_block.md
  docs/src/diagrams/state_machine.md
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5747 test: improve tests code
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
Labels: CR-insufficient_context, P-acks_required

#5681 feat: chatffi simpler callbacks and managed identity and db
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/examples/chat_client/src/networking.rs
  integration_tests/src/chat_ffi.rs
Labels: P-acks_required

#5750 fix(diagrams): missing quotes for messaging diagram
  docs/src/diagrams/comms/inbound_messaging.md
Labels: P-acks_required

#5744 feat: add (de)serialize to BalancedBinaryMerkleTree
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
Labels: P-acks_required

#5748 feat(comms): allow multiple messaging protocol instances
  base_layer/p2p/src/initialization.rs
  comms/core/examples/stress/node.rs
  comms/core/examples/tor.rs
  comms/core/src/builder/tests.rs
  comms/core/src/protocol/messaging/extension.rs
  comms/core/src/protocol/messaging/mod.rs
  comms/core/src/protocol/messaging/outbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/protocol/messaging/test.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/examples/propagation/node.rs
  comms/dht/src/peer_validator.rs
  comms/dht/tests/harness.rs
Labels: P-acks_required

#5751 fix(diagrams): missing quotes for protocol negotiation diagram
  docs/src/diagrams/comms/protocol_negotiation.md
Labels: P-acks_required

#5619 feat!: add claim_public_key to sidechain features
  applications/minotari_app_grpc/proto/sidechain_types.proto
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/sidechain_feature.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/proto/sidechain_feature.proto
  base_layer/core/src/proto/sidechain_feature.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_registration.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_signature.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-acks_required

#5758 feat: up the timeout for comms
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/noise/config.rs
Labels: P-acks_required

#5762 chore: remove brackets
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: CR-insufficient_context, P-acks_required

#5757 fix: remove peer
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: P-acks_required

#5753 docs: fix header sync diagrams
  docs/src/diagrams/header_sync.md
Labels: CR-insufficient_context, P-acks_required

#5752 feat(chatffi): tor configuration
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/lib.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_ffi_steps.rs
Labels: P-acks_required

#5759 fix: potential overflow
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
Labels: P-acks_required

#5760 fix: potential sync stuck
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#5763 feat!: improve block add where many orphan chain tips existed
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/test_helpers/blockchain.rs
Labels: P-reviews_required, P-acks_required

#5768 fix: remove statement from sparse Merkle tree proofs
  base_layer/mmr/src/sparse_merkle_tree/bit_utils.rs
  base_layer/mmr/src/sparse_merkle_tree/error.rs
  base_layer/mmr/src/sparse_merkle_tree/mod.rs
  base_layer/mmr/src/sparse_merkle_tree/node.rs
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#5769 fix: handle possible underflow in smt
  base_layer/mmr/src/sparse_merkle_tree/node.rs
Labels: P-acks_required

#5770 fix: unwraps in rpc client
  comms/core/src/protocol/rpc/client/mod.rs
Labels: P-acks_required

#5766 feat(chatffi): message metadata
  Cargo.lock
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/src/client.rs
  base_layer/contacts/migrations/2023-09-05-132343_add_metadata_to_messages/down.sql
  base_layer/contacts/migrations/2023-09-05-132343_add_metadata_to_messages/up.sql
  base_layer/contacts/proto/message.proto
  base_layer/contacts/src/contacts_service/error.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/sqlite_db.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/contacts/src/contacts_service/types/message_builder.rs
  base_layer/contacts/src/contacts_service/types/mod.rs
  base_layer/contacts/src/schema.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#5773 fix: change truncate_from_bits to from_bits
  comms/core/src/peer_manager/error.rs
  comms/core/src/peer_manager/peer_identity_claim.rs
  comms/core/src/protocol/error.rs
  comms/core/src/protocol/negotiation.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/message.rs
  comms/core/src/protocol/rpc/server/chunking.rs
  comms/core/src/protocol/rpc/server/error.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/dht/src/proto/mod.rs
Labels: P-acks_required

#5774 refactor: reorganize chatffi
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/application_config.rs
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/contacts.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/chat_ffi/src/logging.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/chat_ffi/src/tansport_config.rs
  base_layer/chat_ffi/src/tari_address.rs
  base_layer/chat_ffi/src/types/chat_ffi_contacts_liveness_data.rs
  base_layer/chat_ffi/src/types/chat_ffi_message.rs
  base_layer/chat_ffi/src/types/mod.rs
  base_layer/chat_ffi/src/types/wrappers.rs
Labels: CR-too_long, P-reviews_required, P-acks_required

#5777 chore: move mempool fee check
  base_layer/core/src/mempool/mempool_storage.rs
Labels: P-acks_required

#5664 docs: add reviewers guide
  README.md
  docs/src/reviewing_guide.md
Labels: P-reviews_required, P-acks_required

#5785 chore: upgrade pgp for security
  Cargo.lock
  base_layer/p2p/Cargo.toml
Labels: P-acks_required

#5776 feat: add insert function to SMT
  base_layer/mmr/src/sparse_merkle_tree/error.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
Labels: P-merge, P-reviews_required, P-acks_required

#5786 fix: chat ffi seed peers
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/application_config.rs
  base_layer/chat_ffi/src/message_metadata.rs
  integration_tests/src/chat_ffi.rs
Labels: P-reviews_required, P-acks_required

#5789 feat: chat ffi verbose logging options
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/application_config.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/chat_ffi/src/logging.rs
  base_layer/contacts/examples/chat_client/src/config.rs
Labels: P-acks_required

#5794 fix: get rid of possible 'expect'
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  comms/core/src/message/mod.rs
Labels: P-acks_required

#5784 fix: possible exception in request_context
  base_layer/service_framework/src/lib.rs
  base_layer/service_framework/src/reply_channel.rs
Labels: P-reviews_required, P-acks_required

#5803 chore: change randomxinner pub to pub(crate)
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: P-acks_required

#5820 feat(chatffi): better message metadata parsing
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/contacts.rs
  base_layer/chat_ffi/src/error.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/chat_ffi/src/types/byte_vector.rs
  base_layer/chat_ffi/src/types/chat_ffi_message.rs
  base_layer/chat_ffi/src/types/mod.rs
  base_layer/chat_ffi/src/types/wrappers.rs
  integration_tests/src/chat_ffi.rs
Labels: P-acks_required

#5821 chore: new igor dan seeds
  common/config/presets/b_peer_seeds.toml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5823 chore: clone bmt
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
Labels: P-acks_required

#5812 fix: grpc request overflows
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: CR-insufficient_context, P-acks_required

#5814 fix: mempool panic
  base_layer/core/src/mempool/service/inbound_handlers.rs
Labels: CR-insufficient_context, P-acks_required
