Repository tari-project/tari, pull requests merged in 2023-03, with the labels that each got.

#5193 feat: merged proof
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/mmr/src/lib.rs
Labels: P-conflicts, mq-failed

#5092 fix: wallet reuse existing tor address
  applications/tari_console_wallet/src/init/mod.rs
Labels: P-controversial, P-reviews_required, P-acks_required

#5249 chore: clarify docs
  docs/src/branching_releases.md
Labels: P-acks_required

#5267 chore(version): 0.49.0-pre.4
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog.md
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5278 fix: ensures mutable MMR bitmaps are compressed
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/mmr/src/functions.rs
  base_layer/mmr/src/mutable_mmr.rs
Labels: P-acks_required

#5275 ci(fix): libwallet update to support TestNet env
  .github/workflows/build_libwallets_workflow.yml
  Cross.toml
Labels: P-merge

#5271 docs: update readme to include recommended versions
  README.md
Labels: P-merge

#5282 feat!: change signature construction to allow better HW support
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/tests/mempool.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  integration_tests/tests/utils/transaction.rs
Labels: A-base_node, W-consensus_breaking, A-wallet, P-high-risk, P-reviews_required, P-acks_required, S-high-severity, W-transaction-breaking
