Repository tari-project/tari, pull requests merged in 2023-06, with the labels that each got.

#5434 ci(fix): improve release assets listing for daig-utils
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5436 feat: update burn transaction for core key manager
  base_layer/core/src/core_key_manager/handle.rs
  base_layer/core/src/core_key_manager/interface.rs
  base_layer/core/src/core_key_manager/service.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/key_manager_output_builder.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/handle.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/service.rs
  base_layer/wallet/src/lib.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/util/one_sided.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  integration_tests/log4rs/cucumber.yml
Labels: P-acks_required

#5439 feat: core key manager and related updates
  applications/tari_app_grpc/src/conversions/block_header.rs
  applications/tari_app_grpc/src/conversions/new_block_template.rs
  base_layer/common_types/src/types/mod.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/new_blockheader_template.rs
  base_layer/core/src/core_key_manager/handle.rs
  base_layer/core/src/core_key_manager/interface.rs
  base_layer/core/src/core_key_manager/service.rs
  base_layer/core/src/proto/block.rs
  base_layer/core/src/proto/block_header.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/proto/types_impls.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction_components/key_manager_output.rs
  base_layer/core/src/transactions/transaction_components/key_manager_output_builder.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction.rs
  base_layer/core/src/transactions/transaction_components/transaction_builder.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/handle.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  integration_tests/log4rs/cucumber.yml
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#5432 fix(balanced_mp): removes some panics, adds some checks and new tests
  Cargo.lock
  base_layer/mmr/Cargo.toml
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
Labels: P-acks_required

#5440 fix(comms): validate onion3 checksum
  Cargo.lock
  comms/core/Cargo.toml
  comms/core/src/connection_manager/common.rs
Labels: P-acks_required

#5437 fix(wallet-ffi): don't block on start
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#5431 test: feature and scenario names in temp dir path
  Cargo.toml
  base_layer/contacts/examples/chat_client/src/client.rs
  common/Cargo.toml
  integration_tests/src/base_node_process.rs
  integration_tests/src/chat_client.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet_ffi.rs
  integration_tests/src/wallet_process.rs
  integration_tests/src/world.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/steps/chat_ffi_steps.rs
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#5427 chore(ci): libwallet add back changelog per multiNet
  .github/workflows/build_libwallets_workflow.yml
Labels: P-acks_required

#5413 chore(nextnet): bump randomx-rs dep and hardcode older MacOS SDK on ARM64 for randomx-rs
  .github/workflows/base_node_binaries.yml
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-merge

#5442 ci(fix): libwallet - change filename sha256sums to sha256
  .github/workflows/build_libwallets.yml
  .github/workflows/build_libwallets_workflow.yml
Labels: P-acks_required

#5401 ci(fix): replace abandoned actions-rs
  .github/workflows/audit.yml
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libwallets_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
Labels: P-reviews_required, P-acks_required

#5414 chore(stagenet): bump randomx-rs dep and hardcode older MacOS SDK on ARM64 for randomx-rs
  .github/workflows/base_node_binaries.yml
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-acks_required

#5451 chore(dev): version bump to 0.50.0-pre.3
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#5454 fix(stagenet)!: set gen block time to now
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-too_long, P-acks_required

#5456 ci(fix): libwallet debugging and remove quoting for file checks
  .github/workflows/build_libwallets_workflow.yml
Labels: P-acks_required

#5444 feat: ui for template registration in console wallet
  Cargo.lock
  applications/tari_app_grpc/src/conversions/sidechain_feature.rs
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/ui/app.rs
  applications/tari_console_wallet/src/ui/components/mod.rs
  applications/tari_console_wallet/src/ui/components/register_template_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/state/tasks.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/consensus/consensus_encoding/bytes.rs
  base_layer/core/src/covenants/test.rs
  base_layer/core/src/proto/sidechain_feature.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/sidechain_feature.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-acks_required

#5458 ci(fix): cargo install wasm-pack
  .github/workflows/ci.yml
Labels: CR-insufficient_context, P-acks_required

#5459 chore: up version
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#5455 fix(nextnet): updates the block to the in use on stagenet now
  base_layer/core/src/blocks/genesis_block.rs
Labels: P-acks_required

#5467 ci: remove duplicate test jobs on push
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
Labels: P-acks_required

#5468 chore: make CI green
  .github/workflows/audit.yml
  Cargo.lock
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/p2p/examples/gen_node_identity.rs
  base_layer/p2p/examples/gen_tor_identity.rs
  common/Cargo.toml
  comms/dht/Cargo.toml
  comms/dht/examples/memorynet_graph_network_join_multiple_seeds.rs
  comms/dht/examples/memorynet_graph_network_track_join.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/features/WalletCli.feature
  integration_tests/tests/features/WalletTransactions.feature
Labels: P-acks_required

#5470 chore: remove single test for code coverage
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: P-reviews_required, P-acks_required

#5472 fix(wallet): use correct output features for send to self
  applications/tari_console_wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-acks_required

#5473 ci(fix): for binaries build, fix metadata issues
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5474 fix(mmr): support zero sized balanced merkle proof
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
Labels: P-acks_required

#5481 perf: speed up slow test
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
Labels: P-acks_required

#5475 refactor: various fixes for clarity
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/commands/command/status.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/database.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
Labels: P-acks_required

#5457 feat: sparse merkle trees
  base_layer/mmr/Cargo.toml
  base_layer/mmr/benches/mmr.rs
  base_layer/mmr/benches/smt.rs
  base_layer/mmr/benches/smt_vs_mmr.rs
  base_layer/mmr/src/lib.rs
  base_layer/mmr/src/sparse_merkle_tree/bit_utils.rs
  base_layer/mmr/src/sparse_merkle_tree/error.rs
  base_layer/mmr/src/sparse_merkle_tree/mod.rs
  base_layer/mmr/src/sparse_merkle_tree/node.rs
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
  lints.toml
Labels: CR-too_long, P-reviews_required, P-acks_required

#5477 feat: proof of work audit part 1
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/commands/command/header_stats.rs
  applications/tari_base_node/src/grpc/hash_rate.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/target_difficulties.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/proof_of_work/difficulty.rs
  base_layer/core/src/proof_of_work/lwma_diff.rs
  base_layer/core/src/proof_of_work/target_difficulty_window.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required

#5479 ci(fix): build only bins and include in archive/packages
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
Labels: P-merge, P-acks_required

#5485 chore: version bump development to 0.51.0-pre.2
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#5484 chore: fix comment
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: P-acks_required

#5483 chore: small updates to consensus
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_base_node/src/grpc/hash_rate.rs
  applications/tari_base_node/src/recovery.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/init/mod.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/wallet_modes.rs
  base_layer/core/benches/mempool.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/consensus/mod.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/helpers/sample_blockchains.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/test_utils.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-reviews_required, P-acks_required

#5497 fix(core): compile error in wallet/FFI
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/mod.rs
Labels: P-acks_required

#5489 feat: improve recovery speed
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
Labels: P-acks_required

#5488 fix(core): remove implicit change in protocol for partial/full signatures
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-reviews_required, P-acks_required

#5486 fix(core): minor audit improvements
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/covenants/test.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/mod.rs
  base_layer/core/src/transactions/tari_amount.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction.rs
  base_layer/core/src/transactions/transaction_components/transaction_builder.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/proto/recipient_signed_message.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_metadata.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/types.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/models.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  integration_tests/src/transaction.rs
Labels: P-acks_required

#5490 fix(core/weighting): remove optional and define correct rounding for usize::MAX
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  base_layer/core/src/transactions/weight.rs
Labels: P-acks_required

#5491 chore: cosmetic (e.g. typos) changes
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/service/handle.rs
  base_layer/core/src/mempool/service/outbound_interface.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
Labels: P-reviews_required, P-acks_required

#5493 fix: overflow of target difficulty
  base_layer/core/src/proof_of_work/lwma_diff.rs
Labels: P-acks_required

#5494 fix(core/keymanager): use tokio rwlock for keymanagers
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
Labels: P-acks_required

#5496 chore(core/chain_storage): remove outdated annotation and comment
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: P-acks_required

#5500 fix(core/transactions): resolve or remove TODOs
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_signature.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
Labels: P-acks_required

#5492 chore: refactor out the shrink_hashmap
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/shrink_hashmap.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
Labels: P-acks_required

#5495 feat: proof of work audit part 2
  applications/tari_base_node/src/grpc/hash_rate.rs
  applications/tari_merge_mining_proxy/src/block_template_protocol.rs
  applications/tari_merge_mining_proxy/src/error.rs
  applications/tari_miner/src/difficulty.rs
  applications/tari_miner/src/miner.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/error.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/difficulty.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/proof_of_work/lwma_diff.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/sha3_pow.rs
  base_layer/core/src/proof_of_work/target_difficulty_window.rs
  base_layer/core/src/proto/block.rs
  base_layer/core/src/test_helpers/block_spec.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/database.rs
  base_layer/core/tests/helpers/test_blockchain.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-acks_required

#5506 fix: covenant nit picking
  base_layer/core/src/covenants/macros.rs
Labels: P-acks_required

#5503 fix(core/base_node): safe `mmr_position` cast in horizon sync
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#5499 chore: rustsec fixes or ignores
  .cargo/audit.toml
  .github/workflows/audit.yml
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  infrastructure/libtor/Cargo.toml
  integration_tests/Cargo.toml
Labels: P-acks_required

#5518 chore: version bump dev to 0.51.0-pre.3
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#5502 feat: proof of work audit part 3
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/commands/command/header_stats.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/proof_of_work/lwma_diff.rs
  base_layer/core/src/proof_of_work/target_difficulty_window.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-more_info_needed, P-reviews_required, P-acks_required

#5509 chore: speed up ci
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libwallets_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
Labels: P-acks_required

#5504 feat: proof of work audit part 4
  applications/tari_app_grpc/proto/base_node.proto
  applications/tari_app_grpc/proto/block.proto
  applications/tari_app_grpc/proto/types.proto
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/commands/command/header_stats.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_base_node/src/grpc/hash_rate.rs
  applications/tari_merge_mining_proxy/src/block_template_protocol.rs
  applications/tari_merge_mining_proxy/src/proxy.rs
  applications/tari_merge_mining_proxy/src/run_merge_miner.rs
  applications/tari_miner/src/config.rs
  applications/tari_miner/src/difficulty.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/target_difficulties.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/chain_strength_comparer.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/src/proof_of_work/monero_rx/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proof_of_work/proof_of_work_algorithm.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
  base_layer/core/src/proof_of_work/sha3x_pow.rs
  base_layer/core/src/proof_of_work/target_difficulty.rs
  base_layer/core/src/proof_of_work/target_difficulty_window.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_service.rs
  integration_tests/src/miner.rs
Labels: P-reviews_required, P-acks_required

#5521 feat: proof of work audit part 5
  applications/tari_app_grpc/proto/block.proto
  applications/tari_miner/src/config.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/historical_block.rs
  base_layer/core/src/blocks/new_block_template.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/transactions/tari_amount.rs
Labels: P-acks_required

#5522 chore(core/consensus): remove unnecessary clippy allows on FTL
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-acks_required

#5523 chore(core/consensus): consistent naming in consensus constants
  applications/tari_app_grpc/src/conversions/consensus_constants.rs
  applications/tari_base_node/src/commands/command/status.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/core/tests/tests/mempool.rs
Labels: P-acks_required

#5525 chore(core/chain_storage): duplicated timestamp calculation on orphan insertion
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: P-acks_required

#5533 fix: push test coverage even if some tests fail
  .github/workflows/coverage.yml
Labels: P-merge, P-reviews_required

#5534 fix: llvm-tools installed correctly
  .github/workflows/coverage.yml
Labels: CR-insufficient_context

#5531 fix: use correct TOML field for console wallet network address
  common/config/presets/d_console_wallet.toml
Labels: P-acks_required

#5526 feat: covenants audit
  base_layer/core/src/covenants/byte_codes.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/filters/absolute_height.rs
  base_layer/core/src/covenants/filters/and.rs
  base_layer/core/src/covenants/filters/field_eq.rs
  base_layer/core/src/covenants/filters/fields_hashed_eq.rs
  base_layer/core/src/covenants/filters/fields_preserved.rs
  base_layer/core/src/covenants/filters/filter.rs
  base_layer/core/src/covenants/filters/identity.rs
  base_layer/core/src/covenants/filters/not.rs
  base_layer/core/src/covenants/filters/or.rs
  base_layer/core/src/covenants/filters/output_hash_eq.rs
  base_layer/core/src/covenants/filters/test.rs
  base_layer/core/src/covenants/filters/xor.rs
Labels: P-acks_required

#5532 chore: update local coverage script
  scripts/code_coverage.sh
  scripts/code_coverage_comms.sh
  scripts/code_coverage_keymanager.sh
  scripts/code_coverage_storage.sh
  scripts/code_coverage_tari_core.sh
  scripts/code_coverage_wallet.sh
Labels: P-merge

#5524 feat: add documentation to covenant crate
  base_layer/core/src/covenants/arguments.rs
  base_layer/core/src/covenants/byte_codes.rs
  base_layer/core/src/covenants/context.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/covenants/decoder.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/macros.rs
  base_layer/core/src/covenants/output_set.rs
  base_layer/core/src/covenants/token.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-merge

#5535 fix(console-wallet): fix possible subtract underflow panic in list
  applications/tari_console_wallet/src/ui/components/burn_tab.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/network_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/widgets/list_state.rs
Labels: P-merge

#5530 chore: chain_backend
  base_layer/core/src/chain_storage/block_add_result.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mod.rs
  base_layer/core/tests/tests/node_service.rs
Labels: P-merge

#5540 fix: update code coverage approach
  .github/workflows/coverage.yml
  .gitignore
  scripts/code_coverage.sh
  scripts/source_coverage.sh
Labels: P-reviews_required, P-acks_required

#5538 chore: handle casts indicated by clippy lint rules
  base_layer/common_types/src/emoji.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/mmr/src/error.rs
  base_layer/mmr/src/mutable_mmr.rs
  comms/core/src/net_address/multiaddr_with_stats.rs
Labels: P-acks_required

#5548 chore: hotfix stagenet 0.49.2
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#5545 chore!: audit corrections
  base_layer/core/src/base_node/chain_metadata_service/initializer.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/transaction_components/side_chain/mod.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_signature.rs
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
Labels: P-acks_required

#5546 chore: spacing consistency in error output
  applications/tari_console_wallet/src/ui/components/log_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/transaction_service/service.rs
  common_sqlite/src/error.rs
  comms/dht/src/storage/error.rs
  integration_tests/tests/steps/wallet_ffi_steps.rs
Labels: P-merge

#5528 chore: dry up smt code
  base_layer/mmr/src/sparse_merkle_tree/bit_utils.rs
  base_layer/mmr/src/sparse_merkle_tree/node.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
Labels: P-merge, P-reviews_required, P-acks_required

#5537 feat: borsh sized serialization should be fallible
  applications/tari_base_node/src/commands/command/get_mempool_state.rs
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/ui_error.rs
  base_layer/core/benches/mempool.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/common/borsh.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/fee.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/transactions/weight.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  integration_tests/src/transaction.rs
Labels: P-reviews_required, P-acks_required

#5554 chore: remove commented lines of code
  applications/tari_console_wallet/src/ui/components/menu.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/service/mod.rs
  base_layer/core/src/chain_storage/lmdb_db/mod.rs
  base_layer/core/src/transactions/transaction_protocol/proto/recipient_signed_message.proto
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_finalized.proto
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_metadata.proto
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.proto
  base_layer/core/src/validation/header_iter.rs
  base_layer/core/src/validation/test.rs
  base_layer/wallet_ffi/build.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/core/examples/stress/service.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/message.rs
  comms/core/src/transports/tcp.rs
  comms/dht/src/store_forward/store.rs
  integration_tests/src/ffi/contacts.rs
  integration_tests/tests/steps/node_steps.rs
Labels: P-acks_required

#5559 chore: make sure mainnet values are set as placeholder
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-acks_required

#5557 chore: enable clippy::cast_possible_truncation
  applications/tari_base_node/src/commands/command/period_stats.rs
  applications/tari_base_node/src/commands/command/status.rs
  applications/tari_base_node/src/grpc/base_node_grpc_server.rs
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/tari_console_wallet/src/recovery.rs
  applications/tari_console_wallet/src/ui/components/base_node.rs
  applications/tari_console_wallet/src/ui/components/burn_tab.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/network_tab.rs
  applications/tari_console_wallet/src/ui/components/register_template_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/widgets/multi_column_list.rs
  applications/tari_console_wallet/src/ui/widgets/utilities.rs
  base_layer/contacts/src/contacts_service/storage/database.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/proof_of_work/monero_rx/fixed_array.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/weight.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/mmr/benches/smt_vs_mmr.rs
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/storage/mod.rs
  base_layer/wallet/src/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/storage/mod.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  comms/dht/src/crypt.rs
  comms/dht/src/outbound/requester.rs
  comms/dht/src/store_forward/database/stored_message.rs
  comms/dht/src/test_utils/makers.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/src/ffi/ffi_bytes.rs
  integration_tests/src/lib.rs
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_cli_steps.rs
  integration_tests/tests/steps/wallet_ffi_steps.rs
  lints.toml
Labels: P-acks_required

#5552 fix: remove optional timestamp verification bypass
  applications/tari_base_node/src/builder.rs
  applications/tari_base_node/src/recovery.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_service.rs
Labels: P-acks_required

#5551 fix: mempool fetch_highest_priority_txs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/tests/tests/mempool.rs
Labels: P-acks_required

#5560 feat: add a not before proof
  base_layer/core/src/blocks/genesis_block.rs
Labels: P-acks_required

#5549 fix: mempool should use the correct version of the consensus constant
  base_layer/core/src/mempool/mempool_storage.rs
Labels: P-reviews_required, P-acks_required

#5556 chore!: hash domain consistency
  applications/tari_console_wallet/src/ui/components/register_template_tab.rs
  base_layer/common_types/src/types/mod.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/lmdb_db/mod.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/src/common/one_sided.rs
  base_layer/core/src/consensus/consensus_encoding/hashing.rs
  base_layer/core/src/covenants/mod.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/mempool/unconfirmed_pool/mod.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/mmr/benches/mmr.rs
  base_layer/mmr/benches/smt_vs_mmr.rs
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
  base_layer/mmr/tests/support/mod.rs
  base_layer/mmr/tests/tests/with_blake512_hash.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/wallet.rs
  common/src/hashing.rs
  comms/core/src/peer_manager/hashing.rs
  comms/dht/src/dedup/mod.rs
  comms/dht/src/lib.rs
Labels: P-acks_required

#5561 chore: fix bad merge
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/mmr/tests/tests/merkle_proof.rs
  base_layer/mmr/tests/tests/mutable_mmr.rs
  base_layer/mmr/tests/tests/with_blake512_hash.rs
  base_layer/wallet_ffi/wallet.h
Labels: CR-insufficient_context, P-acks_required

#5562 chore: version bump to 0.51.0-pre.4
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required
