Repository tari-project/tari, pull requests merged in 2023-11, with the labels that each got.

#5886 feat: add config for grpc server methods
  Cargo.lock
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  applications/minotari_node/src/lib.rs
  common/config/presets/c_base_node.toml
  integration_tests/src/base_node_process.rs
Labels: P-acks_required

#5890 feat: allow multiple initial sync peers
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/sync_peer.rs
  base_layer/core/tests/tests/node_state_machine.rs
Labels: P-acks_required

#5888 chore: changes from hazop meeting code review
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
Labels: CR-insufficient_context, P-acks_required

#5883 feat: print warning for wallets in direct send only
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/lib.rs
Labels: P-acks_required

#5892 feat: apply obscure_error_if_true consistenlty
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: P-acks_required

#5895 test: make latency test deterministic
  base_layer/core/src/base_node/sync/sync_peer.rs
Labels: P-acks_required

#5894 feat: update randomx
  .github/workflows/base_node_binaries.yml
  Cargo.lock
  README.md
  base_layer/core/Cargo.toml
Labels: P-reviews_required

#5898 chore: upgrade webpki for rustsec-2023-0052
  Cargo.lock
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/dns/roots/tls.rs
Labels: CR-insufficient_context, P-acks_required

#5901 chore: new release esmeralda
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5906 feat!: completed transaction use bytes for transaction protocol (not hex string) in wallet database
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/wallet/migrations/2023-11-03-161500_transaction_protocol/down.sql
  base_layer/wallet/migrations/2023-11-03-161500_transaction_protocol/up.sql
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/tests/features/WalletCli.feature
Labels: P-acks_required

#5826 feat: add robustness to monero block extra field handling
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/mod.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required

#5899 chore: code review change
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
Labels: CR-insufficient_context, P-acks_required

#5873 feat!: add validator mmr size
  applications/minotari_app_grpc/proto/block.proto
  applications/minotari_app_grpc/src/conversions/block_header.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/sha3x_pow.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block_header.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-acks_required

#5872 fix(tariscript): protect compare and check height from underflows
  infrastructure/tari_script/src/error.rs
  infrastructure/tari_script/src/op_codes.rs
  infrastructure/tari_script/src/script.rs
Labels: P-acks_required

#5896 feat: adaptable min difficulty check
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/proof_of_work/difficulty.rs
Labels: P-reviews_required, P-acks_required

#5917 chore: new gen block time stamps
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-acks_required

#5916 fix!: lmdb flag set wrong on database
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
Labels: P-acks_required

#5918 chore: new release 0.53.0 esme
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#5920 ci(fix): disable osx arm64 build
  .github/workflows/base_node_binaries.json
Labels: P-acks_required

#5923 ci(fix): windows installer upload to s3
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5926 ci(fix): target dan for multiNet
  buildtools/multinet_envs.sh
Labels: P-acks_required

#5902 feat: add constant time comparison for grpc authentication
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/src/authentication/basic_auth.rs
  applications/minotari_app_grpc/src/authentication/server_interceptor.rs
Labels: P-reviews_required, P-acks_required

#5938 fix: fix the windows installer
  README.md
  applications/minotari_merge_mining_proxy/windows/start_minotari_merge_mining_proxy.lnk
  buildtools/windows_inno_installer.iss
Labels: P-acks_required

#5942 feat: add getheaderbyhash method to grpc-js
  clients/nodejs/base_node_grpc_client/src/index.js
Labels: P-acks_required

#5939 fix: fix the windows installer auto build
  .github/workflows/base_node_binaries.yml
  buildtools/windows_inno_installer.iss
Labels: P-acks_required

#5943 feat: remove panics from applications
  applications/minotari_console_wallet/src/main.rs
  applications/minotari_node/src/main.rs
Labels: P-acks_required

#5935 feat!: fix difficulty overflow
  Cargo.lock
  applications/minotari_app_grpc/src/conversions/chain_metadata.rs
  applications/minotari_node/src/commands/command/header_stats.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/proof_of_work/accumulated_difficulty.rs
  base_layer/core/src/proof_of_work/difficulty.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_registration.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/wallet/tests/support/base_node_service_mock.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
Labels: P-reviews_required, P-acks_required

#5928 feat(node grpc): add grpc authentication to the node
  Cargo.lock
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  applications/minotari_miner/src/config.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/cli.rs
  applications/minotari_node/src/commands/command/hash_grpc_password.rs
  applications/minotari_node/src/commands/command/mod.rs
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/lib.rs
  common/config/presets/c_base_node.toml
  common/config/presets/f_merge_mining_proxy.toml
  common/config/presets/g_miner.toml
Labels: P-acks_required

#5945 test: relax constant time assert
  applications/minotari_app_grpc/src/authentication/basic_auth.rs
Labels: P-acks_required

#5944 feat: compile out the metrics
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/mod.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  comms/core/Cargo.toml
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/mod.rs
  comms/core/src/protocol/messaging/inbound.rs
  comms/core/src/protocol/messaging/mod.rs
  comms/core/src/protocol/messaging/outbound.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/message.rs
  comms/core/src/protocol/rpc/server/metrics.rs
  comms/core/src/protocol/rpc/server/mod.rs
Labels: P-acks_required

#5934 feat: bans for bad incoming blocks
  applications/minotari_node/src/bootstrap.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/service/error.rs
  base_layer/core/src/base_node/service/initializer.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/sync/ban.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/unconfirmed_pool/error.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/tests/helpers/nodes.rs
Labels: P-acks_required

#5948 ci(fix): enable libtor for osx builds
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5950 feat: sender and receiver protocols use bytes (not hex string) in wallet database
  base_layer/wallet/migrations/2023-11-13-082000_transaction_protocols/down.sql
  base_layer/wallet/migrations/2023-11-13-082000_transaction_protocols/up.sql
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: P-acks_required

#5952 chore: simplify metrics-only blocks
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: P-acks_required

#5953 chore(ci): osx ARM64 build by removing envs
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  README.md
  applications/minotari_console_wallet/linux/runtime/start_minotari_console_wallet.sh
  applications/minotari_console_wallet/linux/start_minotari_console_wallet
  applications/minotari_console_wallet/osx/runtime/start_minotari_console_wallet.sh
  applications/minotari_console_wallet/osx/start_minotari_console_wallet
  applications/minotari_merge_mining_proxy/linux/runtime/start_minotari_merge_mining_proxy.sh
  applications/minotari_merge_mining_proxy/linux/runtime/start_xmrig.sh
  applications/minotari_merge_mining_proxy/linux/start_minotari_merge_mining_proxy
  applications/minotari_merge_mining_proxy/linux/start_xmrig
  applications/minotari_merge_mining_proxy/osx/runtime/start_minotari_merge_mining_proxy.sh
  applications/minotari_merge_mining_proxy/osx/start_minotari_merge_mining_proxy
  applications/minotari_miner/linux/runtime/start_minotari_miner.sh
  applications/minotari_miner/linux/start_minotari_miner
  applications/minotari_miner/osx/start_minotari_miner
  applications/minotari_node/README.md
  applications/minotari_node/linux/supervisord.md
  applications/minotari_node/osx-pkg/scripts/preinstall
  applications/minotari_node/osx/install.sh
  applications/minotari_node/osx/post_install.sh
  applications/minotari_node/setup.sh
  base_layer/wallet/src/config.rs
  buildtools/build-notes.md
  buildtools/create_osx_install_zip.sh
  buildtools/create_ubuntu_install_zip.sh
  buildtools/docker/base_node.Dockerfile
  buildtools/docker/start.sh
  scripts/build_dists_tarball.sh
Labels: P-reviews_required, P-acks_required

#5955 feat: warnings for untrusted urls
  applications/minotari_console_wallet/src/ui/components/register_template_tab.rs
Labels: P-acks_required

#5936 fix!: standardize gRPC authentication and mitigate DoS
  applications/minotari_app_grpc/src/authentication/basic_auth.rs
  applications/minotari_app_grpc/src/authentication/server_interceptor.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  applications/minotari_node/src/commands/command/hash_grpc_password.rs
  applications/minotari_node/src/commands/command/mod.rs
  applications/minotari_node/src/lib.rs
  common/config/presets/f_merge_mining_proxy.toml
  common/config/presets/g_miner.toml
Labels: P-acks_required

#5958 test: add gRPC interceptor authentication tests
  applications/minotari_app_grpc/src/authentication/client_interceptor.rs
Labels: P-acks_required

#5956 feat!: move kernel MMR position to `u64`
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/lmdb_db/mod.rs
Labels: P-acks_required

#5949 feat: block wallets from sending if BN connection stale
  applications/minotari_console_wallet/src/ui/components/base_node.rs
Labels: P-reviews_required, P-acks_required

#5954 chore!: remove mutable mmr
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/mmr/README.md
  base_layer/mmr/benches/smt.rs
  base_layer/mmr/benches/smt_vs_mmr.rs
  base_layer/mmr/src/functions.rs
  base_layer/mmr/src/lib.rs
  base_layer/mmr/src/merkle_checkpoint.rs
  base_layer/mmr/src/mmr_cache.rs
  base_layer/mmr/src/mutable_mmr.rs
  base_layer/mmr/src/mutable_mmr_leaf_nodes.rs
  base_layer/mmr/tests/support/mod.rs
  base_layer/mmr/tests/tests/merkle_checkpoint.rs
  base_layer/mmr/tests/tests/mmr_cache.rs
  base_layer/mmr/tests/tests/mod.rs
  base_layer/mmr/tests/tests/mutable_mmr.rs
  base_layer/mmr/tests/tests/pruned_mmr.rs
Labels: CR-insufficient_context, P-acks_required

#5963 fix: fix stable build
  applications/minotari_app_utilities/src/identity_management.rs
  applications/minotari_console_wallet/src/ui/widgets/multi_column_list.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-acks_required

#5960 feat: limit max number of addresses
  comms/core/src/net_address/mutliaddresses_with_stats.rs
Labels: P-acks_required

#5959 chore: hazop code review changes
  applications/minotari_console_wallet/src/grpc/mod.rs
  applications/minotari_console_wallet/src/ui/widgets/multi_column_list.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/metrics.rs
  base_layer/core/src/base_node/service/error.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  comms/dht/src/network_discovery/discovering.rs
Labels: P-acks_required

#5961 fix(tariscript): multisig ordered signatures and pubkeys
  infrastructure/tari_script/src/script.rs
Labels: P-reviews_required, P-acks_required

#5964 test: update and fix Merkle benchmarks
  base_layer/mmr/benches/mmr.rs
  base_layer/mmr/benches/smt.rs
Labels: P-acks_required

#5972 chore: fix lint warnings
  comms/core/src/net_address/mutliaddresses_with_stats.rs
Labels: P-acks_required

#5973 fix: update `ToRistrettoPoint` handling
  infrastructure/tari_script/src/op_codes.rs
  infrastructure/tari_script/src/script.rs
Labels: P-acks_required

#5971 chore: add versions to all hash domains
  base_layer/common_types/src/types/mod.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/wallet/src/wallet.rs
  comms/dht/src/lib.rs
Labels: P-acks_required

#5983 feat: enable revealed-value proofs
  Cargo.lock
  applications/minotari_app_grpc/proto/types.proto
  applications/minotari_app_grpc/src/conversions/consensus_constants.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_miner/src/config.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/config.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/faucets/esmeralda_faucet.json
  base_layer/core/src/blocks/faucets/igor_faucet.json
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/range_proof_type.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/wallet/tests/other/mod.rs
  common/config/presets/c_base_node.toml
  common/config/presets/f_merge_mining_proxy.toml
  common/config/presets/g_miner.toml
  integration_tests/src/miner.rs
Labels: CR-too_long, P-acks_required

#5989 test: fix cucumber merge mining tests
  integration_tests/log4rs/cucumber.yml
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/tests/features/MergeMining.feature
Labels: P-acks_required

#5988 feat!: disable console wallet grpc
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/wallet_modes.rs
  integration_tests/Cargo.toml
Labels: P-reviews_required, P-acks_required

#5987 chore(comms): update snow to 0.9.4
  Cargo.lock
  comms/core/Cargo.toml
Labels: P-acks_required

#5994 chore: despam mm proxy logs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  comms/core/src/protocol/rpc/server/mod.rs
Labels: P-acks_required

#5992 chore: migrate from `lazy_static` to `once_cell`
  Cargo.lock
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/emoji.rs
  base_layer/common_types/src/lib.rs
  base_layer/p2p/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/core/Cargo.toml
  comms/core/src/lib.rs
  comms/core/src/memsocket/mod.rs
  comms/dht/Cargo.toml
  comms/dht/examples/graphing_utilities/utilities.rs
  comms/dht/examples/memory_net/utilities.rs
Labels: P-acks_required

#5976 feat!: add aux chain support for merge mining
  Cargo.lock
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/block_template_data.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree_parameters.rs
  base_layer/core/src/proof_of_work/monero_rx/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/src/validation/difficulty_calculator.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: CR-too_long, P-acks_required
