Repository tari-project/tari, pull requests merged in 2023-10, with the labels that each got.

#5827 fix(chatffi): return and read from ptrs
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/chat_ffi/src/types/byte_vector.rs
  base_layer/chat_ffi/src/types/chat_ffi_message.rs
Labels: P-acks_required

#5830 fix: listing mode is synced
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: P-acks_required

#5775 fix: potential index out of bounds
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#5788 docs: add to reviewers guide
  docs/src/reviewing_guide.md
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5805 feat: failure of min difficulty should not add block to list of bad blocks
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: P-reviews_required, P-acks_required

#5767 chore: remove tracing
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/connection_manager/requester.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/connectivity/requester.rs
  comms/core/src/multiplexing/yamux.rs
  comms/core/src/noise/config.rs
  comms/core/src/protocol/messaging/outbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/handshake.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/core/src/socks/client.rs
Labels: P-acks_required

#5836 fix: add lock height and kernel features checks on default transactions
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-acks_required

#5835 refactor(proto)!: remove proto bytes for std bytes
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/proto/chain_metadata.proto
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/proto/wallet_rpc.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
Labels: P-acks_required

#5778 fix: potential overflow
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_node/src/commands/command/get_mempool_state.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/service/error.rs
  base_layer/core/src/blocks/new_block_template.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/unconfirmed_pool/error.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/transaction.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/database.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
Labels: P-acks_required

#5842 ci(fix): windows github action remove strawberryperl install
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5843 fix: don't ban a peer for sending a banned peer
  comms/dht/src/discovery/service.rs
  comms/dht/src/inbound/dht_handler/task.rs
  comms/dht/src/peer_validator.rs
Labels: P-acks_required

#5840 chore: correct the incoming pipeline diagram link in docs
  docs/src/diagrams/incoming_blocks.md
Labels: P-acks_required

#5844 fix: ban peer if it sends bad liveness data
  base_layer/core/src/base_node/chain_metadata_service/initializer.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  comms/core/src/lib.rs
Labels: P-reviews_required, P-acks_required

#5846 fix: fix erroneous warning message
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: P-acks_required

#5829 refactor(chatffi): remove c rep types
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/application_config.rs
  base_layer/chat_ffi/src/byte_vector.rs
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/confirmation.rs
  base_layer/chat_ffi/src/contacts.rs
  base_layer/chat_ffi/src/contacts_liveness_data.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/chat_ffi/src/messages.rs
  base_layer/chat_ffi/src/read_receipt.rs
  base_layer/chat_ffi/src/tansport_config.rs
  base_layer/chat_ffi/src/types/chat_ffi_contacts_liveness_data.rs
  base_layer/chat_ffi/src/types/chat_ffi_message.rs
  base_layer/chat_ffi/src/types/mod.rs
  base_layer/chat_ffi/src/types/wrappers.rs
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/contacts/src/chat_client/README.md
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/contacts/src/chat_client/src/config.rs
  base_layer/contacts/src/chat_client/src/database.rs
  base_layer/contacts/src/chat_client/src/lib.rs
  base_layer/contacts/src/chat_client/src/networking.rs
  integration_tests/Cargo.toml
  integration_tests/src/chat_ffi.rs
Labels: CR-too_long, P-acks_required

#5833 refactor(proto)!: remove proto timestamp wrapper types
  Cargo.lock
  applications/minotari_app_grpc/proto/network.proto
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/peer.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/proto/chain_metadata.proto
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/proto/wallet_rpc.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  comms/dht/Cargo.toml
  comms/dht/src/envelope.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/message.rs
  comms/dht/src/outbound/serialize.rs
  comms/dht/src/proto/envelope.proto
  comms/dht/src/proto/store_forward.proto
  comms/dht/src/store_forward/message.rs
  comms/dht/src/store_forward/saf_handler/task.rs
Labels: P-acks_required

#5849 feat(chatffi): get conversationalists
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/conversationalists.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/contacts/src/contacts_service/handle.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/database.rs
  base_layer/contacts/src/contacts_service/storage/sqlite_db.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/Chat.feature
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_steps.rs
Labels: P-reviews_required, P-acks_required

#5837 feat: consistent handling of edge cases for header sync
  Cargo.lock
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/sync/header_sync/mod.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/mod.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/mod.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/header_sync.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/mod.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/tests/support/comms_and_services.rs
  base_layer/wallet/tests/support/comms_and_services.rs
Labels: P-reviews_required, P-acks_required

#5866 chore: fix spend test
  base_layer/core/src/validation/block_body/test.rs
Labels: P-acks_required

#5864 chore: few small code improvements
  base_layer/core/src/base_node/sync/header_sync/mod.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/proof_of_work/target_difficulty_window.rs
Labels: P-acks_required

#5863 fix: db resize issues
  Cargo.lock
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/mmr/Cargo.toml
Labels: P-acks_required

#5876 feat: smt code review
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/proto/rpc.rs
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/base_node/rpc/sync_utxos_by_block_task.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/utxo_mined_info.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/tests/chain_storage_tests/chain_backend.rs
  base_layer/core/tests/tests/async_db.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/comms_rpc.rs
Labels: CR-insufficient_context, CR-too_long, P-acks_required

#5877 fix: recovery passphrase flow
  applications/minotari_console_wallet/src/init/mod.rs
Labels: P-acks_required

#5878 docs: clean up documentation
  README.md
Labels: P-acks_required

#5871 feat: ban bad block-sync peers
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/base_node/sync/rpc/tests.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/block_sync.rs
  base_layer/core/tests/tests/header_sync.rs
  base_layer/core/tests/tests/mod.rs
  base_layer/core/tests/tests/node_service.rs
Labels: P-acks_required

#5879 feat: enable multiple coinbase utxos
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/validation/block_body/test.rs
Labels: P-reviews_required, P-acks_required

#5882 feat: reduce timeouts and increase bans
  base_layer/core/src/base_node/sync/config.rs
  common/config/presets/c_base_node.toml
Labels: P-acks_required

#5884 feat: make prc errors ban-able for sync
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
Labels: P-acks_required
