Repository tari-project/tari, pull requests merged in 2023-04, with the labels that each got.

#5286 chore: update to use crates.io versions of tari
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/key_manager_service/mock.rs
  base_layer/wallet/src/key_manager_service/service.rs
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#5257 feat: added auxiliary callback to push base node state changes #5109
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/base_node_service/service.rs
  base_layer/wallet/tests/support/base_node_service_mock.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/ffi_basenode_state.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/tests/utils/ffi/callbacks.rs
  integration_tests/tests/utils/ffi/ffi_import.rs
  integration_tests/tests/utils/ffi/wallet.rs
Labels: P-acks_required

#5290 fix: resize transaction tab windows
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
Labels: A-wallet, P-merge

#5284 feat!: move key manager service to key_manager
  .license.ignore
  Cargo.lock
  applications/tari_console_wallet/src/automation/commands.rs
  applications/tari_console_wallet/src/automation/error.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/encryption.rs
  base_layer/common_types/src/lib.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/diesel.toml
  base_layer/key_manager/migrations/2023-03-31-130611_initial/down.sql
  base_layer/key_manager/migrations/2023-03-31-130611_initial/up.sql
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/handle.rs
  base_layer/key_manager/src/key_manager_service/initializer.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/mock.rs
  base_layer/key_manager/src/key_manager_service/mod.rs
  base_layer/key_manager/src/key_manager_service/service.rs
  base_layer/key_manager/src/key_manager_service/storage/database/backend.rs
  base_layer/key_manager/src/key_manager_service/storage/database/mod.rs
  base_layer/key_manager/src/key_manager_service/storage/mod.rs
  base_layer/key_manager/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/key_manager/src/key_manager_service/storage/sqlite_db/mod.rs
  base_layer/key_manager/src/key_manager_service/test.rs
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/schema.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/migrations/2022-08-08-134037_initial/up.sql
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/lib.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/schema.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/storage/sqlite_utilities/mod.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/types.rs
  base_layer/wallet/src/util/mod.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/key_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/wallet.rs
Labels: P-acks_required

#5292 chore(version): v0.49.0-pre.6
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog.md
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-reviews_required, P-acks_required

#5294 ci(fix): add TARI_NETWORK env support in GHA docker builds
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#5301 feat: add extended mask recovery
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-acks_required

#5304 feat: fix rpc transaction conversion
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-acks_required

#5291 feat: add network name to data path and --network flag to the miners
  applications/tari_app_utilities/src/common_cli_args.rs
  applications/tari_base_node/src/cli.rs
  applications/tari_base_node/src/lib.rs
  applications/tari_base_node/src/main.rs
  applications/tari_console_wallet/src/cli.rs
  applications/tari_console_wallet/src/lib.rs
  applications/tari_merge_mining_proxy/src/cli.rs
  applications/tari_merge_mining_proxy/src/config.rs
  applications/tari_merge_mining_proxy/src/run_merge_miner.rs
  applications/tari_miner/src/cli.rs
  applications/tari_miner/src/config.rs
  applications/tari_miner/src/main.rs
  applications/tari_miner/src/run_miner.rs
  common/src/configuration/bootstrap.rs
  integration_tests/tests/utils/merge_mining_proxy.rs
  integration_tests/tests/utils/miner.rs
  integration_tests/tests/utils/wallet_process.rs
Labels: P-acks_required

#5302 feat!: add paging to utxo stream request
  base_layer/core/src/base_node/rpc/sync_utxos_by_block_task.rs
  base_layer/core/tests/base_node_rpc.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: P-acks_required

#5296 chore: remove unused deps
  Cargo.lock
  common_sqlite/Cargo.toml
  infrastructure/libtor/Cargo.toml
Labels: P-acks_required

#5311 feat: add wallet daemon config
  common/config/presets/j_dan_wallet_daemon.toml
  common/src/configuration/utils.rs
Labels: P-acks_required

#5300 chore: add some needed traits for merge proof
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
Labels: P-acks_required

#5242 feat: add other code template types
  applications/tari_app_grpc/proto/sidechain_types.proto
  applications/tari_app_grpc/src/conversions/sidechain_feature.rs
  base_layer/core/src/proto/sidechain_feature.proto
  base_layer/core/src/proto/sidechain_feature.rs
  base_layer/core/src/transactions/transaction_components/side_chain/template_registration.rs
Labels: P-acks_required

#5314 chore(version): v0.50.0-pre.0
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-reviews_required, P-acks_required

#5316 docs: fix readme versions
  README.md
Labels: P-reviews_required, P-acks_required

#5308 test: update merge mining proxy trace log
  applications/tari_merge_mining_proxy/src/proxy.rs
Labels: P-acks_required

#5319 chore: changelogs and readmes
  changelog-development.md
  changelog-nextnet.md
  changelog-stagenet.md
  docs/src/branching_releases.md
Labels: CR-insufficient_context, CR-too_long, P-acks_required

#5333 fix: default network selection
  Cargo.lock
  common/Cargo.toml
  common/build.rs
  common/tari_features/Cargo.toml
  common/tari_features/src/resolver.rs
Labels: P-acks_required

#5329 fix: wallet ffi header file
  base_layer/wallet_ffi/src/ffi_basenode_state.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#5327 chore(release): nextnet hotfix default network selection
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/build.rs
  common/tari_features/Cargo.toml
  common/tari_features/src/resolver.rs
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5334 fix: clippy issues with config
  applications/tari_base_node/src/main.rs
Labels: P-acks_required

#5330 fix: wallet .h file for lib wallets
  base_layer/wallet_ffi/src/ffi_basenode_state.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#5323 chore(ci): add cargo machete
  .github/workflows/ci.yml
  applications/tari_console_wallet/Cargo.toml
Labels: P-acks_required

#5288 feat: improve message encryption
  applications/tari_app_grpc/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/dht/src/crypt.rs
  comms/dht/src/dht.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/decryption.rs
  comms/dht/src/lib.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/outbound/mock.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/test_utils/makers.rs
  infrastructure/tari_script/Cargo.toml
Labels: P-do_not_merge, P-acks_required

#5331 feat: add miner timeout config option
  applications/tari_miner/src/config.rs
  common/config/presets/g_miner.toml
  common/config/presets/j_dan_wallet_daemon.toml
Labels: P-acks_required

#5309 chore: update log to print display and not debug
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-acks_required

#5332 docs: update readme to show esmeralda
  Contributing.md
  README.md
Labels: P-acks_required

#5352 fix: make the first output optional in the wallet
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: P-acks_required

#5351 fix: add SECURITY.md Vulnerability Disclosure Policy
  SECURITY.md
Labels: P-merge
