Repository tari-project/tari, pull requests merged in 2023-12, with the labels that each got.

#5982 fix: display
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/new_blockheader_template.rs
  base_layer/core/src/chain_storage/block_add_result.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/covenants/arguments.rs
  base_layer/core/src/mempool/service/request.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/wallet/src/base_node_service/handle.rs
  base_layer/wallet/src/output_manager_service/handle.rs
Labels: P-acks_required

#5999 chore!: ups the min difficulty
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-acks_required

#5991 feat!: dont store entire monero coinbase transaction
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/src/conversions/transaction_input.rs
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/filters/fields_hashed_eq.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proof_of_work/proof_of_work_algorithm.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/transaction_components/output_features_version.rs
  base_layer/core/src/transactions/transaction_components/output_type.rs
  base_layer/core/src/transactions/transaction_components/range_proof_type.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_input_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel_version.rs
  base_layer/core/src/transactions/transaction_components/transaction_output_version.rs
  base_layer/core/src/validation/difficulty_calculator.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/tests/features/WalletFFI.feature
Labels: P-acks_required

#6001 chore!: new faucet for esmeralda
  base_layer/core/src/blocks/faucets/esmeralda_faucet.json
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6013 feat: audit fixes
  applications/minotari_miner/src/config.rs
  applications/minotari_miner/src/run_miner.rs
  comms/core/src/net_address/mutliaddresses_with_stats.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6018 chore: upgrade dependancies
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6008 feat!: update status
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/transaction.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/common_types/src/transaction.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6016 feat: add miner input processing
  Cargo.lock
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_app_utilities/src/lib.rs
  applications/minotari_app_utilities/src/parse_miner_input.rs
  applications/minotari_merge_mining_proxy/log4rs_sample.yml
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/error.rs
  applications/minotari_merge_mining_proxy/src/main.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  applications/minotari_miner/src/errors.rs
  applications/minotari_miner/src/main.rs
  applications/minotari_miner/src/run_miner.rs
  common/config/presets/c_base_node.toml
Labels: P-acks_required

#6004 chore: refactor current network handling and add test
  Cargo.lock
  applications/minotari_app_utilities/src/network_check.rs
  base_layer/core/src/consensus/consensus_encoding/hashing.rs
  common/Cargo.toml
  common/src/configuration/mod.rs
  common/src/configuration/network.rs
Labels: P-reviews_required, P-acks_required

#6012 chore: hazop code review
  base_layer/core/src/chain_storage/blockchain_database.rs
  integration_tests/tests/features/MergeMining.feature
  integration_tests/tests/features/WalletFFI.feature
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: CR-insufficient_context, P-acks_required

#6020 feat: hazop findings
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/common/mod.rs
Labels: CR-insufficient_context, P-acks_required

#6019 feat: make base node support 1 click mining
  applications/minotari_app_utilities/src/identity_management.rs
  applications/minotari_node/src/cli.rs
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  applications/minotari_node/src/lib.rs
  applications/minotari_node/src/main.rs
  common/config/presets/b_peer_seeds.toml
  common/config/presets/c_base_node_a.toml
  common/config/presets/c_base_node_b_mining_deny_methods.toml
  common/config/presets/c_base_node_b_non_mining_deny_methods.toml
  common/config/presets/c_base_node_c.toml
  common/src/configuration/utils.rs
Labels: P-reviews_required, P-acks_required

#6024 feat: update faucets
  base_layer/core/src/blocks/faucets/esmeralda_faucet.json
  base_layer/core/src/blocks/faucets/igor_faucet.json
  base_layer/core/src/blocks/faucets/nextnet_faucet.json
  base_layer/core/src/blocks/faucets/stagenet_faucet.json
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-acks_required

#6025 chore: new release esme 1.0.0-pre.1
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6027 chore: new release 1.0.0-pre.2
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6029 fix: remove duplicate config settings
  common/config/presets/b_peer_seeds.toml
Labels: P-acks_required

#6028 feat: update tests and constants
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-acks_required

#6033 chore: fix cucumber tests
  applications/minotari_app_utilities/src/network_check.rs
  integration_tests/tests/steps/chat_steps.rs
  integration_tests/tests/steps/node_steps.rs
Labels: P-acks_required

#6032 chore: update dependencies due to security from dependabot
  Cargo.lock
  common/Cargo.toml
  comms/dht/Cargo.toml
  comms/dht/examples/memorynet_graph_network_track_join.rs
  comms/dht/examples/memorynet_graph_network_track_propagation.rs
  infrastructure/libtor/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6035 refactor: increase trace verbosity in ffis
  base_layer/contacts/src/chat_client/src/database.rs
  base_layer/contacts/src/chat_client/src/networking.rs
  base_layer/contacts/src/contacts_service/mod.rs
  base_layer/contacts/src/contacts_service/service.rs
Labels: P-acks_required

#6034 feat: console wallet use dns seeds
  applications/minotari_console_wallet/src/init/mod.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6038 chore: new esme release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6039 chore: first RC release
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6037 chore: remove extra `
  README.md
Labels: CR-insufficient_context, P-acks_required

#6040 chore: new gen block for nextnet
  base_layer/core/src/blocks/genesis_block.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6043 feat: fix windows installer
  .github/workflows/base_node_binaries.yml
  applications/minotari_console_wallet/windows/runtime/source_minotari_console_wallet_env.bat
  applications/minotari_console_wallet/windows/runtime/start_minotari_console_wallet.bat
  applications/minotari_merge_mining_proxy/windows/runtime/source_merge_mining_proxy_env.bat
  applications/minotari_merge_mining_proxy/windows/runtime/source_xmrig_env.bat
  applications/minotari_merge_mining_proxy/windows/runtime/start_minotari_merge_mining_proxy.bat
  applications/minotari_merge_mining_proxy/windows/runtime/start_xmrig.bat
  applications/minotari_miner/windows/runtime/source_miner_env.bat
  applications/minotari_miner/windows/runtime/start_minotari_miner.bat
  applications/minotari_node/osx/install.sh
  applications/minotari_node/osx/post_install.sh
  applications/minotari_node/windows/runtime/source_minotari_node_env.bat
  applications/minotari_node/windows/runtime/start_all.bat
  applications/minotari_node/windows/runtime/start_minotari_node.bat
  buildtools/create_osx_install_zip.sh
  buildtools/create_ubuntu_install_zip.sh
  buildtools/generate_config.bat
  buildtools/generate_config.sh
  buildtools/windows_inno_installer.iss
  common/config/presets/f_merge_mining_proxy.toml
  common/xmrig_config/config_example_mainnet.json
  common/xmrig_config/config_example_mainnet_self_select.json
  common/xmrig_config/config_example_stagenet.json
  scripts/build_dists_tarball.sh
  scripts/create_bundle.sh
Labels: P-acks_required

#6042 feat: side load chat
  Cargo.lock
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/chat_ffi.rs
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
  integration_tests/src/wallet_ffi.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_ffi_steps.rs
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#6044 chore: new esme release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6045 chore(ci): improve the docker build for cross-compile
  scripts/cross_compile_tooling.sh
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#6046 chore: update nextnet gen block block
  base_layer/core/src/blocks/genesis_block.rs
Labels: CR-insufficient_context, P-acks_required

#6047 core(ci): change docker build feature - grpc
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#6048 chore: new rc release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6041 chore: update nextnet change log
  README.md
  changelog-nextnet.md
Labels: CR-insufficient_context, P-acks_required

#6049 feat: make all apps non interactive
  applications/minotari_console_wallet/src/main.rs
  applications/minotari_merge_mining_proxy/src/cli.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  applications/minotari_miner/src/cli.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/main.rs
  common/config/presets/c_base_node_a.toml
  common/config/presets/c_base_node_b_mining_deny_methods.toml
  common/config/presets/c_base_node_b_non_mining_deny_methods.toml
  common/src/configuration/utils.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
Labels: P-acks_required

#6052 fix: fix small error in config.toml
  common/config/presets/d_console_wallet.toml
Labels: P-acks_required

#6051 chore: build warning about Invalid TOML document
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
Labels: P-acks_required

#6062 chore(ci): fix s3 uploads for none tagged builds
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6060 feat: make libtor on by default for nix builds
  .github/workflows/base_node_binaries.json
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/config.rs
  base_layer/wallet/src/config.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  infrastructure/libtor/Cargo.toml
Labels: P-acks_required

#6061 chore(ci): add latest tag and multiNet label on release for docker
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#6064 chore(ci): fix windows s3 uploads
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6065 chore(ci): fix windows s3 uploads error again
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required
