Repository tari-project/tari, pull requests merged in 2023-05, with the labels that each got.

#5358 chore: update location of compiled bins in s3
  .github/workflows/base_node_binaries.yml
Labels: P-merge

#5357 feat(p2p): allow listener bind to differ from the tor forward address
  base_layer/p2p/examples/gen_tor_identity.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/transport.rs
  common/config/presets/c_base_node.toml
  comms/core/examples/stress/node.rs
  comms/core/examples/tor.rs
  comms/core/src/tor/hidden_service/builder.rs
  comms/dht/examples/propagation/node.rs
Labels: P-acks_required

#5362 chore(ci): fix ci
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
Labels: CR-insufficient_context, P-acks_required

#5360 docs: update security policy scope
  SECURITY.md
Labels: P-merge, mq-failed

#5356 fix: added missing log4rs features
  Cargo.lock
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_miner/Cargo.toml
Labels: P-acks_required

#5338 fix: remove wallet panic
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: P-acks_required

#5343 chore(release): nextnet hotfix, fix console wallet qr code
  Cargo.lock
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5366 chore: update location of compiled bins in s3 for stagenet
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5365 chore: update location of compiled bins in s3 for nextnet
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5344 chore(tests): make a few improvements on cucumber tests
  integration_tests/src/transaction.rs
  integration_tests/tests/features/BaseNodeConnectivity.feature
  integration_tests/tests/features/Mempool.feature
  integration_tests/tests/features/MergeMining.feature
  integration_tests/tests/features/Propagation.feature
  integration_tests/tests/features/Recovery.feature
  integration_tests/tests/features/Reorgs.feature
  integration_tests/tests/features/Sync.feature
  integration_tests/tests/features/WalletFFI.feature
  integration_tests/tests/features/WalletQuery.feature
  integration_tests/tests/features/WalletRecovery.feature
  integration_tests/tests/features/WalletRoutingMechanism.feature
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/features/WalletTransfer.feature
  integration_tests/tests/steps/mining_steps.rs
  integration_tests/tests/steps/mod.rs
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#5342 fix: deeplink to rfc spec
  applications/tari_console_wallet/src/ui/state/app_state.rs
Labels: P-acks_required

#5378 ci: more test workflows
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
  .github/workflows/publish_test_results_integration.yml
Labels: P-reviews_required, P-acks_required

#5379 test: remove unnecessary steps
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
  .github/workflows/publish_test_results_ci.yml
  .github/workflows/publish_test_results_integration.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5380 ci: more test results publishing
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
  .github/workflows/publish_test_results_ci.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5381 ci: more test results
  .github/workflows/publish_test_results_ci.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5374 ci(fix): libwallet build fix - remove changelog reference
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libwallets.yml
  .github/workflows/build_libwallets_workflow.yml
Labels: P-acks_required

#5387 docs: remove an outdated comment
  comms/dht/src/inbound/decryption.rs
Labels: P-merge

#5396 fix: loop on mismatched passphrase entry
  applications/tari_console_wallet/src/init/mod.rs
Labels: P-acks_required

#5384 chore(nextnet): fix cargo toml pointing toward correct tag
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-acks_required

#5383 chore: fix cargo toml pointing toward correct tag
  Cargo.lock
  applications/tari_merge_mining_proxy/src/proxy.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-acks_required

#5385 chore(stagenet): fix cargo toml pointing toward correct tag
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-acks_required

#5400 fix: use domain separation for wallet message signing
  base_layer/common_types/src/types/mod.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#5388 build(feature): add diag-utils for binary archives
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5389 build(fix): target older MacOS SDK on ARM64 for randomx-rs
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5402 test: improvements for debugging integration tests
  integration_tests/src/base_node_process.rs
  integration_tests/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet_process.rs
  integration_tests/src/world.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/BlockExplorerGRPC.feature
  integration_tests/tests/features/Propagation.feature
  integration_tests/tests/features/Reorgs.feature
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/steps/node_steps.rs
Labels: P-reviews_required, P-acks_required

#5390 feat: improved base node monitoring
  Cargo.lock
  applications/tari_console_wallet/Cargo.toml
  applications/tari_console_wallet/src/cli.rs
  applications/tari_console_wallet/src/lib.rs
  applications/tari_console_wallet/src/main.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  base_layer/wallet/src/base_node_service/config.rs
  base_layer/wallet/src/base_node_service/handle.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/base_node_service/service.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/d_console_wallet.toml
  integration_tests/src/ffi/wallet.rs
  integration_tests/src/wallet_process.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5408 feat: add small fixes, naming, clippy
  base_layer/core/src/core_key_manager/interface.rs
  base_layer/core/src/transactions/transaction_components/key_manager_output.rs
  base_layer/core/src/transactions/transaction_components/key_manager_output_builder.rs
Labels: P-acks_required

#5406 fix(comms): only set final forward address if configured to port 0
  base_layer/p2p/src/initialization.rs
  comms/core/src/builder/comms_node.rs
  comms/core/src/lib.rs
  comms/core/src/tor/control_client/types.rs
Labels: P-acks_required

#5410 feat: organize core_key_manager service
  base_layer/core/src/core_key_manager/handle.rs
  base_layer/core/src/core_key_manager/service.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/key_manager_service/handle.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/mock.rs
  base_layer/key_manager/src/key_manager_service/mod.rs
Labels: P-acks_required

#5411 feat: add metadata signature check
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-reviews_required, P-acks_required

#5417 feat: add script offset
  base_layer/core/src/core_key_manager/handle.rs
  base_layer/core/src/core_key_manager/interface.rs
  base_layer/core/src/core_key_manager/service.rs
Labels: P-acks_required

#5415 chore(ci): move multinet envs target into single script
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/build_libwallets_workflow.yml
  buildtools/multinet_envs.sh
Labels: P-acks_required

#5421 feat: update script offset
  base_layer/core/src/core_key_manager/handle.rs
  base_layer/core/src/core_key_manager/interface.rs
  base_layer/core/src/core_key_manager/service.rs
Labels: P-acks_required

#5423 chore: new Esmeralda version
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#5428 chore: merge commit development
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/build_libwallets_workflow.yml
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  buildtools/multinet_envs.sh
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  integration_tests/src/base_node_process.rs
  integration_tests/src/chat_client.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/src/lib.rs
  integration_tests/src/wallet_ffi.rs
  integration_tests/src/wallet_process.rs
  package-lock.json
Labels: P-reviews_required, P-acks_required

#5426 feat: refactor configuration for chat so ffi can create and accept a config file
  Cargo.lock
  Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/error.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/contacts/examples/chat_client/src/client.rs
  base_layer/contacts/examples/chat_client/src/config.rs
  base_layer/contacts/examples/chat_client/src/database.rs
  base_layer/contacts/examples/chat_client/src/lib.rs
  base_layer/contacts/examples/chat_client/src/networking.rs
  integration_tests/src/chat_client.rs
  integration_tests/src/chat_ffi.rs
Labels: P-acks_required

#5429 fix: fix custom wallet startup logic for console wallet
  applications/tari_console_wallet/src/init/mod.rs
Labels: P-acks_required
