Repository tari-project/tari, pull requests merged in 2023-07, with the labels that each got.

#5563 chore: fix doc test
  base_layer/core/src/covenants/macros.rs
Labels: P-acks_required

#5566 fix: sparse Merkle tree key querying
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
Labels: P-acks_required

#5555 perf: switch to local-cache for self-hosted runners
  .github/workflows/ci.yml
  .github/workflows/integration_tests.yml
Labels: P-merge

#5445 feat: peer sync limiter
  comms/core/src/peer_manager/manager.rs
  comms/core/src/peer_manager/peer_storage.rs
  comms/dht/src/network_discovery/on_connect.rs
  comms/dht/src/rpc/service.rs
  comms/dht/src/rpc/test.rs
Labels: P-merge

#5581 ci(fix): manually download checksums tool for windows
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5573 fix: update peers seed for esme
  common/config/presets/b_peer_seeds.toml
Labels: P-reviews_required, P-acks_required

#5586 chore(ci): update nightly
  applications/tari_console_wallet/src/ui/components/burn_tab.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/network_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/widgets/list_state.rs
  applications/tari_miner/src/miner.rs
  applications/tari_miner/src/stratum/controller.rs
  base_layer/common_types/src/dammsum.rs
  base_layer/common_types/src/transaction.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/lib.rs
  base_layer/mmr/src/merkle_checkpoint.rs
  base_layer/mmr/src/mmr_cache.rs
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  base_layer/p2p/src/socks_authentication.rs
  base_layer/service_framework/src/context/lazy_service.rs
  base_layer/wallet/src/output_manager_service/input_selection.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet/tests/support/utils.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  common/src/build/protobuf.rs
  common/src/configuration/common_config.rs
  common/src/configuration/multiaddr_list.rs
  common/src/configuration/string_list.rs
  comms/core/src/connectivity/connection_stats.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/connectivity/requester.rs
  comms/core/src/peer_manager/peer_query.rs
  comms/core/src/protocol/rpc/test/smoke.rs
  comms/core/src/socks/client.rs
  comms/core/src/tor/control_client/client.rs
  comms/core/src/tor/control_client/monitor.rs
  comms/core/src/transports/memory.rs
  comms/dht/src/envelope.rs
  comms/dht/src/outbound/message.rs
  infrastructure/storage/src/key_val_store/hmap_database.rs
  infrastructure/storage/src/key_val_store/key_val_store.rs
  infrastructure/storage/src/key_val_store/lmdb_database.rs
  infrastructure/storage/src/lmdb_store/store.rs
  lints.toml
  rust-toolchain.toml
Labels: P-acks_required

#5583 feat: chat ffi status callback
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/lib.rs
  integration_tests/log4rs/cucumber.yml
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_ffi_steps.rs
Labels: P-reviews_required, P-acks_required

#5592 feat: new message callback to chat-ffi
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/src/contacts_service/handle.rs
  base_layer/contacts/src/contacts_service/mod.rs
  base_layer/contacts/src/contacts_service/service.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_ffi_steps.rs
Labels: P-acks_required

#5593 chore: fix failed test
  comms/core/src/peer_manager/peer_storage.rs
Labels: P-acks_required

#5594 feat: chat message fetching pagination
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/examples/chat_client/src/client.rs
  base_layer/contacts/src/contacts_service/handle.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/database.rs
  base_layer/contacts/src/contacts_service/storage/sqlite_db.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  base_layer/contacts/tests/contacts_service.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#5591 feat: chat-ffi logging
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/lib.rs
  base_layer/contacts/examples/chat_client/src/config.rs
  integration_tests/src/chat_client.rs
  integration_tests/src/world.rs
Labels: P-reviews_required, P-acks_required

#5578 chore(Snyk): security upgrade @grpc/proto-loader from 0.5.6 to 0.7.0
  clients/nodejs/wallet_grpc_client/package.json
Labels: P-reviews_required, P-acks_required
