Repository tari-project/tari, pull requests merged in 2023-08, with the labels that each got.

#5612 chore: fixes monero build
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-acks_required

#5614 ci(fix): update Windows installer for Minotari
  .github/workflows/base_node_binaries.yml
  buildtools/windows_inno_installer.iss
Labels: P-merge

#5613 ci(fix): artifact cleanup for diag-utils
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#5579 fix: peer connection to stale nodes
  comms/core/src/peer_manager/peer.rs
  comms/dht/src/connectivity/mod.rs
Labels: P-acks_required

#5582 fix: miner delay attack
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: P-acks_required, C-audit_fix

#5599 chore(tests): large block unit tests
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required

#5606 feat: add mempool min fee
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/proto/wallet_rpc.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/mod.rs
  base_layer/core/src/mempool/proto/tx_storage_response.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/tests/tests/mempool.rs
  common/config/presets/c_base_node.toml
Labels: P-reviews_required, P-acks_required, C-audit_fix

#5603 fix: monero fork attack
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/mod.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required

#5604 fix: duplicate tari header in monero coinbase
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-reviews_required, P-acks_required, C-audit_fix

#5610 fix: check bytes remaining on monero blocks
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-reviews_required, P-acks_required, C-audit_fix

#5615 fix!: add validator mr to mining hash
  base_layer/core/src/blocks/block_header.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/proof_of_work/sha3x_pow.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-acks_required, C-audit_fix

#5608 feat: ban peer unexpected response
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: P-acks_required, C-audit_fix

#5590 fix: sorted edge case
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-controversial, P-acks_required

#5611 fix(comms): check multiple addresses for inbound liveness check
  comms/core/src/builder/comms_node.rs
  comms/core/src/connection_manager/liveness.rs
Labels: P-acks_required

#5602 fix!: limit monero hashes and force coinbase to be tx 0
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required, C-audit_fix

#5607 ci: terminate slow tests
  .config/nextest.toml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5601 feat: remove orphan validation and only validate on insertion
  Cargo.lock
  applications/minotari_node/src/bootstrap.rs
  base_layer/core/src/base_node/comms_interface/error.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/service/initializer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/tests/node_comms_interface.rs
Labels: P-acks_required, C-audit_fix

#5622 feat: remove unused wasm_key_manager
  .github/workflows/ci.yml
  Cargo.lock
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/Makefile
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
Labels: P-acks_required

#5623 ci(fix): minotari rename for docker builds
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#5626 feat: update tari crypto and utiltites
  .github/workflows/ci.yml
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/validation/error.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/Makefile
  base_layer/key_manager/src/lib.rs
  base_layer/key_manager/src/wasm.rs
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/dht/src/outbound/error.rs
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/tari_script/src/stack.rs
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, CR-too_long, P-acks_required, CR-one_job

#5627 chore(ci): match toolchain for all workflows
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
  rust-toolchain.toml
Labels: P-reviews_required, P-acks_required

#5572 fix: error out the stx protocol if the sender sends unsupported data
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-acks_required

#5617 fix: minor fixes for multiple address support
  applications/minotari_app_utilities/src/identity_management.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_node/src/commands/command/whoami.rs
  base_layer/p2p/src/initialization.rs
  comms/core/src/peer_manager/node_identity.rs
  comms/core/tests/tests/rpc.rs
  comms/core/tests/tests/rpc_stress.rs
  comms/core/tests/tests/substream_stress.rs
Labels: P-acks_required

#5605 feat!: add a nextnet genesis block faucet for nextnet
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
  base_layer/common_types/src/dammsum.rs
  base_layer/common_types/src/transaction.rs
  base_layer/core/src/blocks/faucets/nextnet_faucet.json
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/key_manager/Makefile
  base_layer/key_manager/src/lib.rs
  base_layer/mmr/src/merkle_checkpoint.rs
  base_layer/p2p/src/socks_authentication.rs
  base_layer/service_framework/src/context/lazy_service.rs
  base_layer/wallet/src/output_manager_service/input_selection.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet_ffi/README.md
  base_layer/wallet_ffi/src/lib.rs
  buildtools/docker/base_node.Dockerfile
  common/src/configuration/multiaddr_list.rs
  common/src/configuration/string_list.rs
  comms/core/src/connectivity/connection_stats.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/connectivity/requester.rs
  comms/core/src/peer_manager/peer_query.rs
  comms/core/src/protocol/rpc/test/smoke.rs
  comms/core/src/socks/client.rs
  comms/core/src/tor/control_client/client.rs
  comms/core/src/transports/memory.rs
  comms/dht/src/envelope.rs
  comms/dht/src/inbound/forward.rs
  comms/dht/src/outbound/message.rs
  infrastructure/storage/src/key_val_store/key_val_store.rs
  infrastructure/storage/src/lmdb_store/store.rs
  rust-toolchain.toml
  scripts/test_in_docker.sh
Labels: P-acks_required

#5631 chore: fix ci nextnet
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
  applications/tari_console_wallet/src/ui/components/burn_tab.rs
  applications/tari_console_wallet/src/ui/components/contacts_tab.rs
  applications/tari_console_wallet/src/ui/components/network_tab.rs
  applications/tari_console_wallet/src/ui/components/send_tab.rs
  applications/tari_console_wallet/src/ui/components/transactions_tab.rs
  applications/tari_console_wallet/src/ui/state/app_state.rs
  applications/tari_console_wallet/src/ui/widgets/list_state.rs
  applications/tari_miner/src/miner.rs
  applications/tari_miner/src/stratum/controller.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/key_manager/Makefile
  base_layer/mmr/src/mmr_cache.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/README.md
  base_layer/wallet_ffi/src/callback_handler.rs
  buildtools/docker/base_node.Dockerfile
  common/src/build/protobuf.rs
  common/src/configuration/common_config.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/tor/control_client/monitor.rs
  infrastructure/storage/src/key_val_store/hmap_database.rs
  infrastructure/storage/src/key_val_store/lmdb_database.rs
  lints.toml
  rust-toolchain.toml
  scripts/test_in_docker.sh
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5624 fix(core): always pass the correct timestamp window to header validatior
  applications/minotari_app_grpc/src/conversions/historical_block.rs
  applications/minotari_node/src/commands/command/period_stats.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/blocks/historical_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/common/rolling_vec.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/test.rs
Labels: P-acks_required

#5635 chore: fix windows checksum for stagenet
  .github/workflows/base_node_binaries.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5639 chore: release stagenet 0.50.0-hotfix.1
  Cargo.lock
  README.md
  applications/tari_app_grpc/Cargo.toml
  applications/tari_app_utilities/Cargo.toml
  applications/tari_base_node/Cargo.toml
  applications/tari_console_wallet/Cargo.toml
  applications/tari_merge_mining_proxy/Cargo.toml
  applications/tari_miner/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#5641 chore: version bump dev to 0.52.0-pre.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-reviews_required, P-acks_required

#5637 chore: release 0.51.0-rc.1 and fix libwallet build(nextnet)
  .github/workflows/build_libwallets_workflow.yml
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/examples/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#5645 test: fixed cucumber test
  integration_tests/tests/steps/node_steps.rs
Labels: P-acks_required

#5643 refactor: change atomics to use SeqCst
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/mempool/sync_protocol/mod.rs
  base_layer/service_framework/src/stack.rs
  base_layer/service_framework/src/tower/service_ext.rs
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/protocol/rpc/test/greeting_service.rs
  comms/core/src/test_utils/mocks/peer_connection.rs
  comms/dht/src/network_discovery/state_machine.rs
Labels: P-merge

#5638 chore: fix lib wallet build(dev)
  .github/workflows/build_libwallets_workflow.yml
Labels: CR-insufficient_context, P-reviews_required

#5649 ci(fix): android build minotari_chat_ffi - sqlite
  Cargo.lock
  base_layer/chat_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/src/chat_ffi.rs
Labels: P-acks_required

#5640 docs: new diagrams
  docs/src/SUMMARY.md
  docs/src/diagrams/common_message_pipeline.md
  docs/src/diagrams/incoming_blocks.md
  docs/src/diagrams/index.md
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5659 fix: make sure all needed libs are required for chatffi
  base_layer/chat_ffi/build.rs
  base_layer/chat_ffi/chat.h
Labels: P-acks_required

#5662 chore: update security.md
  SECURITY.md
Labels: P-merge

#5678 docs: new diagrams (#5640)
  docs/src/diagrams/common_message_pipeline.md
  docs/src/diagrams/comms/inbound_messaging.md
  docs/src/diagrams/comms/index.md
  docs/src/diagrams/comms/protocol_negotiation.md
  docs/src/diagrams/index.md
Labels: P-acks_required

#5682 docs: add block sync diagram
  docs/src/diagrams/block_sync.md
Labels: P-acks_required

#5680 docs: diagrams reconcile block
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  docs/src/diagrams/reconcile_block.md
Labels: P-acks_required

#5676 chore: remove dead code
  infrastructure/tari_script/src/lib.rs
  infrastructure/tari_script/src/script.rs
Labels: CR-insufficient_context, P-acks_required

#5684 chore: remove deadcode
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
Labels: CR-insufficient_context, P-acks_required

#5665 chore: update randomx-rs
  Cargo.lock
  base_layer/core/Cargo.toml
Labels: P-acks_required

#5668 refactor: remove unused code
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
Labels: CR-insufficient_context, P-acks_required

#5677 ci(fix): add chat_ffi to build and release
  .github/workflows/build_libffis.json
  .github/workflows/build_libffis.yml
  .github/workflows/build_libwallets.yml
  .github/workflows/build_libwallets_workflow.yml
  base_layer/core/Cargo.toml
  base_layer/p2p/Cargo.toml
Labels: P-acks_required

#5653 feat: change default script to PushPubKey
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/chain_storage_tests/chain_backend.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/utils.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  infrastructure/tari_script/src/script.rs
Labels: P-reviews_required, P-acks_required

#5687 docs: add horizon sync diagram
  docs/src/diagrams/horizon_sync.md
Labels: P-acks_required

#5690 feat: updates to block_sync diagram
  docs/src/diagrams/block_sync.md
Labels: P-acks_required

#5658 fix: memory overflow panic
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  infrastructure/tari_script/src/script.rs
  infrastructure/tari_script/src/stack.rs
Labels: P-acks_required, C-audit_fix

#5688 fix: potential u64 overflow panic
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
Labels: P-acks_required

#5686 fix: remove potential u64 overflow panic
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: CR-insufficient_context, P-acks_required

#5693 fix: ban peers if they send a bad protobuf message
  Cargo.lock
  base_layer/contacts/src/contacts_service/error.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/service/error.rs
  base_layer/core/src/base_node/service/initializer.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/p2p/src/services/liveness/error.rs
  base_layer/p2p/src/services/liveness/mod.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/src/services/utils.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/support/comms_and_services.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: P-reviews_required, P-acks_required

#5670 test: add bitflag test for kernelfeatures
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/transactions/transaction_components/kernel_features.rs
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
Labels: P-acks_required

#5697 feat: remove inherent iterator panic
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/iterators/chunk.rs
Labels: P-acks_required

#5655 feat: cleanup errors
  base_layer/core/src/base_node/state_machine_service/states/header_sync.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/error.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/proof_of_work/error.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/kernel_builder.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_builder.rs
  base_layer/core/src/transactions/transaction_components/transaction_input.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/header/header_full_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/core/src/validation/transaction/transaction_internal_validator.rs
  base_layer/core/tests/tests/block_validation.rs
Labels: P-acks_required

#5696 fix(comms)!: use noise XX handshake pattern for improved privacy
  Cargo.lock
  comms/core/Cargo.toml
  comms/core/src/noise/config.rs
  comms/core/src/noise/crypto_resolver.rs
  comms/core/src/noise/mod.rs
  comms/core/src/noise/socket.rs
Labels: P-acks_required

#5704 fix(horizon_sync): check for leftover unpruned outputs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#5703 fix(horizon_sync): check max number of kernels/utxos from peer
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#5701 fix: handle out of sync errors when returning mempool transactions
  base_layer/core/src/mempool/error.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
Labels: P-acks_required

#5705 fix: better timeout for lagging
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/p2p/src/services/liveness/service.rs
  common/config/presets/c_base_node.toml
Labels: P-acks_required

#5706 fix: addition overflow when coinbase + fees is too high
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/validation/block_body/block_body_internal_validator.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/helpers.rs
Labels: P-acks_required

#5691 feat: improve block sync error handling
  base_layer/core/src/base_node/service/error.rs
  base_layer/core/src/base_node/state_machine_service/states/block_sync.rs
  base_layer/core/src/base_node/sync/block_sync/error.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/src/validation/error.rs
Labels: P-acks_required

#5698 feat: update genesis blocks
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#5707 chore: fix bad merge
  base_layer/core/src/validation/error.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#5679 fix(comms): timeout and ban for bad behaviour in protocol negotation
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/protocol/error.rs
  comms/dht/examples/memory_net/utilities.rs
Labels: P-acks_required
