Repository tari-project/tari, pull requests merged in 2024-01, with the labels that each got.

#6066 chore(ci): fix windows envs with bash shell for s3 uploads
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6068 refactor(common): allow custom default configs
  common/src/configuration/utils.rs
Labels: P-acks_required

#6069 chore(ci): ffi extend to build for none mobile platforms
  .github/workflows/build_libffis.json
  .github/workflows/build_libffis.yml
Labels: P-acks_required

#6072 docs: update disclosure policy
  SECURITY.md
  meta/img/hacker1.webp
Labels: C-documentation, P-acks_required

#6075 feat: add tari address as valid string for discovering a peer
  applications/minotari_app_utilities/src/utilities.rs
  applications/minotari_console_wallet/README.md
Labels: P-acks_required

#6067 chore: upgrade tonic and prost
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/build.rs
  applications/minotari_app_grpc/src/lib.rs
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/proto/mod.rs
  base_layer/wallet/Cargo.toml
  clients/rust/wallet_grpc_client/Cargo.toml
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/core/src/proto/mod.rs
  comms/dht/Cargo.toml
  comms/dht/src/proto/mod.rs
  comms/rpc_macros/Cargo.toml
  comms/rpc_macros/tests/macro.rs
  integration_tests/Cargo.toml
Labels: P-acks_required

#6077 chore(fix): include protobuf during build
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libffis.yml
  README.md
Labels: P-acks_required

#6083 chore(fix): ci - ffis android - add protobuf for cross-compile
  .github/workflows/build_libffis.yml
  Cross.toml
Labels: P-acks_required

#6074 fix: wallet coinbases not validated correctly
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/tests/features/Sync.feature
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6079 fix: tms validation correctly updating
  applications/minotari_app_grpc/proto/block.proto
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/transaction.rs
  base_layer/common_types/src/transaction.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  integration_tests/tests/features/Sync.feature
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6084 chore: new esme release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6085 chore: new nextnet release
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6082 feat: add search kernels method to nodejs client
  clients/nodejs/base_node_grpc_client/src/index.js
Labels: P-acks_required

#6086 chore: update change log
  changelog-nextnet.md
Labels: CR-insufficient_context, P-acks_required

#6088 feat: update codeowners
  CODEOWNERS
Labels: P-merge

#6089 feat: update codeowners (stagenet)
  CODEOWNERS
Labels: P-merge, P-reviews_required

#6094 chore(fix): ci - move s3 uploads to only on release
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6098 chore: update monero to latest release
  Cargo.lock
  applications/minotari_merge_mining_proxy/Cargo.toml
  base_layer/core/Cargo.toml
Labels: P-acks_required

#6096 feat: prevent runtime error with compact error input
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: P-acks_required

#6100 chore: merge development to feature-dan2
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/proto/sidechain_types.proto
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/sidechain_feature.rs
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_app_utilities/src/identity_management.rs
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/proto/sidechain_feature.proto
  base_layer/core/src/proto/sidechain_feature.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_registration.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_signature.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/Cargo.toml
  buildtools/multinet_envs.sh
  common/Cargo.toml
  common/config/presets/b_peer_seeds.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#6105 feat: new release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6106 chore: new rc release
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6107 chore: adit warnings
  .cargo/audit.toml
Labels: CR-insufficient_context, P-acks_required

#6095 chore: rename chain metadata fields to be consistent with its meaning
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_app_grpc/src/conversions/chain_metadata.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/components/base_node.rs
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/commands/command/check_db.rs
  applications/minotari_node/src/commands/command/list_connections.rs
  applications/minotari_node/src/commands/command/list_peers.rs
  applications/minotari_node/src/commands/command/list_validator_nodes.rs
  applications/minotari_node/src/commands/command/period_stats.rs
  applications/minotari_node/src/commands/command/status.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  applications/minotari_node/src/grpc/blocks.rs
  applications/minotari_node/src/recovery.rs
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/chain_metadata_service/service.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/proto/chain_metadata.proto
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/core/src/base_node/proto/wallet_rpc.proto
  base_layer/core/src/base_node/proto/wallet_rpc.rs
  base_layer/core/src/base_node/rpc/service.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/validation/block_body/block_body_full_validator.rs
  base_layer/core/src/validation/transaction/transaction_chain_validator.rs
  base_layer/core/src/validation/transaction/transaction_internal_validator.rs
  base_layer/core/tests/chain_storage_tests/chain_storage.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/support/comms_rpc.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/ffi_basenode_state.rs
  base_layer/wallet_ffi/wallet.h
  clients/nodejs/base_node_grpc_client/src/index.test.js
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6006 feat!: fix horizon sync after smt upgrade
  applications/minotari_node/src/commands/command/check_db.rs
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/proto/rpc.proto
  base_layer/core/src/base_node/state_machine_service/states/horizon_state_sync.rs
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/base_node/sync/sync_peer.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/block_sync.rs
  base_layer/core/tests/tests/header_sync.rs
  base_layer/core/tests/tests/horizon_sync.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/mod.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
Labels: CR-too_long, P-acks_required
