Repository tari-project/tari, pull requests merged in 2024-05, with the labels that each got.

#6315 ci(fix): update osx pkg notarization from deprecated altool
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6316 feat: add check to verify mempool state
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
Labels: P-acks_required

#6317 fix(comms/core): upgrade to yamux 0.13
  Cargo.lock
  comms/core/Cargo.toml
  comms/core/src/connection_manager/listener.rs
  comms/core/src/multiplexing/yamux.rs
  comms/core/src/protocol/messaging/inbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/protocol/messaging/test.rs
  comms/core/src/protocol/rpc/test/smoke.rs
  comms/core/src/test_utils/mocks/peer_connection.rs
  comms/core/src/test_utils/transport.rs
Labels: P-reviews_required, P-acks_required

#6319 chore: prevent spam logs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: P-acks_required

#6314 feat: add sent at timestamp to chat messages
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/message.rs
  base_layer/contacts/migrations/2024-04-30-155100_add_sent_timestamp/down.sql
  base_layer/contacts/migrations/2024-04-30-155100_add_sent_timestamp/up.sql
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/contacts/src/schema.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6321 fix: change mmproxy to select new monerod on error
  applications/minotari_merge_mining_proxy/src/proxy.rs
Labels: P-acks_required

#6322 chore: minor cleanup to `CipherSeed`
  base_layer/key_manager/src/cipher_seed.rs
Labels: P-acks_required

#6323 chore: update zeroizing
  comms/core/src/tor/control_client/types.rs
Labels: P-reviews_required, P-acks_required

#6324 ci(fix): cosmetic - update binaries build workflow to be more, tbn to ts
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
Labels: P-acks_required

#6325 chore: new release testnet v1.0.0-pre.13
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6330 chore: refactor key manager hasher
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
Labels: P-acks_required

#6326 ci(fix): macOS add workflow to assemble macOS universal binaries
  .github/workflows/build_binaries.yml
Labels: P-acks_required

#6329 feat!: update key manager hasher labels
  base_layer/key_manager/src/cipher_seed.rs
  base_layer/key_manager/src/key_manager.rs
  base_layer/key_manager/src/lib.rs
Labels: P-acks_required

#6307 feat: limit wallet base node peer outbound connections
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/chat_ffi/src/byte_vector.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/transactions/crypto_factories.rs
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/mmr/src/backend.rs
  base_layer/mmr/src/sparse_merkle_tree/proofs.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/src/transport.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/core/src/builder/mod.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/error.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/connection_manager/tests/listener_dialer.rs
  comms/core/src/connectivity/config.rs
  comms/core/src/connectivity/connection_pool.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/connectivity/requester.rs
  comms/core/src/connectivity/test.rs
  comms/core/src/lib.rs
  comms/core/src/net_address/multiaddr_with_stats.rs
  comms/core/src/net_address/mutliaddresses_with_stats.rs
  comms/core/src/peer_manager/peer.rs
  comms/core/src/peer_manager/peer_query.rs
  comms/core/src/protocol/rpc/client/tests.rs
  comms/core/src/test_utils/mocks/connectivity_manager.rs
  comms/core/src/test_utils/mocks/peer_connection.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/connectivity/test.rs
  comms/dht/src/network_discovery/state_machine.rs
  comms/dht/src/store_forward/error.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/src/store_forward/service.rs
Labels: P-acks_required

#6335 fix: new monero release for mr support in monero
  Cargo.lock
  applications/minotari_merge_mining_proxy/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-acks_required

#6333 ci(fix): macOS add workflow steps for universal pkg
  .github/workflows/build_binaries.yml
  .github/workflows/build_libffis.yml
Labels: P-acks_required

#6336 fix!: monero merkle tree params
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/proof_of_work/monero_rx/error.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree_parameters.rs
Labels: P-acks_required

#6337 chore: refactor checksum mask initialization
  base_layer/common_types/src/dammsum.rs
Labels: P-acks_required

#6341 feat: fix base node console display
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
Labels: P-acks_required

#6343 feat: improve initial connection times
  comms/core/src/connectivity/manager.rs
  comms/dht/src/connectivity/mod.rs
Labels: P-acks_required

#6344 feat: generate script challenge on the ledger
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  applications/minotari_ledger_wallet/wallet/src/utils.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  hashing/Cargo.toml
  hashing/src/borsh_hasher.rs
  hashing/src/domains.rs
  hashing/src/lib.rs
Labels: P-acks_required

#6345 feat: remove chunking from rpc
  comms/core/src/protocol/messaging/inbound.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/message.rs
  comms/core/src/protocol/rpc/mod.rs
  comms/core/src/protocol/rpc/server/chunking.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/core/src/protocol/rpc/test/smoke.rs
Labels: P-acks_required

#6352 ci(fix): improve cross-compile, add x86_64 target from aarch64
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_libffis.yml
  Cross.toml
  applications/minotari_miner/linux/start_minotari_miner
  applications/minotari_miner/osx/start_minotari_miner
  scripts/cross_compile_ubuntu_18-pre-build.sh
Labels: P-acks_required

#6355 feat: add default message tag
  comms/dht/src/outbound/message_params.rs
Labels: P-acks_required

#6354 feat: chat ffi find by message
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/message.rs
  base_layer/common_types/src/wallet_types.rs
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/contacts/src/contacts_service/handle.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/database.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/features/Chat.feature
  integration_tests/tests/features/ChatFFI.feature
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#6357 feat: remove wallet type from config
  applications/minotari_console_wallet/src/init/mod.rs
  base_layer/wallet/src/config.rs
Labels: P-reviews_required, P-acks_required

#6358 feat: split message to have dedicated to and from fields
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/callback_handler.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/contacts/migrations/2024-05-27-145200_add_from_to_fields/up.sql
  base_layer/contacts/proto/message.proto
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/contacts/src/contacts_service/handle.rs
  base_layer/contacts/src/contacts_service/service.rs
  base_layer/contacts/src/contacts_service/storage/types/messages.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/contacts/src/contacts_service/types/message_builder.rs
  base_layer/contacts/src/schema.rs
  base_layer/contacts/tests/contacts_service.rs
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/src/chat_ffi.rs
Labels: P-reviews_required, P-acks_required

#6360 fix: atomic swap
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-acks_required

#6359 ci(fix): further cross build improvements, with updated build doc
  .github/workflows/build_binaries.yml
  .github/workflows/build_libffis.yml
  Cross.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/init/mod.rs
  buildtools/build-notes.md
  scripts/cross_compile_tooling.sh
  scripts/cross_compile_ubuntu_18-pre-build.sh
  scripts/install_ubuntu_dependencies-rust-arm64.sh
  scripts/install_ubuntu_dependencies-rust.sh
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#6364 feat: limit script max size
  base_layer/core/src/consensus/consensus_constants.rs
Labels: CR-insufficient_context, P-acks_required
