Repository tari-project/tari, pull requests merged in 2024-03, with the labels that each got.

#6154 feat: limit transaction size
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/storage/sqlite_utilities/mod.rs
  base_layer/wallet/src/test_utils.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/protocols/mod.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
  base_layer/wallet/tests/support/utils.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6175 test: fix cucumber network environment
  integration_tests/src/base_node_process.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet_process.rs
Labels: P-reviews_required, P-acks_required

#6163 chore: removes panics from wallet burn task
  applications/minotari_console_wallet/src/ui/state/tasks.rs
Labels: CR-insufficient_context, P-acks_required

#6159 fix: hide unmined coinbase
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
Labels: P-acks_required

#6176 chore: add localnet gen block
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  integration_tests/tests/steps/node_steps.rs
Labels: P-acks_required

#6152 feat: wallet ffi use dns
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
Labels: P-acks_required

#6180 feat: make the make_it_rain submission rate a float
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  integration_tests/tests/features/StressTest.feature
  integration_tests/tests/features/TransactionInfo.feature
  integration_tests/tests/features/WalletCli.feature
  integration_tests/tests/features/WalletFFI.feature
  integration_tests/tests/features/WalletMonitoring.feature
  integration_tests/tests/features/WalletQuery.feature
  integration_tests/tests/features/WalletRoutingMechanism.feature
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/features/WalletTransfer.feature
  integration_tests/tests/steps/mining_steps.rs
  integration_tests/tests/steps/wallet_cli_steps.rs
  integration_tests/tests/steps/wallet_ffi_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6182 chore: upgrade deps
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/commands/cli_loop.rs
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/wallet/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6185 chore: remove `subtle` feature
  applications/minotari_app_grpc/Cargo.toml
Labels: P-reviews_required, P-acks_required

#6184 chore: change default network
  Cargo.lock
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/build.rs
  base_layer/wallet_ffi/src/lib.rs
  common/src/configuration/network.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6186 chore: add minotari_mining_helper_ffi to build plus clean ups
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  base_layer/tari_mining_helper_ffi/Cargo.toml
Labels: P-acks_required

#6183 feat: mining ffi add coinbase add
  Cargo.lock
  base_layer/core/src/blocks/new_block_template.rs
  base_layer/core/src/blocks/new_blockheader_template.rs
  base_layer/core/src/proof_of_work/difficulty.rs
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/src/error.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6190 fix: remove extra range proof verifications
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-acks_required

#6191 feat: expose extra_data field to wallet ffi
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6192 chore: nextnext build fixes
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/common_types/README.md
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/auto_update/gpg_keys/CjS77.asc
  base_layer/p2p/src/auto_update/gpg_keys/README.md
  base_layer/p2p/src/auto_update/gpg_keys/hansieodendaal.asc
  base_layer/p2p/src/auto_update/gpg_keys/sdbondi.asc
  base_layer/p2p/src/auto_update/gpg_keys/stringhandler.asc
  base_layer/p2p/src/auto_update/gpg_keys/swvheerden.asc
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common/tari_features/README.md
  common_sqlite/Cargo.toml
  common_sqlite/README.md
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  comms/rpc_macros/README.md
  hash_domains/Cargo.toml
  hash_domains/README.md
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/metrics/README.md
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/tari_script/README.md
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6193 ci(fix): add windows ffi libraries
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6197 fix: horizon sync
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
Labels: P-acks_required

#6194 fix: add .h file to mining helper
  Cargo.lock
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/build.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/tari_mining_helper_ffi/tari_mining_helper.h
Labels: CR-insufficient_context, P-acks_required

#6188 feat!: change split to 50-50
  applications/minotari_node/src/grpc/hash_rate.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/tests/tests/node_state_machine.rs
Labels: P-reviews_required, P-acks_required

#6198 chore: new release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6200 chore: new gen blocks
  base_layer/core/src/blocks/genesis_block.rs
Labels: CR-insufficient_context, P-acks_required

#6201 chore: new release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6199 chore: new nextnetnet release v1.0.0-rc.6
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6202 chore: new stagenet release 1.0.0-alpha.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6204 fix: downgrade crossterm for windows compatibility
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
Labels: P-acks_required

#6205 chore: new release v1.0.0-pre.11a
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6206 chore: new nextnet release 1.0.0-rc.6a
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6209 ci(fix): docker build - limit perms to package write only
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
Labels: P-acks_required

#6213 chore: allow fixed tests
  integration_tests/tests/features/WalletFFI.feature
Labels: CR-insufficient_context, P-acks_required

#6217 chore: fix ffi stagenet + new version
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#6196 feat: optimize transaction validation db queries
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6218 fix!: change grpc deny to allow
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/cli.rs
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  applications/minotari_node/src/lib.rs
  common/config/presets/c_base_node_b_mining_allow_methods.toml
  common/config/presets/c_base_node_b_non_mining_allow_methods.toml
  common/src/configuration/utils.rs
  integration_tests/src/base_node_process.rs
Labels: P-acks_required

#6210 fix: base node write tor address
  applications/minotari_node/src/bootstrap.rs
Labels: P-acks_required

#6220 feat: remove template blocking call
  base_layer/core/src/mempool/mempool.rs
  base_layer/core/src/mempool/mempool_storage.rs
  base_layer/core/src/mempool/unconfirmed_pool/mod.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
Labels: P-acks_required

#6222 feat: cache new block template
  applications/minotari_merge_mining_proxy/src/block_template_data.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/error.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
Labels: P-reviews_required, P-acks_required

#6227 chore(ci): improve security, add build target riscv with best effort support
  .cargo/config.toml
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_libffis.yml
  scripts/install_ubuntu_dependencies-arm64.sh
  scripts/install_ubuntu_dependencies-cross_compile.sh
Labels: P-acks_required

#6235 feat: add bad block reason
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/header_sync/validator.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/src/validation/header/header_full_validator.rs
Labels: P-acks_required

#6233 fix: potential in panic message_vector_get_at
  base_layer/chat_ffi/src/conversationalists.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/messages.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#5644 feat: ledger key manager interface
  .gitignore
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_ledger_wallet/Cargo.lock
  applications/minotari_ledger_wallet/Cargo.toml
  applications/minotari_ledger_wallet/README.md
  applications/minotari_ledger_wallet/app_nanosplus.json
  applications/minotari_ledger_wallet/key_14x14.gif
  applications/minotari_ledger_wallet/key_16x16.gif
  applications/minotari_ledger_wallet/rust-toolchain.toml
  applications/minotari_ledger_wallet/rustfmt.toml
  applications/minotari_ledger_wallet/src/hashing.rs
  applications/minotari_ledger_wallet/src/main.rs
  applications/minotari_ledger_wallet/src/utils.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/lib.rs
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/transactions/key_manager/error.rs
  base_layer/core/src/transactions/key_manager/initializer.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/memory_db_key_manager.rs
  base_layer/core/src/transactions/key_manager/mod.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/storage/database.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
  infrastructure/derive/Cargo.toml
  scripts/install_ubuntu_dependencies.sh
Labels: CR-too_long, P-reviews_required, P-acks_required

#6231 feat: add dynamic growth to lmdb
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  infrastructure/storage/src/lmdb_store/store.rs
Labels: P-acks_required

#6238 chore: remove ahash as dependancy
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/p2p/Cargo.toml
  common/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6232 feat: improve wallet sql queries
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  common/config/presets/d_console_wallet.toml
Labels: P-reviews_required, P-acks_required

#6226 feat: new template with coinbase call
  Cargo.lock
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/transaction_components/transaction_kernel.rs
  common/config/presets/c_base_node_b_mining_allow_methods.toml
  common/config/presets/c_base_node_b_non_mining_allow_methods.toml
  integration_tests/src/base_node_process.rs
  integration_tests/tests/features/BlockTemplate.feature
  integration_tests/tests/steps/node_steps.rs
Labels: P-acks_required

#6225 feat!: enable multiple second layers to be registered
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_app_grpc/proto/sidechain_types.proto
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_app_grpc/src/conversions/sidechain_feature.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/components/burn_tab.rs
  applications/minotari_console_wallet/src/ui/components/register_template_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/state/tasks.rs
  applications/minotari_console_wallet/src/ui/ui_error.rs
  applications/minotari_node/src/commands/command/list_validator_nodes.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/comms_interface/comms_request.rs
  base_layer/core/src/base_node/comms_interface/comms_response.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/comms_interface/local_interface.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/active_validator_node.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/lmdb_db/validator_node_store.rs
  base_layer/core/src/chain_storage/mod.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/covenants/test.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/proto/sidechain_feature.proto
  base_layer/core/src/proto/sidechain_feature.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/transactions/transaction_components/side_chain/confidential_output.rs
  base_layer/core/src/transactions/transaction_components/side_chain/template_registration.rs
  base_layer/core/src/transactions/transaction_components/side_chain/validator_node_registration.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/error.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/mmr/src/sparse_merkle_tree/tree.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required
