Repository tari-project/tari, pull requests merged in 2024-09, with the labels that each got.

#6518 feat: add network wire byte
  base_layer/p2p/src/initialization.rs
  common/src/configuration/network.rs
  comms/core/src/builder/mod.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connection_manager/mod.rs
  comms/core/src/protocol/network_info.rs
  comms/dht/examples/propagation/node.rs
Labels: P-reviews_required, P-acks_required

#6493 docs(fix): ledger_wallet single line docker build
  applications/minotari_ledger_wallet/wallet/README.md
Labels: P-reviews_required, P-acks_required

#6520 ci(feature): archive and checksum minotari_ledger_wallet for release
  .github/workflows/build_ledger_wallet.yml
Labels: P-reviews_required, P-acks_required

#6509 feat(p2pool-randomx-support): added pow algo to GetNewBlockRequest in p2pool proto
  applications/minotari_app_grpc/proto/p2pool.proto
  applications/minotari_app_grpc/src/conversions/mod.rs
  applications/minotari_miner/src/run_miner.rs
Labels: P-reviews_required, P-acks_required

#6523 chore: reduce logs
  applications/minotari_miner/src/run_miner.rs
  base_layer/core/src/transactions/key_manager/inner.rs
Labels: P-acks_required

#6522 feat: paper wallet cli
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_console_wallet/src/utils/db.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  changelog-development.md
Labels: P-reviews_required, P-acks_required

#6521 feat(p2pool-randomx-support): merge mining proxy update
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
Labels: P-reviews_required, P-acks_required

#6526 chore: new release esme v1.4.0-pre.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/src/configuration/network.rs
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6528 feat: clear handshake error when connections go stale
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/error.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/noise/config.rs
Labels: P-reviews_required, P-acks_required

#6531 feat: add console wallet detail
  applications/minotari_console_wallet/src/ui/components/network_tab.rs
  applications/minotari_console_wallet/src/ui/components/receive_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
Labels: P-reviews_required, P-acks_required

#6529 test: improve test coverage for xxxx_genesis_sanity_check tests
  Cargo.lock
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_encoding/hashing.rs
Labels: P-reviews_required, P-acks_required

#6534 chore: new release esmeralde v1.4.1-pre.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context

#6535 chore: new release nextnet v1.4.1-rc.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/src/configuration/network.rs
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: P-acks_required

#6537 feat: changes for the randomx miner
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/merkle_tree.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: P-acks_required

#6540 feat: reduce universe spam logs
  applications/minotari_console_wallet/log4rs_sample.yml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/mempool/service/inbound_handlers.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/dht/src/connectivity/mod.rs
Labels: P-reviews_required, P-acks_required

#6539 ci(chore): add quay expire for none release docker images
  .github/workflows/build_dockers_workflow.yml
Labels: P-reviews_required, P-acks_required

#6546 chore: reduce size of proxy logs
  applications/minotari_merge_mining_proxy/log4rs_sample.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6536 chore: update nextnet change logs
  changelog-nextnet.md
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6541 feat: ledger version check
  Cargo.lock
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/comms/src/error.rs
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
Labels: P-reviews_required, P-acks_required

#6544 feat: stop interactive only address from being used in mining
  base_layer/core/src/transactions/coinbase_builder.rs
Labels: CR-insufficient_context, P-acks_required

#6542 feat: add one-sided addresses to grpc
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
  integration_tests/src/world.rs
  integration_tests/tests/steps/wallet_cli_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-reviews_required, P-acks_required

#6545 feat: display waiting for intial peer data
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/base_node/state_machine_service/state_machine.rs
  base_layer/core/src/base_node/state_machine_service/states/events_and_states.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_service.rs
  common/config/presets/c_base_node_c.toml
Labels: P-reviews_required, P-acks_required

#6547 chore: reduce logs on proxy
  applications/minotari_merge_mining_proxy/src/proxy.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6550 feat(ci): sign windows binaries and installer
  .github/workflows/build_binaries.yml
Labels: P-acks_required

#6543 feat: add configurable exclude dialer addresses for universe
  base_layer/contacts/tests/contacts_service.rs
  base_layer/p2p/src/initialization.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/core/src/builder/mod.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/error.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/tests/listener_dialer.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/peer_manager/manager.rs
  comms/dht/src/actor.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
Labels: P-reviews_required, P-acks_required

#6551 chore: new release esmeralda 1.4.2-pre.1
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6552 chore: new release nextnet 1.4.2-rc.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/src/configuration/network.rs
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6553 chore: update nextnet release details
  base_layer/core/src/blocks/genesis_block.rs
  changelog-nextnet.md
  common/src/configuration/network.rs
Labels: P-reviews_required, P-acks_required

#6555 chore: new version esmeralda v1.4.2-pre.2
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6556 chore: new nextnet v1.4.2-rc.1
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6558 fix: upgrade diesel version
  Cargo.lock
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/wallet/Cargo.toml
  common_sqlite/Cargo.toml
  comms/dht/Cargo.toml
Labels: P-acks_required

#6559 fix: randomX on mac x86
  base_layer/core/src/proof_of_work/randomx_factory.rs
Labels: P-reviews_required, P-acks_required

#6560 chore: hotfix for nextnet release v1.4.2-rc.2
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/proof_of_work/randomx_factory.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6561 feat: add coinbase extra info to grpc
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/transactions/aggregated_body.rs
Labels: CR-insufficient_context, P-acks_required

#6565 chore: add 4 test coins
  base_layer/core/src/blocks/pre_mine/mod.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6566 chore: new mainnet premine file
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/mainnet_pre_mine.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6567 feat: add generic config list type and use throughout all config settings
  Cargo.lock
  applications/minotari_app_utilities/src/common_cli_args.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/main.rs
  applications/minotari_merge_mining_proxy/src/cli.rs
  applications/minotari_merge_mining_proxy/src/main.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  applications/minotari_miner/src/cli.rs
  applications/minotari_miner/src/main.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/cli.rs
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  applications/minotari_node/src/grpc_method.rs
  applications/minotari_node/src/lib.rs
  applications/minotari_node/src/main.rs
  base_layer/chat_ffi/src/application_config.rs
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/auto_update/dns.rs
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/p2p/src/auto_update/service.rs
  base_layer/p2p/src/config.rs
  base_layer/p2p/src/lib.rs
  base_layer/p2p/src/peer_seeds.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/b_peer_seeds.toml
  common/src/configuration/config_list.rs
  common/src/configuration/mod.rs
  common/src/configuration/multiaddr_list.rs
  common/src/configuration/name_server.rs
  common/src/configuration/string_list.rs
  common/src/configuration/utils.rs
  integration_tests/src/base_node_process.rs
Labels: P-reviews_required, P-acks_required

#6564 feat: update consensus
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-reviews_required, P-acks_required

#6557 feat: add multiaddr with range checks for use with universe
  Cargo.lock
  base_layer/contacts/tests/contacts_service.rs
  base_layer/p2p/src/initialization.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  clients/ffi_client/index.js
  clients/ffi_client/recovery.js
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/core/Cargo.toml
  comms/core/src/builder/mod.rs
  comms/core/src/connection_manager/dialer.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/tests/listener_dialer.rs
  comms/core/src/net_address/mod.rs
  comms/core/src/net_address/multiaddr_range.rs
  comms/dht/src/actor.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
  integration_tests/src/ffi/comms_config.rs
  integration_tests/src/ffi/ffi_import.rs
Labels: P-reviews_required, P-acks_required

#6571 fix: fix coinbase share calculations
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: CR-insufficient_context

#6568 feat: broadcast one sided
  base_layer/common_types/src/transaction.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/support/output_manager_service_mock.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  integration_tests/tests/features/WalletFFI.feature
  integration_tests/tests/steps/wallet_ffi_steps.rs
Labels: P-reviews_required, P-acks_required

#6527 feat: add resilience to initial wallet connect
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/state/wallet_event_monitor.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/base_node_peer_manager.rs
  base_layer/wallet/src/connectivity_service/error.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/initializer.rs
  base_layer/wallet/src/connectivity_service/interface.rs
  base_layer/wallet/src/connectivity_service/mock.rs
  base_layer/wallet/src/connectivity_service/mod.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
  base_layer/wallet/src/error.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet_ffi/src/lib.rs
  comms/core/src/test_utils/mocks/connectivity_manager.rs
Labels: P-reviews_required, P-acks_required

#6569 feat!: add ability to encrypt seed words
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_console_wallet/src/recovery.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
  integration_tests/tests/features/WalletFFI.feature
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6574 chore: new nextnet release v1.5.0-rc.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/config/presets/f_merge_mining_proxy.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6577 chore: new release esme v1.5.1-pre.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/config/presets/f_merge_mining_proxy.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6579 chore: new release nextnet v1.5.1-rc.2
  Cargo.lock
  base_layer/common_types/Cargo.toml
  base_layer/core/src/consensus/consensus_constants.rs
  changelog-nextnet.md
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6580 chore: fix nextnet consensus in dev
  base_layer/core/src/consensus/consensus_constants.rs
Labels: CR-insufficient_context, P-acks_required

#6570 feat(p2pool): add coinbase extra field to p2pool proto
  applications/minotari_app_grpc/proto/p2pool.proto
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_miner/src/run_miner.rs
Labels: P-acks_required

#6582 chore: new release esme v1.5.1-pre.1
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6584 chore: new release v1.5.1-rc.3
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/proto/p2pool.proto
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6586 feat: add payment id to notify script
  Cargo.lock
  applications/minotari_console_wallet/src/notifier/mod.rs
  applications/minotari_console_wallet/src/notifier/notify_example.sh
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
  base_layer/tari_mining_helper_ffi/Cargo.toml
Labels: CR-insufficient_context, P-acks_required
