Repository tari-project/tari, pull requests merged in 2024-06, with the labels that each got.

#6368 chore: esme new release 1.0.0-pre.14
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6363 ci(fix): add individual feature ```cargo check```
  .github/workflows/ci.yml
Labels: P-acks_required

#6362 feat: make console wallet ledger default
  applications/minotari_console_wallet/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#6361 feat!: export unblinded outputs
  Cargo.lock
  applications/minotari_app_grpc/proto/transaction.proto
  applications/minotari_app_grpc/src/conversions/transaction_output.rs
  applications/minotari_app_grpc/src/conversions/unblinded_output.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/unblinded_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/tests/chain_storage_tests/chain_backend.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/other/mod.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/log4rs/cucumber.yml
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/steps/wallet_cli_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-acks_required

#6374 fix: improve key scanning
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/key_manager/src/key_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
Labels: P-acks_required

#6372 feat!: change tar address to use base58 and not hex
  Cargo.lock
  applications/minotari_app_utilities/src/utilities.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/notifier/mod.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/ui_contact.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_miner/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/chat_ffi/src/contacts_liveness_data.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/ffi/callbacks.rs
  integration_tests/src/ffi/contact.rs
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
  integration_tests/src/ffi/wallet_address.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet_ffi.rs
  integration_tests/src/world.rs
  integration_tests/tests/steps/chat_ffi_steps.rs
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_cli_steps.rs
  integration_tests/tests/steps/wallet_ffi_steps.rs
Labels: P-reviews_required, P-acks_required

#6376 feat!: make stealth one-sided tx's look the same as all other tx's
  applications/minotari_console_wallet/src/ui/components/send_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_miner/README.md
  applications/minotari_miner/src/config.rs
  applications/minotari_miner/src/run_miner.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  common/config/presets/f_merge_mining_proxy.toml
  common/config/presets/g_miner.toml
  infrastructure/tari_script/src/lib.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
  integration_tests/tests/steps/merge_mining_steps.rs
Labels: P-reviews_required, P-acks_required

#6375 fix: keep alpha key constant
  applications/minotari_console_wallet/src/init/mod.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6381 fix: update curve library
  Cargo.lock
Labels: P-reviews_required, P-acks_required

#6380 fix: make tx id random
  base_layer/core/src/transactions/transaction_protocol/mod.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
Labels: P-acks_required

#6377 feat: m of n scripting poc
  Cargo.lock
  applications/minotari_app_utilities/src/utilities.rs
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/error.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature_from_challenge.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/core/src/common/one_sided.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/transaction_components/range_proof_type.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/wallet/src/output_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  infrastructure/tari_script/src/lib.rs
Labels: CR-too_long, P-acks_required
