Repository tari-project/tari, pull requests merged in 2024-04, with the labels that each got.

#6237 feat: add validation for zero confirmation block sync
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/core/src/validation/helpers.rs
Labels: P-acks_required

#6241 ci: bump nightly version
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_tests.yml
  applications/minotari_ledger_wallet/rust-toolchain.toml
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/common_types/src/tx_id.rs
  base_layer/core/src/covenants/decoder.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/key_manager/src/lib.rs
  base_layer/mmr/src/backend.rs
  base_layer/service_framework/src/context/handles.rs
  base_layer/wallet/src/operation_id.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet_ffi/README.md
  buildtools/docker/base_node.Dockerfile
  comms/core/src/peer_manager/migrations.rs
  comms/core/src/test_utils/mocks/connection_manager.rs
  comms/core/src/tor/hidden_service/controller.rs
  comms/dht/src/test_utils/dht_actor_mock.rs
  lints.toml
  rust-toolchain.toml
  scripts/test_in_docker.sh
Labels: P-acks_required

#6239 feat: prevent mempool panic
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/transactions/transaction_components/error.rs
  base_layer/core/src/transactions/weight.rs
Labels: P-reviews_required, P-acks_required

#6245 feat: allow wallet type from db to have preference
  applications/minotari_ledger_wallet/rustfmt.toml
  base_layer/wallet/src/wallet.rs
  rustfmt.toml
Labels: P-acks_required

#6242 feat: improve lmdb dynamic growth
  applications/minotari_console_wallet/src/ui/mod.rs
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/base_node/sync/rpc/service.rs
  base_layer/core/src/chain_storage/lmdb_db/helpers.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_chain_validator.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/g_miner.toml
  infrastructure/storage/src/lmdb_store/mod.rs
  infrastructure/storage/src/lmdb_store/store.rs
  infrastructure/storage/tests/lmdb.rs
Labels: P-reviews_required, P-acks_required

#6248 feat: add monerod detection as an option to the merge mining proxy
  Cargo.lock
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/log4rs_sample.yml
  applications/minotari_merge_mining_proxy/src/block_template_data.rs
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_merge_mining_proxy/src/error.rs
  applications/minotari_merge_mining_proxy/src/lib.rs
  applications/minotari_merge_mining_proxy/src/main.rs
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  common/config/presets/f_merge_mining_proxy.toml
  integration_tests/src/merge_mining_proxy.rs
Labels: P-acks_required

#6247 fix(chat): metadata panic
  base_layer/chat_ffi/chat.h
  base_layer/chat_ffi/src/byte_vector.rs
  base_layer/chat_ffi/src/confirmation.rs
  base_layer/chat_ffi/src/contacts.rs
  base_layer/chat_ffi/src/contacts_liveness_data.rs
  base_layer/chat_ffi/src/conversationalists.rs
  base_layer/chat_ffi/src/error.rs
  base_layer/chat_ffi/src/message.rs
  base_layer/chat_ffi/src/message_metadata.rs
  base_layer/chat_ffi/src/messages.rs
  base_layer/contacts/proto/message.proto
  base_layer/contacts/src/chat_client/src/client.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/contacts/src/contacts_service/types/mod.rs
  integration_tests/src/chat_ffi.rs
  integration_tests/tests/steps/chat_steps.rs
Labels: P-acks_required

#6246 feat: show warning when GRPC method is disallowed
  applications/minotari_node/src/config.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: CR-insufficient_context, P-acks_required

#6249 refactor: fix template registration grpc
  .cargo/config.toml
  Cargo.lock
  applications/minotari_app_grpc/proto/wallet.proto
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/components/burn_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/state/tasks.rs
  applications/minotari_console_wallet/src/ui/ui_error.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/transaction_components/side_chain/template_registration.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  ci_all.bat
  hash_domains/Cargo.toml
  hash_domains/src/lib.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6265 feat: keep smt memory
  applications/minotari_node/src/bootstrap.rs
  applications/minotari_node/src/builder.rs
  applications/minotari_node/src/recovery.rs
  base_layer/core/src/base_node/sync/block_sync/synchronizer.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_backend.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/db_transaction.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/validation/block_body/block_body_full_validator.rs
  base_layer/core/src/validation/block_body/test.rs
  base_layer/core/src/validation/mocks.rs
  base_layer/core/src/validation/traits.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/core/tests/helpers/sample_blockchains.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_comms_interface.rs
Labels: P-reviews_required, P-acks_required

#6270 ci(fix): docker image build fix and ci improvements
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/build_libffis.yml
  Cross.toml
Labels: P-reviews_required, P-acks_required

#6275 fix!: avoid `Encryptable` domain collisions
  base_layer/key_manager/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
Labels: P-acks_required

#6283 ci(fix): fix release plus add json flag for for additional metric builds
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_libffis.yml
Labels: P-acks_required

#6290 fix: wallet ffi type incorrect
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6284 feat: improve node and wallet connection times
  applications/minotari_app_grpc/proto/network.proto
  applications/minotari_app_grpc/src/conversions/peer.rs
  applications/minotari_node/src/bootstrap.rs
  applications/minotari_node/src/commands/command/get_peer.rs
  applications/minotari_node/src/commands/command/status.rs
  base_layer/contacts/src/chat_client/src/config.rs
  base_layer/contacts/tests/contacts_service.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/p2p/src/config.rs
  base_layer/p2p/src/initialization.rs
  base_layer/p2p/src/services/liveness/error.rs
  base_layer/p2p/src/services/liveness/mod.rs
  base_layer/p2p/src/services/liveness/service.rs
  base_layer/p2p/tests/services/liveness.rs
  base_layer/wallet/src/config.rs
  base_layer/wallet/tests/other/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/core/src/builder/comms_node.rs
  comms/core/src/builder/mod.rs
  comms/core/src/connection_manager/common.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connection_manager/manager.rs
  comms/core/src/connection_manager/mod.rs
  comms/core/src/connection_manager/self_liveness.rs
  comms/core/src/lib.rs
  comms/core/src/net_address/multiaddr_with_stats.rs
  comms/core/src/net_address/mutliaddresses_with_stats.rs
  comms/core/src/peer_manager/manager.rs
  comms/core/src/peer_manager/peer.rs
  comms/dht/src/config.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/discovery/service.rs
  comms/dht/src/inbound/dht_handler/task.rs
  comms/dht/src/network_discovery/config.rs
  comms/dht/src/network_discovery/initializing.rs
  comms/dht/src/network_discovery/on_connect.rs
  comms/dht/src/network_discovery/test.rs
  comms/dht/src/peer_validator.rs
Labels: P-reviews_required, P-acks_required

#6301 chore: new release 1.0.0-pre.12
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6302 chore: new release nextnet 1.0.0-rc.7
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
  base_layer/core/src/blocks/block.rs
  base_layer/core/src/proto/block.proto
  base_layer/core/src/proto/block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/key_manager_service/storage/sqlite_db/key_manager_state.rs
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/storage/sqlite_db/wallet.rs
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6287 feat: updates the emoji ID API to be more idiomatic
  applications/minotari_app_utilities/src/utilities.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_node/src/commands/command/get_peer.rs
  base_layer/common_types/src/dammsum.rs
  base_layer/common_types/src/emoji.rs
  base_layer/common_types/src/tari_address.rs
Labels: P-acks_required

#6305 fix: hot for removing breaking change in wallet, new release for nexnet v1.0.0-rc.8
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: P-acks_required

#6306 fix: potential overflow of coinbase calc
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/common_types/src/emoji.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  integration_tests/tests/steps/node_steps.rs
Labels: P-reviews_required, P-acks_required

#6312 chore: prevent spam logs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Labels: P-acks_required

#6313 chore: show smt is loading
  base_layer/core/src/chain_storage/blockchain_database.rs
Labels: P-acks_required
