Repository tari-project/tari, pull requests merged in 2024-02, with the labels that each got.

#6115 feat: smt verification
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
Labels: P-acks_required

#6114 feat: do validation after adding utxos and txs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/support/output_manager_service_mock.rs
  base_layer/wallet/tests/support/transaction_service_mock.rs
Labels: P-acks_required

#6110 chore: update pgp keys
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/p2p/src/auto_update/signature.rs
  meta/gpg_keys/delta1.asc
  meta/gpg_keys/neonknight64.asc
  meta/gpg_keys/philipr-za.asc
Labels: P-merge, P-acks_required

#6111 feat: export transaction
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
Labels: P-acks_required

#6109 feat: initial horizon sync from prune node
  base_layer/core/src/base_node/state_machine_service/states/sync_decide.rs
  base_layer/core/src/base_node/sync/rpc/sync_utxos_task.rs
  base_layer/core/src/chain_storage/async_db.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/tests/tests/horizon_sync.rs
Labels: CR-too_long, P-acks_required

#6117 fix: make monero extra data less strict
  base_layer/core/src/base_node/sync/header_sync/synchronizer.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
Labels: P-reviews_required, P-acks_required

#6113 feat: wallet add restart validation to start
  base_layer/wallet/src/wallet.rs
Labels: P-acks_required

#6118 chore: suppress warn log
  comms/core/src/connection_manager/dialer.rs
Labels: CR-insufficient_context, P-acks_required

#6119 fix: restart tx fix
  base_layer/wallet/src/wallet.rs
Labels: CR-insufficient_context, P-acks_required

#6120 chore: new release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6121 chore: new rc version
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6123 chore: make MAC equality check more idiomatic
  base_layer/key_manager/src/cipher_seed.rs
Labels: P-acks_required

#6124 fix(comms): correctly initialize hidden service
  comms/core/src/tor/control_client/client.rs
  comms/core/src/tor/control_client/monitor.rs
  comms/core/src/tor/hidden_service/controller.rs
  comms/core/src/transports/hidden_service_transport.rs
  infrastructure/libtor/Cargo.toml
  infrastructure/libtor/src/tor.rs
Labels: P-acks_required

#6125 fix(libtor): prevent metrics port conflict
  Cargo.lock
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_node/src/main.rs
  infrastructure/libtor/Cargo.toml
  infrastructure/libtor/src/tor.rs
Labels: P-acks_required

#6127 chore: new testnet release
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6129 chore: update pgp public key
  meta/gpg_keys/hansieodendaal.asc
Labels: P-acks_required

#6130 chore: new nextnet release
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6132 feat: add import tx method
  Cargo.lock
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/database.rs
  base_layer/wallet/src/transaction_service/storage/models.rs
Labels: P-acks_required

#6073 feat: turn off node metrics by default
  applications/minotari_node/Cargo.toml
  applications/minotari_node/src/commands/command/get_network_stats.rs
  applications/minotari_node/src/lib.rs
  integration_tests/Cargo.toml
Labels: P-acks_required

#6139 chore: add pgp public key
  meta/gpg_keys/cifko.asc
Labels: CR-insufficient_context, P-acks_required

#6134 chore: add stringhandler gpg
  meta/gpg_keys/stringhandler.asc
Labels: CR-insufficient_context, P-acks_required

#6135 chore: fix versions to correct version
  Cargo.lock
  hash_domains/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/tari_script/Cargo.toml
Labels: P-acks_required

#6136 chore: fix versions nextnet
  Cargo.lock
  hash_domains/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/tari_script/Cargo.toml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6141 chore(ci): add metrics targeted build, remove miner artifacts, misc clean ups
  .github/workflows/base_node_binaries.json
  .github/workflows/base_node_binaries.yml
Labels: P-acks_required

#6140 feat: allow ffi to see lock height
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6144 fix: balanced binary merkle tree merged proof
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
Labels: P-reviews_required, P-acks_required

#6148 chore: use log4rs 1.3
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
Labels: P-acks_required

#6147 chore(ci): osx arm64 code sign with entitlements and include diag-utils
  .github/workflows/base_node_binaries.yml
  .github/workflows/ci.yml
  .license.ignore
  applications/minotari_node/osx-pkg/entitlements.xml
  buildtools/windows_inno_installer.iss
Labels: P-acks_required

#6150 refactor(common-types): move waiting_requests, remove tokio dep
  Cargo.lock
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/lib.rs
  base_layer/core/src/base_node/service/service.rs
  base_layer/core/src/base_node/service/service_request.rs
  base_layer/core/src/base_node/service/service_response.rs
  base_layer/core/src/common/mod.rs
  base_layer/core/src/common/waiting_requests.rs
  base_layer/core/src/mempool/service/request.rs
  base_layer/core/src/mempool/service/response.rs
Labels: P-acks_required

#6146 feat: check chain metadata
  base_layer/common_types/src/chain_metadata.rs
  base_layer/core/src/base_node/proto/chain_metadata.rs
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
  base_layer/core/src/base_node/sync/sync_peer.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/wallet/tests/support/base_node_service_mock.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
Labels: P-acks_required

#6156 feat!: change proof of work to be dependant on target difficulty
  base_layer/core/src/blocks/accumulated_data.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/tests/tests/header_sync.rs
Labels: P-acks_required

#6153 feat: change CLI get_block to search orphans
  applications/minotari_node/src/commands/command/get_block.rs
Labels: P-acks_required

#6143 chore: fixes for crates release
  Cargo.lock
  base_layer/common_types/Cargo.toml
  base_layer/common_types/README.md
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/auto_update/gpg_keys/README.md
  base_layer/p2p/src/auto_update/gpg_keys/swvheerden.asc
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/service_framework/Cargo.toml
  base_layer/wallet/Cargo.toml
  common/Cargo.toml
  common/tari_features/README.md
  common_sqlite/Cargo.toml
  common_sqlite/README.md
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  comms/rpc_macros/README.md
  hash_domains/Cargo.toml
  hash_domains/README.md
  infrastructure/metrics/README.md
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/README.md
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6157 chore: new release for esme
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hash_domains/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6165 fix: fixed make-it-rain delay
  applications/minotari_console_wallet/src/automation/commands.rs
Labels: P-acks_required

#6161 fix: oms validation
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
Labels: P-reviews_required, P-acks_required

#6166 fix: avoid cloning range proofs during verification
  base_layer/common_types/src/types/bullet_rangeproofs.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-acks_required

#6158 fix!: changes balance query
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/components/balance.rs
  applications/minotari_console_wallet/src/ui/state/debouncer.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/output_sql.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
Labels: P-acks_required

#6169 chore: remove un-used code
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/notifier/mod.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_validation_protocol.rs
Labels: CR-insufficient_context, P-acks_required

#6160 feat!: implement inflating tail emission
  applications/minotari_app_grpc/proto/types.proto
  applications/minotari_app_grpc/src/conversions/consensus_constants.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/consensus/emission.rs
  base_layer/core/src/transactions/tari_amount.rs
  base_layer/core/src/validation/chain_balance.rs
  base_layer/core/tests/helpers/sample_blockchains.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/core/tests/tests/node_state_machine.rs
Labels: A-base_node, W-consensus_breaking, P-acks_required, W-breaking

#6173 fix: wallet validation during reorgs
  base_layer/wallet/src/output_manager_service/storage/database/backend.rs
  base_layer/wallet/src/output_manager_service/storage/database/mod.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required
