Repository tari-project/tari, pull requests merged in 2024-07, with the labels that each got.

#6383 feat: ledger recovery
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/ui/components/send_tab.rs
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_ledger_wallet/wallet/src/handlers/get_dh_shared_secret.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature_from_challenge.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_view_key.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/wallet_types.rs
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/common/one_sided.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/key_manager/Cargo.toml
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/mod.rs
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/config.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  hashing/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
Labels: P-acks_required

#6382 feat: enlarge console wallet display
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  applications/minotari_console_wallet/src/ui/mod.rs
Labels: P-reviews_required, P-acks_required

#6385 feat!: add accessor functions for tari address in FFI
  base_layer/common_types/src/emoji.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6384 feat!: faucet and new esme gen block
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/recovery.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/faucets/esmeralda_faucet.json
  base_layer/core/src/blocks/faucets/mod.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/mod.rs
  base_layer/core/src/common/one_sided.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  hashing/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
Labels: CR-too_long, P-reviews_required, P-acks_required

#6370 feat(miner): add SHA P2Pool mining related configuration and changes
  applications/minotari_app_grpc/build.rs
  applications/minotari_app_grpc/proto/p2pool.proto
  applications/minotari_app_utilities/src/parse_miner_input.rs
  applications/minotari_miner/build.rs
  applications/minotari_miner/linux/runtime/start_minotari_miner.sh
  applications/minotari_miner/osx/runtime/start_minotari_miner.sh
  applications/minotari_miner/src/cli.rs
  applications/minotari_miner/src/config.rs
  applications/minotari_miner/src/difficulty.rs
  applications/minotari_miner/src/errors.rs
  applications/minotari_miner/src/lib.rs
  applications/minotari_miner/src/main.rs
  applications/minotari_miner/src/miner.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_miner/src/stratum/controller.rs
  applications/minotari_miner/src/stratum/error.rs
  applications/minotari_miner/src/stratum/mod.rs
  applications/minotari_miner/src/stratum/stratum_controller/controller.rs
  applications/minotari_miner/src/stratum/stratum_controller/mod.rs
  applications/minotari_miner/src/stratum/stratum_types/client_message.rs
  applications/minotari_miner/src/stratum/stratum_types/job.rs
  applications/minotari_miner/src/stratum/stratum_types/job_params.rs
  applications/minotari_miner/src/stratum/stratum_types/login_params.rs
  applications/minotari_miner/src/stratum/stratum_types/login_response.rs
  applications/minotari_miner/src/stratum/stratum_types/miner_message.rs
  applications/minotari_miner/src/stratum/stratum_types/mod.rs
  applications/minotari_miner/src/stratum/stratum_types/rpc_error.rs
  applications/minotari_miner/src/stratum/stratum_types/rpc_request.rs
  applications/minotari_miner/src/stratum/stratum_types/rpc_response.rs
  applications/minotari_miner/src/stratum/stratum_types/submit_params.rs
  applications/minotari_miner/src/stratum/stratum_types/submit_response.rs
  applications/minotari_miner/src/stratum/stratum_types/worker_identifier.rs
  applications/minotari_miner/src/stratum/stream.rs
Labels: P-reviews_required, P-acks_required

#6392 docs: update hasher documentation
  hashing/src/borsh_hasher.rs
Labels: P-acks_required

#6396 chore: fix unwraps in memory key manager
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/core/benches/mempool.rs
  base_layer/core/src/blocks/faucets/mod.rs
  base_layer/core/src/chain_storage/tests/blockchain_database.rs
  base_layer/core/src/covenants/covenant.rs
  base_layer/core/src/covenants/fields.rs
  base_layer/core/src/covenants/filters/absolute_height.rs
  base_layer/core/src/covenants/filters/and.rs
  base_layer/core/src/covenants/filters/field_eq.rs
  base_layer/core/src/covenants/filters/fields_hashed_eq.rs
  base_layer/core/src/covenants/filters/fields_preserved.rs
  base_layer/core/src/covenants/filters/identity.rs
  base_layer/core/src/covenants/filters/not.rs
  base_layer/core/src/covenants/filters/or.rs
  base_layer/core/src/covenants/filters/output_hash_eq.rs
  base_layer/core/src/covenants/filters/xor.rs
  base_layer/core/src/mempool/priority/prioritized_transaction.rs
  base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
  base_layer/core/src/mempool/sync_protocol/test.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/test_helpers/blockchain.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/key_manager/memory_db_key_manager.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/test.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/src/validation/aggregate_body/aggregate_body_internal_validator.rs
  base_layer/core/src/validation/helpers.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/helpers/sample_blockchains.rs
  base_layer/core/tests/helpers/sync.rs
  base_layer/core/tests/tests/base_node_rpc.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/mempool.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/core/tests/tests/node_service.rs
  base_layer/core/tests/tests/node_state_machine.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/tari_mining_helper_ffi/src/error.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/tests/other/mod.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/output_manager_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  integration_tests/src/world.rs
Labels: P-reviews_required, P-acks_required

#6390 feat: add ffi features
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-reviews_required, P-acks_required

#6398 fix: script dependance on party order
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6402 ci(fix): include macOS universal assets in release
  .github/workflows/build_binaries.yml
Labels: P-reviews_required, P-acks_required

#6399 feat: simplify leader sig generation
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature_from_challenge.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/wallet_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-reviews_required, P-acks_required

#6404 chore: new release v1.0.0-pre.16
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/faucets/esmeralda_faucet.json
  base_layer/core/src/blocks/faucets/mod.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6406 feat: update ledger instructions
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_ledger_wallet/wallet/README.md
  applications/minotari_ledger_wallet/wallet/src/main.rs
Labels: P-reviews_required, P-acks_required

#6400 refactor: remove metadata sig and use difference key branch for offset
  applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-reviews_required, P-acks_required

#6407 feat!: fix key manager use of keys
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_console_wallet/src/ui/app.rs
  applications/minotari_console_wallet/src/ui/components/receive_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  base_layer/common_types/src/lib.rs
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/service.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/resources.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/util/wallet_identity.rs
  base_layer/wallet/src/utxo_scanner_service/initializer.rs
  base_layer/wallet/src/utxo_scanner_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/utxo_scanner_service/uxto_scanner_service_builder.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
  base_layer/wallet_ffi/src/error.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-acks_required

#6412 chore: remove dependancy on ledger for common types
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
  base_layer/common_types/Cargo.toml
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/src/transactions/key_manager/inner.rs
Labels: P-reviews_required, P-acks_required

#6413 fix: branch keys
  applications/minotari_ledger_wallet/wallet/src/handlers/get_dh_shared_secret.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_public_key.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_public_spend_key.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_offset.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
Labels: P-reviews_required, P-acks_required

#6414 fix: panic in from_base58 fn
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
  base_layer/wallet_ffi/src/error.rs
  common/src/build/application.rs
Labels: P-acks_required

#6415 chore: fix build and osp
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/wallet/src/wallet.rs
  common/src/build/application.rs
Labels: P-reviews_required, P-acks_required

#6416 chore: remove unnecessary commitment hashing
  applications/minotari_console_wallet/src/automation/commands.rs
  base_layer/core/src/blocks/faucets/mod.rs
  base_layer/core/src/common/one_sided.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-acks_required

#6419 chore: sync FFI and Console Wallet payment Id display options
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6422 feat: change grpc address conversions to use from_str
  applications/minotari_console_wallet/src/grpc/wallet_grpc_server.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: P-acks_required

#6423 chore: new release esme v1.0.0-pre.17
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6425 feat: encode max allowable encrypted bytes into struct
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_encoding/bytes.rs
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
  base_layer/core/src/validation/block_body/test.rs
Labels: P-reviews_required, P-acks_required

#6427 chore: remove panic abort
  Cargo.toml
Labels: P-reviews_required, P-acks_required

#6428 fix: wallet address deserialize
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
Labels: P-reviews_required, P-acks_required

#6429 chore: new release esme v1.0.0-pre.18
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6424 chore: rename pre mine
  README.md
  applications/minotari_app_grpc/proto/types.proto
  applications/minotari_app_grpc/src/conversions/consensus_constants.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/mod.rs
  applications/minotari_console_wallet/src/automation/utils.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/mod.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
  base_layer/core/src/blocks/pre_mine/igor_pre_mine.json
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/core/src/blocks/pre_mine/nextnet_pre_mine.json
  base_layer/core/src/blocks/pre_mine/stagenet_pre_mine.json
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_manager.rs
  base_layer/core/src/consensus/emission.rs
  base_layer/core/src/validation/test.rs
  base_layer/wallet/src/output_manager_service/service.rs
  infrastructure/tari_script/src/op_codes.rs
  integration_tests/tests/features/WalletTransactions.feature
  integration_tests/tests/steps/wallet_steps.rs
  scripts/update_crate_metadata.sh
Labels: CR-insufficient_context, P-acks_required

#6431 feat: backup spend for pre-mine
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6436 chore: remove domain digest
  Cargo.lock
  base_layer/mmr/Cargo.toml
  base_layer/mmr/src/balanced_binary_merkle_proof.rs
  base_layer/mmr/src/balanced_binary_merkle_tree.rs
  base_layer/mmr/src/common.rs
  base_layer/mmr/src/functions.rs
  base_layer/mmr/src/merkle_mountain_range.rs
  base_layer/mmr/src/merkle_proof.rs
  base_layer/mmr/src/pruned_hashset.rs
  common/Cargo.toml
  common/src/hashing.rs
  common/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6410 feat: add ledger function to generate one sided metadata signature
  applications/minotari_ledger_wallet/common/src/common_types.rs
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/comms/src/error.rs
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_one_sided_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  applications/minotari_ledger_wallet/wallet/src/utils.rs
  base_layer/common_types/src/key_branches.rs
  base_layer/core/src/common/one_sided.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/key_manager/src/key_manager_service/error.rs
  base_layer/key_manager/src/key_manager_service/interface.rs
  base_layer/key_manager/src/key_manager_service/mod.rs
  base_layer/key_manager/src/key_manager_service/service.rs
  base_layer/wallet/Cargo.toml
  base_layer/wallet/src/output_manager_service/recovery/standard_outputs_recoverer.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
Labels: P-reviews_required, P-acks_required

#6437 chore: use safer slice splitting
  base_layer/common_types/src/encryption.rs
  comms/core/src/peer_validator/helpers.rs
  docs/src/reviewing_guide.md
Labels: P-reviews_required, P-acks_required

#6435 feat: sync cli
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
Labels: P-reviews_required, P-acks_required
