Repository tari-project/tari, pull requests merged in 2024-10, with the labels that each got.

#6587 chore(ci): add stax and flex build options for minotari_ledger_wallet
  .github/workflows/build_ledger_wallet.yml
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6590 feat: update pre-mine specification and allow multiple spends
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/mod.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/core/src/transactions/tari_amount.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: CR-too_long, P-reviews_required, P-acks_required

#6591 feat: add wallet ffi backup peers
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6594 feat: add use transaction output as provided with encumber_aggregate_utxo
  applications/minotari_console_wallet/src/automation/commands.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-acks_required

#6596 feat: make pre mine spend tx stealth
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/mod.rs
  base_layer/wallet/src/output_manager_service/handle.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6597 feat: update payment_id display
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
Labels: P-acks_required

#6595 feat: allow zero fees for pre-mine
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/transactions/fee.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-reviews_required, P-acks_required

#6599 fix: ffi wallet seed behaviour
  base_layer/wallet_ffi/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6600 feat(peerseeds/autoupdate): hickory-dns upgrade, default to system DNS
  .license.ignore
  Cargo.lock
  base_layer/chat_ffi/src/application_config.rs
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/auto_update/dns.rs
  base_layer/p2p/src/auto_update/mod.rs
  base_layer/p2p/src/config.rs
  base_layer/p2p/src/dns/client.rs
  base_layer/p2p/src/dns/error.rs
  base_layer/p2p/src/dns/mock.rs
  base_layer/p2p/src/dns/roots/README.md
  base_layer/p2p/src/dns/roots/mod.rs
  base_layer/p2p/src/dns/roots/tls.rs
  base_layer/p2p/src/peer_seeds.rs
  base_layer/wallet_ffi/src/lib.rs
  common/src/configuration/name_server.rs
Labels: P-reviews_required, P-acks_required

#6602 fix(core): reduce block messages with many connections
  base_layer/core/src/base_node/service/service.rs
  comms/dht/examples/memory_net/utilities.rs
  comms/dht/examples/propagation_stress.rs
  comms/dht/src/config.rs
  comms/dht/src/outbound/requester.rs
  comms/dht/tests/dht.rs
Labels: P-reviews_required, P-acks_required

#6603 chore: upgrade prost and tonic (ring dep)
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/build.rs
  applications/minotari_app_grpc/src/conversions/base_node_state.rs
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/block_template_data.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/base_node/proto/wallet_rpc.rs
  base_layer/p2p/Cargo.toml
  base_layer/p2p/src/comms_connector/pubsub.rs
  base_layer/p2p/src/services/liveness/message.rs
  base_layer/wallet/Cargo.toml
  clients/rust/wallet_grpc_client/Cargo.toml
  comms/core/Cargo.toml
  comms/core/src/protocol/rpc/error.rs
  comms/dht/Cargo.toml
  comms/dht/src/envelope.rs
  comms/dht/src/store_forward/saf_handler/task.rs
  comms/dht/tests/dht.rs
  comms/rpc_macros/Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-reviews_required, P-acks_required

#6588 feat: ledger stax + flex support
  applications/minotari_ledger_wallet/common/src/common_types.rs
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_ledger_wallet/wallet/README.md
  applications/minotari_ledger_wallet/wallet/key_32x32.gif
  applications/minotari_ledger_wallet/wallet/key_40x40.gif
  applications/minotari_ledger_wallet/wallet/key_64x64.gif
  applications/minotari_ledger_wallet/wallet/ledger_app.toml
  applications/minotari_ledger_wallet/wallet/src/app_ui/menu.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_dh_shared_secret.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_one_sided_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_public_key.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_public_spend_key.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_schnorr_signature.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_view_key.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  applications/minotari_ledger_wallet/wallet/src/utils.rs
Labels: CR-insufficient_context, P-acks_required

#6604 feat: dont sync local only peers
  comms/core/src/peer_validator/helpers.rs
  comms/dht/src/actor.rs
  comms/dht/src/config.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6605 fix(dns): fix Display impl to match from_str
  common/src/configuration/name_server.rs
Labels: P-reviews_required, P-acks_required

#6606 feat: update pre_mine specification
  base_layer/core/src/blocks/pre_mine/mod.rs
Labels: P-reviews_required, P-acks_required

#6601 feat!: add input mr into genesis block
  applications/minotari_console_wallet/src/automation/commands.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/error.rs
  base_layer/core/src/base_node/sync/horizon_state_sync/synchronizer.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/chain_storage/blockchain_database.rs
  base_layer/core/src/chain_storage/error.rs
  base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-reviews_required, P-acks_required

#6607 feat: add default exclude dial
  base_layer/wallet/src/wallet.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/dht/src/config.rs
Labels: P-reviews_required, P-acks_required

#6608 feat!: add context to ffi callbacks
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/src/tasks.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
  integration_tests/src/ffi/wallet_address.rs
Labels: P-reviews_required, P-acks_required

#6609 feat!: esme test pre-mine with immediate spend
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
  base_layer/core/src/validation/test.rs
  common/src/configuration/network.rs
Labels: P-reviews_required, P-acks_required

#6611 chore(ci): add riscv64 builds and misc script fixes
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  Cargo.lock
  Cross.toml
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_grpc/src/tls/error.rs
  applications/minotari_app_utilities/Cargo.toml
  scripts/cross_compile_ubuntu_18-pre-build.sh
  scripts/file_license_check.sh
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#6610 chore: changes mainnet default network
  common/src/configuration/network.rs
Labels: CR-insufficient_context, P-acks_required

#6612 feat: pre-mine introduce temp ban and add counters
  applications/minotari_console_wallet/src/automation/commands.rs
  base_layer/wallet/src/connectivity_service/base_node_peer_manager.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/interface.rs
  base_layer/wallet/src/connectivity_service/mock.rs
Labels: P-reviews_required, P-acks_required

#6613 feat: enable identity grpc method by default
  common/config/presets/c_base_node_b_mining_allow_methods.toml
  common/config/presets/c_base_node_b_non_mining_allow_methods.toml
Labels: P-acks_required

#6614 chore: new release esme v1.6.0-pre.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6615 feat: exit logic for pre-mine spend
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
Labels: P-acks_required

#6618 feat: improve mempool error msg when mempool out of sync
  base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
Labels: P-acks_required

#6620 feat: add FFI function to create seed words from Mbase58 encrypted cipher seed
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/cli.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6621 feat: upgrade utils
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/utils.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  hashing/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  integration_tests/Cargo.toml
Labels: P-reviews_required, P-acks_required

#6623 chore: update pre mine funds
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/mainnet_pre_mine.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6619 feat: improve base node connection from the wallet
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/base_node_peer_manager.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/connectivity_service/test.rs
Labels: P-reviews_required, P-acks_required

#6624 fix: example mainnet config seed section
  common/config/presets/b_peer_seeds.toml
Labels: P-reviews_required, P-acks_required

#6625 chore: new release esmeralda v1.7.0-pre.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  changelog-stagenet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6626 chore: new release nextnet v1.7.0-rc.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6627 chore: new version stagenet v1.7.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6628 feat: add checked_sub
  base_layer/core/src/proof_of_work/accumulated_difficulty.rs
Labels: P-acks_required

#6629 feat: add dns resiliency
  base_layer/p2p/src/config.rs
  base_layer/p2p/src/dns/error.rs
  base_layer/p2p/src/initialization.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  common/config/presets/b_peer_seeds.toml
  common/src/configuration/dns_name_server_list.rs
  common/src/configuration/mod.rs
  common/src/configuration/name_server.rs
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/wallet.rs
Labels: P-reviews_required, P-acks_required

#6631 chore: new release esme ralda v1.7.0-pre.1
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6632 chore: new nextnet version v1.7.0-rc.1
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6633 fix: view-only wallet scan
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/utxo_scanner/mod.rs
Labels: P-reviews_required, P-acks_required

#6634 chore: new release esmeralda v1.7.0-pre.2
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6635 chore: new release nextnet 1.7.0-rc.2
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6636 feat: change ffi wallet recovery interface
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
  integration_tests/src/ffi/ffi_import.rs
Labels: P-acks_required

#6637 feat: add proxy monerod resiliency
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/config.rs
  applications/minotari_merge_mining_proxy/src/error.rs
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  applications/minotari_merge_mining_proxy/src/proxy.rs
  applications/minotari_merge_mining_proxy/src/run_merge_miner.rs
  base_layer/wallet_ffi/wallet.h
  common/config/presets/f_merge_mining_proxy.toml
Labels: P-reviews_required, P-acks_required

#6638 test: add DammSum known-answer test
  base_layer/common_types/src/dammsum.rs
Labels: P-acks_required

#6639 test: add merge mining proxy monerod stress test code
  applications/minotari_merge_mining_proxy/src/proxy.rs
Labels: P-reviews_required, P-acks_required

#6642 chore: release new esmeralda v1.7.0-pre.3
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6643 chore: new release nextnet v1.7.0-rc.3
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6647 chore: new release esmeralda
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6648 chore: new release nextnet 1.7.0-rc.4
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context

#6649 feat: close rpc connections when not in use - without close on dial requests
  applications/minotari_merge_mining_proxy/src/monero_fail.rs
  applications/minotari_node/src/bootstrap.rs
  base_layer/contacts/tests/contacts_service.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/tests/helpers/nodes.rs
  base_layer/p2p/src/config.rs
  base_layer/wallet/src/base_node_service/monitor.rs
  base_layer/wallet/src/connectivity_service/handle.rs
  base_layer/wallet/src/connectivity_service/interface.rs
  base_layer/wallet/src/connectivity_service/mock.rs
  base_layer/wallet/src/connectivity_service/service.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet_ffi/src/lib.rs
  common/config/presets/c_base_node_c.toml
  common/config/presets/d_console_wallet.toml
  comms/core/src/connection_manager/peer_connection.rs
  comms/core/src/protocol/rpc/client/mod.rs
  comms/core/src/protocol/rpc/client/pool.rs
  comms/core/src/protocol/rpc/handshake.rs
  comms/core/src/protocol/rpc/server/handle.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/core/src/protocol/rpc/test/greeting_service.rs
  comms/core/src/protocol/rpc/test/smoke.rs
  comms/core/tests/tests/rpc.rs
  comms/dht/src/store_forward/service.rs
  comms/rpc_macros/src/generator.rs
Labels: P-reviews_required, P-acks_required

#6651 chore: new release esme v1.8.0-pre.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  changelog-nextnet.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-reviews_required, P-acks_required
