Repository tari-project/tari, pull requests merged in 2024-08, with the labels that each got.

#6432 feat: add pre-mine create commands
  Cargo.lock
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/error.rs
  applications/minotari_console_wallet/src/automation/mod.rs
  applications/minotari_console_wallet/src/automation/utils.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  applications/minotari_ledger_wallet/common/src/common_types.rs
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/common_types/src/key_branches.rs
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/Cargo.toml
  base_layer/core/src/blocks/mod.rs
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/mod.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/handle.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: CR-too_long, P-reviews_required, P-acks_required

#6433 feat: check address features on send
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-reviews_required, P-acks_required

#6403 ci(feature): check for signed commits
  .github/workflows/pr_signed_commits_check.yml
Labels: P-reviews_required, P-acks_required

#6430 chore: remove temp code
  applications/minotari_merge_mining_proxy/src/proxy.rs
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
  common/src/build/application.rs
Labels: CR-insufficient_context, P-acks_required

#6440 feat: add scanned height
  applications/minotari_console_wallet/src/ui/components/base_node.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/state/wallet_event_monitor.rs
  base_layer/wallet_ffi/src/callback_handler.rs
  base_layer/wallet_ffi/src/callback_handler_tests.rs
  base_layer/wallet_ffi/src/lib.rs
  base_layer/wallet_ffi/wallet.h
Labels: P-acks_required

#6441 fix: lagging code
  base_layer/core/src/base_node/state_machine_service/states/listening.rs
Labels: P-reviews_required, P-acks_required

#6444 feat: add memory db key manager util function
  base_layer/core/src/transactions/key_manager/memory_db_key_manager.rs
  base_layer/core/src/transactions/key_manager/mod.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6443 feat: update Ledger readme
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/wallet/README.md
Labels: P-reviews_required, P-acks_required

#6445 feat: add identify to allowed grpc mining methods
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: CR-insufficient_context, P-acks_required

#6447 feat: add private view key function
  applications/minotari_app_utilities/src/utilities.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
Labels: P-acks_required

#6446 feat: add zeroize to memory_key_manager
  base_layer/core/src/transactions/key_manager/memory_db_key_manager.rs
Labels: P-acks_required

#6449 feat: add timestamp to grpc
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_app_grpc/src/conversions/chain_metadata.rs
Labels: CR-insufficient_context

#6450 chore: new release esmeralda v1.1.0-pre.0
  Cargo.lock
  README.md
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6452 fix: comms key managedment
  applications/minotari_console_wallet/src/init/mod.rs
  base_layer/common_types/src/wallet_types.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: P-reviews_required, P-acks_required

#6455 feat: console wallet recovery improvements for ledger
  applications/minotari_console_wallet/src/lib.rs
Labels: P-reviews_required, P-acks_required

#6448 feat: prepare MM backend stuff
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_miner/src/run_miner.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/mainnet_pre_mine.json
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/mempool/service/handle.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
Labels: P-reviews_required, P-acks_required

#6456 feat: add pre-mine fail-safe height
  applications/minotari_console_wallet/src/automation/commands.rs
  base_layer/core/src/blocks/pre_mine/mod.rs
Labels: P-reviews_required, P-acks_required

#6451 feat: remove pre-mine create commands from the console wallet
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/mod.rs
  applications/minotari_console_wallet/src/automation/utils.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
Labels: P-reviews_required, P-acks_required

#6458 feat: don't permit trying to send interactive transfers from hardware devices
  applications/minotari_console_wallet/src/ui/app.rs
  applications/minotari_console_wallet/src/ui/components/send_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  applications/minotari_console_wallet/src/ui/ui_error.rs
Labels: P-reviews_required, P-acks_required

#6459 feat: add ability to specify log location
  applications/minotari_app_utilities/src/common_cli_args.rs
  applications/minotari_console_wallet/src/lib.rs
  applications/minotari_console_wallet/src/main.rs
  applications/minotari_merge_mining_proxy/src/main.rs
  applications/minotari_node/src/lib.rs
  applications/minotari_node/src/main.rs
  integration_tests/src/merge_mining_proxy.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet_process.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6457 feat: check encumbrance later
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-reviews_required, P-acks_required

#6460 feat: add new esmeralda pre-mine for test
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/automation/utils.rs
  applications/minotari_console_wallet/src/cli.rs
  applications/minotari_console_wallet/src/wallet_modes.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
Labels: P-acks_required

#6462 feat!: ledger metadata signature with receiver adress confirmation
  Cargo.lock
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/common/src/common_types.rs
  applications/minotari_ledger_wallet/common/src/lib.rs
  applications/minotari_ledger_wallet/common/src/utils.rs
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/comms/src/lib.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_one_sided_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/interface.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
  base_layer/core/src/transactions/transaction_components/wallet_output_builder.rs
  base_layer/wallet/src/transaction_service/service.rs
Labels: P-reviews_required, P-acks_required

#6465 feat: update sender offset key
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-reviews_required, P-acks_required

#6461 feat: check wallet type on send + ui fixes
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_console_wallet/src/init/mod.rs
  applications/minotari_console_wallet/src/ui/components/base_node.rs
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  applications/minotari_console_wallet/src/ui/state/app_state.rs
  base_layer/core/src/transactions/aggregated_body.rs
  base_layer/core/src/transactions/key_manager/initializer.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/key_manager/memory_db_key_manager.rs
  base_layer/core/src/transactions/key_manager/wrapper.rs
  base_layer/wallet/src/transaction_service/error.rs
  base_layer/wallet/src/transaction_service/mod.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/wallet.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/transaction_protocols.rs
Labels: P-reviews_required, P-acks_required

#6464 fix: stop reuse of nonce keys
  base_layer/common_types/src/key_branches.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
Labels: P-reviews_required, P-acks_required

#6466 fix: backup spend
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/wallet/src/output_manager_service/service.rs
Labels: P-reviews_required, P-acks_required

#6469 chore: fix cucumber tests
  integration_tests/src/ffi/callbacks.rs
  integration_tests/src/ffi/comms_config.rs
  integration_tests/src/ffi/ffi_import.rs
  integration_tests/src/ffi/public_key.rs
  integration_tests/src/ffi/transport_config.rs
  integration_tests/src/ffi/wallet.rs
Labels: CR-insufficient_context, P-acks_required

#6468 fix: wallet validation
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/wallet/src/base_node_service/config.rs
  base_layer/wallet/src/output_manager_service/tasks/txo_validation_task.rs
  base_layer/wallet/src/transaction_service/tasks/check_faux_transaction_status.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  common/config/presets/d_console_wallet.toml
Labels: P-reviews_required, P-acks_required

#6471 feat: add new genesis blocks
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
  base_layer/core/src/blocks/pre_mine/mainnet_pre_mine.json
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/core/src/consensus/consensus_constants.rs
Labels: P-reviews_required, P-acks_required

#6472 feat!: add source address to encrypted data
  applications/minotari_console_wallet/src/ui/components/transactions_tab.rs
  base_layer/common_types/src/tari_address/dual_address.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/common_types/src/tari_address/single_address.rs
  base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/encrypted_data.rs
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.proto
  base_layer/core/src/transactions/transaction_protocol/proto/transaction_sender.rs
  base_layer/core/src/transactions/transaction_protocol/recipient.rs
  base_layer/core/src/transactions/transaction_protocol/sender.rs
  base_layer/core/src/transactions/transaction_protocol/single_receiver.rs
  base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/core/tests/tests/node_comms_interface.rs
  base_layer/wallet/src/output_manager_service/mod.rs
  base_layer/wallet/src/output_manager_service/resources.rs
  base_layer/wallet/src/output_manager_service/service.rs
  base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
  base_layer/wallet/src/transaction_service/service.rs
  base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
  base_layer/wallet/src/transaction_service/tasks/send_transaction_reply.rs
  base_layer/wallet/src/utxo_scanner_service/utxo_scanner_task.rs
  base_layer/wallet/tests/output_manager_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/service.rs
  base_layer/wallet/tests/transaction_service_tests/storage.rs
Labels: P-reviews_required, P-acks_required

#6476 chore: new release esmeralda 1.2.0-pre.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required

#6453 ci(feature): add minotari_ledger_wallet build
  .github/workflows/build_ledger_wallet.yml
Labels: P-reviews_required, P-acks_required

#6483 docs: fix Ledger hash documentation
  applications/minotari_ledger_wallet/wallet/src/utils.rs
Labels: P-reviews_required, P-acks_required

#6482 fix: avoid an underflow in Ledger BIP32 path parsing
  applications/minotari_ledger_wallet/wallet/src/utils.rs
Labels: P-acks_required

#6479 fix: default ledger wallet
  applications/minotari_console_wallet/Cargo.toml
  base_layer/wallet/Cargo.toml
Labels: P-acks_required

#6470 chore: add panics to cucumber tests
  integration_tests/src/chat_ffi.rs
  integration_tests/src/ffi/balance.rs
  integration_tests/src/ffi/completed_transaction.rs
  integration_tests/src/ffi/completed_transactions.rs
  integration_tests/src/ffi/contact.rs
  integration_tests/src/ffi/contacts.rs
  integration_tests/src/ffi/contacts_liveness_data.rs
  integration_tests/src/ffi/fee_per_gram_stat.rs
  integration_tests/src/ffi/fee_per_gram_stats.rs
  integration_tests/src/ffi/ffi_bytes.rs
  integration_tests/src/ffi/kernel.rs
  integration_tests/src/ffi/pending_inbound_transaction.rs
  integration_tests/src/ffi/pending_inbound_transactions.rs
  integration_tests/src/ffi/pending_outbound_transaction.rs
  integration_tests/src/ffi/pending_outbound_transactions.rs
  integration_tests/src/ffi/private_key.rs
  integration_tests/src/ffi/public_keys.rs
  integration_tests/src/ffi/seed_words.rs
  integration_tests/src/ffi/transaction_send_status.rs
  integration_tests/src/ffi/vector.rs
  integration_tests/src/ffi/wallet.rs
  integration_tests/src/ffi/wallet_address.rs
  integration_tests/src/merge_mining_proxy.rs
Labels: P-reviews_required, P-acks_required

#6478 fix: contact service tari address support
  applications/minotari_console_wallet/src/ui/components/contacts_tab.rs
  base_layer/common_types/src/tari_address/mod.rs
  base_layer/contacts/src/contacts_service/storage/sqlite_db.rs
  base_layer/contacts/src/contacts_service/storage/types/contacts.rs
  base_layer/contacts/src/contacts_service/types/contact.rs
  base_layer/wallet_ffi/src/error.rs
Labels: P-reviews_required, P-acks_required

#6486 chore: fix flaky test + remove unused code
  base_layer/core/src/proof_of_work/difficulty.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/tests/tests/node_state_machine.rs
Labels: P-acks_required

#6473 feat: limit open-ended vectors
  applications/minotari_app_grpc/src/conversions/block_header.rs
  applications/minotari_app_grpc/src/conversions/new_block_template.rs
  applications/minotari_app_grpc/src/conversions/output_features.rs
  applications/minotari_app_grpc/src/conversions/proof_of_work.rs
  applications/minotari_console_wallet/src/automation/commands.rs
  applications/minotari_merge_mining_proxy/src/block_template_data.rs
  applications/minotari_merge_mining_proxy/src/block_template_protocol.rs
  applications/minotari_merge_mining_proxy/src/error.rs
  applications/minotari_miner/src/errors.rs
  applications/minotari_miner/src/run_miner.rs
  applications/minotari_miner/src/stratum/error.rs
  applications/minotari_miner/src/stratum/stratum_controller/controller.rs
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  base_layer/common_types/src/lib.rs
  base_layer/common_types/src/max_size/bytes.rs
  base_layer/common_types/src/max_size/mod.rs
  base_layer/common_types/src/max_size/vec.rs
  base_layer/contacts/src/contacts_service/types/message.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/blocks/pre_mine/esmeralda_pre_mine.json
  base_layer/core/src/blocks/pre_mine/igor_pre_mine.json
  base_layer/core/src/blocks/pre_mine/mainnet_pre_mine.json
  base_layer/core/src/blocks/pre_mine/mod.rs
  base_layer/core/src/blocks/pre_mine/nextnet_pre_mine.json
  base_layer/core/src/blocks/pre_mine/stagenet_pre_mine.json
  base_layer/core/src/common/mod.rs
  base_layer/core/src/common/waiting_requests.rs
  base_layer/core/src/consensus/consensus_constants.rs
  base_layer/core/src/consensus/consensus_encoding/hashing.rs
  base_layer/core/src/lib.rs
  base_layer/core/src/proof_of_work/mod.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/proof_of_work/monero_rx/pow_data.rs
  base_layer/core/src/proof_of_work/proof_of_work.rs
  base_layer/core/src/proto/block_header.rs
  base_layer/core/src/proto/transaction.rs
  base_layer/core/src/test_helpers/mod.rs
  base_layer/core/src/transactions/coinbase_builder.rs
  base_layer/core/src/transactions/test_helpers.rs
  base_layer/core/src/transactions/transaction_components/mod.rs
  base_layer/core/src/transactions/transaction_components/output_features.rs
  base_layer/core/src/validation/test.rs
  base_layer/core/tests/helpers/block_builders.rs
  base_layer/core/tests/tests/block_validation.rs
  base_layer/tari_mining_helper_ffi/src/lib.rs
  base_layer/wallet/src/output_manager_service/storage/sqlite_db/new_output_sql.rs
  base_layer/wallet_ffi/src/lib.rs
  common/src/configuration/network.rs
  integration_tests/src/miner.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: CR-too_long, P-reviews_required, P-acks_required

#6487 feat: ffi accessor function for payment id
  base_layer/wallet_ffi/src/lib.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6495 fix: backup spend
  base_layer/wallet/src/output_manager_service/service.rs
Labels: CR-insufficient_context, P-reviews_required, P-acks_required

#6492 fix!: don't use the ledger unless both keys are for ledger
  Cargo.lock
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/common/src/lib.rs
  applications/minotari_ledger_wallet/common/src/utils.rs
  applications/minotari_ledger_wallet/comms/src/accessor_methods.rs
  applications/minotari_ledger_wallet/comms/src/lib.rs
  applications/minotari_ledger_wallet/wallet/src/handlers/get_one_sided_metadata_signature.rs
  applications/minotari_ledger_wallet/wallet/src/main.rs
  base_layer/common_types/src/key_branches.rs
  base_layer/core/src/blocks/genesis_block.rs
  base_layer/core/src/transactions/key_manager/inner.rs
  base_layer/core/src/transactions/transaction_components/transaction_output.rs
Labels: P-reviews_required, P-acks_required

#6496 chore: fix wallet.h compile
  base_layer/wallet_ffi/wallet.h
Labels: CR-insufficient_context

#6500 chore: new release esmeralda v1.3.0-pre0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
Labels: CR-insufficient_context

#6498 fix(minotari node): add get_sync_progress to allow list if mining is enabled
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: P-acks_required

#6503 feat: ledger reconnect
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
  applications/minotari_ledger_wallet/comms/src/error.rs
  applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
Labels: P-reviews_required, P-acks_required

#6504 chore(api): get_sync_progress returns short_desc
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
Labels: P-reviews_required, P-acks_required

#6491 chore: test fixing cucumber on ci
  integration_tests/src/base_node_process.rs
  integration_tests/src/lib.rs
  integration_tests/src/wallet_process.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/Sync.feature
  integration_tests/tests/features/WalletFFI.feature
  integration_tests/tests/steps/node_steps.rs
  integration_tests/tests/steps/wallet_ffi_steps.rs
  integration_tests/tests/steps/wallet_steps.rs
Labels: P-reviews_required, P-acks_required

#6505 chore: reduce logging
  applications/minotari_node/src/grpc/base_node_grpc_server.rs
  comms/core/src/connection_manager/listener.rs
  comms/core/src/connection_manager/self_liveness.rs
  comms/core/src/connectivity/manager.rs
  comms/core/src/protocol/messaging/outbound.rs
  comms/core/src/protocol/messaging/protocol.rs
  comms/core/src/protocol/rpc/server/mod.rs
  comms/dht/src/connectivity/mod.rs
  comms/dht/src/outbound/broadcast.rs
  comms/dht/src/store_forward/service.rs
Labels: P-reviews_required, P-acks_required

#6506 fix: correct the expected return errors in ledger demo
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
Labels: P-acks_required

#6510 feat: improve header validation speed
  applications/minotari_ledger_wallet/comms/examples/ledger_demo/main.rs
  base_layer/core/src/proof_of_work/monero_rx/helpers.rs
  base_layer/core/src/validation/header/header_full_validator.rs
Labels: P-reviews_required, P-acks_required

#6515 chore: new release esmeralda 1.3.1-pre.0
  Cargo.lock
  applications/minotari_app_grpc/Cargo.toml
  applications/minotari_app_utilities/Cargo.toml
  applications/minotari_console_wallet/Cargo.toml
  applications/minotari_ledger_wallet/common/Cargo.toml
  applications/minotari_ledger_wallet/comms/Cargo.toml
  applications/minotari_ledger_wallet/wallet/Cargo.lock
  applications/minotari_ledger_wallet/wallet/Cargo.toml
  applications/minotari_merge_mining_proxy/Cargo.toml
  applications/minotari_miner/Cargo.toml
  applications/minotari_node/Cargo.toml
  base_layer/chat_ffi/Cargo.toml
  base_layer/common_types/Cargo.toml
  base_layer/contacts/Cargo.toml
  base_layer/contacts/src/chat_client/Cargo.toml
  base_layer/core/Cargo.toml
  base_layer/key_manager/Cargo.toml
  base_layer/mmr/Cargo.toml
  base_layer/p2p/Cargo.toml
  base_layer/service_framework/Cargo.toml
  base_layer/tari_mining_helper_ffi/Cargo.toml
  base_layer/wallet/Cargo.toml
  base_layer/wallet_ffi/Cargo.toml
  changelog-development.md
  common/Cargo.toml
  common/tari_features/Cargo.toml
  common_sqlite/Cargo.toml
  comms/core/Cargo.toml
  comms/dht/Cargo.toml
  comms/rpc_macros/Cargo.toml
  hashing/Cargo.toml
  infrastructure/derive/Cargo.toml
  infrastructure/libtor/Cargo.toml
  infrastructure/max_size/Cargo.toml
  infrastructure/metrics/Cargo.toml
  infrastructure/shutdown/Cargo.toml
  infrastructure/storage/Cargo.toml
  infrastructure/tari_script/Cargo.toml
  infrastructure/test_utils/Cargo.toml
  package-lock.json
Labels: CR-insufficient_context, P-acks_required
